/* Generated by Nim Compiler v1.9.3 */
#define NIM_INTBITS 32

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #define nimfrs_(proc, file, slots, length) \
    struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename;NI len;VarSlot s[slots];} FR_; \
    FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #define nimln_(n) \
    FR_.line = n;

  #define nimlf_(n, file) \
    FR_.line = n; FR_.filename = file;

typedef int tyArray__K3aHFXbhHM4GwklUcGylAw[4];
#include <sys/types.h>
#include <sys/sysctl.h>
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4294)(void);
static N_INLINE(void, popFrame)(void);
extern NIM_BOOL nimInErrorMode__system_u4097;
extern TFrame* framePtr__system_u3743;
extern TFrame* framePtr__system_u3743;
extern TFrame* framePtr__system_u3743;
extern TFrame* framePtr__system_u3743;
extern TFrame* framePtr__system_u3743;
extern TFrame* framePtr__system_u3743;
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (NIM_BOOL*)0;
	result = (&nimInErrorMode__system_u4097);
	return result;
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimSetMem__systemZmemory_u7(p_p0, ((int)0), size_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
BeforeRet_: ;
}
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u3743 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u3743).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u3743;
	framePtr__system_u3743 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4294();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u3743 = (*framePtr__system_u3743).prev;
}
N_LIB_PRIVATE N_NIMCALL(NI, ncpicountProcessors)(void) {
	NI result;
	tyArray__K3aHFXbhHM4GwklUcGylAw mib;
	NI numCPU;
	size_t len;
	int T1_;
	nimfr_("countProcessors", "D:\\nim\\lib\\pure\\concurrency\\cpuinfo.nim");
	result = (NI)0;
	nimZeroMem((void*)mib, sizeof(tyArray__K3aHFXbhHM4GwklUcGylAw));
	numCPU = (NI)0;
	nimlf_(68, "D:\\nim\\lib\\pure\\concurrency\\cpuinfo.nim");
	mib[(((NI)0))- 0] = ((int)6);
	nimln_(69);
	mib[(((NI)1))- 0] = ((int)25);
	nimln_(70);
	len = ((size_t)4);
	nimln_(71);
	T1_ = (int)0;
	T1_ = sysctl(mib, ((int)2), ((void*) ((&numCPU))), (&len), NIM_NIL, ((size_t)0));
	(void)(T1_);
	nimln_(72);
	{
		int T6_;
		if (!(numCPU < ((NI)1))) goto LA4_;
		nimln_(73);
		mib[(((NI)1))- 0] = ((int)3);
		nimln_(74);
		T6_ = (int)0;
		T6_ = sysctl(mib, ((int)2), ((void*) ((&numCPU))), (&len), NIM_NIL, ((size_t)0));
		(void)(T6_);
	}
LA4_: ;
	nimln_(75);
	result = numCPU;
	nimln_(89);
	{
		if (!(result <= ((NI)0))) goto LA9_;
		result = ((NI)0);
	}
LA9_: ;
	popFrame();
	return result;
}
