/* Generated by Nim Compiler v1.9.3 */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <stdlib.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #define nimfrs_(proc, file, slots, length) \
    struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename;NI len;VarSlot s[slots];} FR_; \
    FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #define nimln_(n) \
    FR_.line = n;

  #define nimlf_(n, file) \
    FR_.line = n; FR_.filename = file;

typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyTuple__7q7q3E6Oj24ZNVJb9aonhAg tyTuple__7q7q3E6Oj24ZNVJb9aonhAg;
typedef struct tyObject_WideCStringObj__qZlS9aXUUYG9cVv6VNCsI5NQ tyObject_WideCStringObj__qZlS9aXUUYG9cVv6VNCsI5NQ;
typedef struct tyObject_WIN32_FIND_DATA__m9cbpw3LqlaVzCliEIMPxoA tyObject_WIN32_FIND_DATA__m9cbpw3LqlaVzCliEIMPxoA;
typedef struct tyObject_FILETIME__w49a7nuWXU45gvkyLJUCKdA tyObject_FILETIME__w49a7nuWXU45gvkyLJUCKdA;
typedef struct tyObject_OSError__364R2OEHwjKXXXZy8WY36g tyObject_OSError__364R2OEHwjKXXXZy8WY36g;
typedef struct tyObject_CatchableError__gR37KDrjbfwtwdSWyHspqA tyObject_CatchableError__gR37KDrjbfwtwdSWyHspqA;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tySequence__OC4OxQhfzCBuUQxMi5llBQ tySequence__OC4OxQhfzCBuUQxMi5llBQ;
typedef struct tySequence__OC4OxQhfzCBuUQxMi5llBQ_Content tySequence__OC4OxQhfzCBuUQxMi5llBQ_Content;
typedef struct tyObject_Time__f8Ov9bPTwk6nAIjCM1lESAw tyObject_Time__f8Ov9bPTwk6nAIjCM1lESAw;
typedef struct tyObject_StackTraceEntry__cwz3X1atIa8ET8VanDA2pw tyObject_StackTraceEntry__cwz3X1atIa8ET8VanDA2pw;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
typedef NU8 tySet_tyChar__nmiMWKVIe46vacnhAFrQvw[32];
struct tyTuple__7q7q3E6Oj24ZNVJb9aonhAg {
NimStringV2 Field0;
NimStringV2 Field1;
NimStringV2 Field2;
};
struct tyObject_WideCStringObj__qZlS9aXUUYG9cVv6VNCsI5NQ {
	NI bytes;
	NI16* data;
};
typedef N_STDCALL_PTR(NI32, tyProc__G0MNqLrkAnRVz4cDlgVcRg) (NI handle_p0, NI16* buf_p1, NI32 size_p2);
typedef NI16 tyUncheckedArray__Tyd4y3haUOOHTj71TPIRag[1];
typedef N_STDCALL_PTR(NI32, tyProc__Rzv0SS9bu3vYSxhvPQEKMBQ) (NI16* lpFileName_p0, NI32 nBufferLength_p1, NI16* lpBuffer_p2, NI16** lpFilePart_p3);
struct tyObject_FILETIME__w49a7nuWXU45gvkyLJUCKdA {
	NI32 dwLowDateTime;
	NI32 dwHighDateTime;
};
typedef NI16 tyArray__EKfNt9b8uxndgFbu2Ky3XAQ[260];
typedef NI16 tyArray__Get9cpRTS5VjGKP6CDsI9bYA[14];
struct tyObject_WIN32_FIND_DATA__m9cbpw3LqlaVzCliEIMPxoA {
	NI32 dwFileAttributes;
	tyObject_FILETIME__w49a7nuWXU45gvkyLJUCKdA ftCreationTime;
	tyObject_FILETIME__w49a7nuWXU45gvkyLJUCKdA ftLastAccessTime;
	tyObject_FILETIME__w49a7nuWXU45gvkyLJUCKdA ftLastWriteTime;
	NI32 nFileSizeHigh;
	NI32 nFileSizeLow;
	NI32 dwReserved0;
	NI32 dwReserved1;
	tyArray__EKfNt9b8uxndgFbu2Ky3XAQ cFileName;
	tyArray__Get9cpRTS5VjGKP6CDsI9bYA cAlternateFileName;
};
typedef N_STDCALL_PTR(NI32, tyProc__9a9b4MhG9cyzdGMncqnn5oCMg) (NI hFindFile_p0, tyObject_WIN32_FIND_DATA__m9cbpw3LqlaVzCliEIMPxoA* lpFindFileData_p1);
typedef N_STDCALL_PTR(NI32, tyProc__9bXer9a4ps9aSGctILcxWReVw) (void);
typedef N_STDCALL_PTR(void, tyProc__ofoySXaAAlxxs9bQS9a1etlg) (NI hFindFile_p0);
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
};
struct RootObj {
TNimTypeV2* m_type;
};
struct tySequence__OC4OxQhfzCBuUQxMi5llBQ {
  NI len; tySequence__OC4OxQhfzCBuUQxMi5llBQ_Content* p;
};
struct Exception {
  RootObj Sup;
	Exception* parent;
	NCSTRING name;
	NimStringV2 message;
	tySequence__OC4OxQhfzCBuUQxMi5llBQ trace;
	Exception* up;
};
struct tyObject_CatchableError__gR37KDrjbfwtwdSWyHspqA {
  Exception Sup;
};
struct tyObject_OSError__364R2OEHwjKXXXZy8WY36g {
  tyObject_CatchableError__gR37KDrjbfwtwdSWyHspqA Sup;
	NI32 errorCode;
};
typedef NimStringV2 tyArray__24KAM9afIUgUaqBaEBB6r9bg[3];
struct tyObject_Time__f8Ov9bPTwk6nAIjCM1lESAw {
	NI64 seconds;
	NI nanosecond;
};
struct tyObject_StackTraceEntry__cwz3X1atIa8ET8VanDA2pw {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};


#ifndef tySequence__OC4OxQhfzCBuUQxMi5llBQ_Content_PP
#define tySequence__OC4OxQhfzCBuUQxMi5llBQ_Content_PP
struct tySequence__OC4OxQhfzCBuUQxMi5llBQ_Content { NI cap; tyObject_StackTraceEntry__cwz3X1atIa8ET8VanDA2pw data[SEQ_DECL_SIZE];};
#endif

      N_LIB_PRIVATE N_NIMCALL(NimStringV2, nospquoteShellWindows)(NimStringV2 s_p0);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, contains__pureZstrutils_u1893)(NimStringV2 s_p0, tySet_tyChar__nmiMWKVIe46vacnhAFrQvw chars_p1);
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(void, copyMem__system_u1720)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
N_LIB_PRIVATE N_NIMCALL(void, prepareAdd)(NimStringV2* s_p0, NI addlen_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
static N_INLINE(void, nimAddCharV1)(NimStringV2* s_p0, NIM_CHAR c_p1);
N_LIB_PRIVATE N_NIMCALL(void, setLengthStrV2)(NimStringV2* s_p0, NI newLen_p1);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__stdZassertions_u274)(NimStringV2 msg_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___stdZassertions_u16)(NimStringV2* dest_p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4294)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nospquoteShell)(NimStringV2 s_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___stdZassertions_u19)(NimStringV2* dest_p0, NimStringV2 src_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nosgetHomeDir)(void);
static N_INLINE(NimStringV2, slash___stdZprivateZospaths50_u90)(NimStringV2 head_p0, NimStringV2 tail_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nosjoinPath)(NimStringV2 head_p0, NimStringV2 tail_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, substr__system_u7976)(NimStringV2 s_p0, NI first_p1);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(void, nossplitFile)(NimStringV2 path_p0, tyTuple__7q7q3E6Oj24ZNVJb9aonhAg* Result);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nosgetAppFilename)(void);
N_LIB_PRIVATE N_NIMCALL(tyObject_WideCStringObj__qZlS9aXUUYG9cVv6VNCsI5NQ, newWideCString__stdZwidestrs_u271)(NCSTRING source_p0, NI L_p1);
static N_INLINE(NI16*, toWideCString__stdZwidestrs_u45)(tyObject_WideCStringObj__qZlS9aXUUYG9cVv6VNCsI5NQ x_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___stdZassertions_u22)(NimStringV2* dest_p0, NimStringV2 src_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___stdZwidestrs_u31)(tyObject_WideCStringObj__qZlS9aXUUYG9cVv6VNCsI5NQ* a_p0, tyObject_WideCStringObj__qZlS9aXUUYG9cVv6VNCsI5NQ b_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___stdZwidestrs_u375)(tyObject_WideCStringObj__qZlS9aXUUYG9cVv6VNCsI5NQ s_p0, NI estimate_p1, NI replacement_p2);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___stdZwidestrs_u6)(tyObject_WideCStringObj__qZlS9aXUUYG9cVv6VNCsI5NQ* a_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___stdZprivateZosdirs_u84)(tyTuple__7q7q3E6Oj24ZNVJb9aonhAg* dest_p0);
N_LIB_PRIVATE N_NIMCALL(tyObject_WideCStringObj__qZlS9aXUUYG9cVv6VNCsI5NQ, newWideCString__stdZwidestrs_u303)(NimStringV2 s_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseOSError__stdZoserrors_u102)(NI32 errorCode_p0, NimStringV2 additionalInfo_p1);
N_LIB_PRIVATE N_NIMCALL(NI32, osLastError__stdZoserrors_u105)(void);
N_LIB_PRIVATE N_NIMCALL(NI, findFirstFile__stdZprivateZoscommon_u25)(NimStringV2 a_p0, tyObject_WIN32_FIND_DATA__m9cbpw3LqlaVzCliEIMPxoA* b_p1);
N_LIB_PRIVATE N_NIMCALL(NI, searchExtPos__stdZprivateZospaths50_u291)(NimStringV2 path_p0);
static N_INLINE(NIM_BOOL, skipFindData__stdZprivateZoscommon_u34)(tyObject_WIN32_FIND_DATA__m9cbpw3LqlaVzCliEIMPxoA* f_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___stdZwidestrs_u372)(NI16* s_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___stdZassertions_u13)(NimStringV2* dest_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nosextractFilename)(NimStringV2 path_p0);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nosfileExists)(NimStringV2 filename_p0);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nosdirExists)(NimStringV2 dir_p0);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size_p0, NI alignment_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, rawNewString)(NI space_p0);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e_p0, NCSTRING ename_p1, NCSTRING procname_p2, NCSTRING filename_p3, NI line_p4);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nosaddFileExt)(NimStringV2 filename_p0, NimStringV2 ext_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, getEnv__stdZenvvars_u32)(NimStringV2 key_p0, NimStringV2 default_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, substr__system_u7964)(NimStringV2 s_p0, NI first_p1, NI last_p2);
static N_INLINE(NIM_CHAR, X5BX5D___system_u7429)(NimStringV2 s_p0, NI i_p1);
N_LIB_PRIVATE N_NIMCALL(int, exitStatusLikeShell__pureZos_u183)(int status_p0);
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0);
N_LIB_PRIVATE N_NIMCALL(tyObject_Time__f8Ov9bPTwk6nAIjCM1lESAw, fromWinTime__pureZtimes_u1131)(NI64 win_p0);
N_LIB_PRIVATE N_NIMCALL(NI64, rdFileTime__windowsZwinlean_u284)(tyObject_FILETIME__w49a7nuWXU45gvkyLJUCKdA f_p0);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, ntLtTime)(tyObject_Time__f8Ov9bPTwk6nAIjCM1lESAw a_p0, tyObject_Time__f8Ov9bPTwk6nAIjCM1lESAw b_p1);
N_LIB_PRIVATE N_NIMCALL(tyObject_Time__f8Ov9bPTwk6nAIjCM1lESAw, nosgetLastModificationTime)(NimStringV2 file_p0);
static NIM_CONST tySet_tyChar__nmiMWKVIe46vacnhAFrQvw TM__yu6cxgKBBXbNsTkT9cyMd4g_2 = {
0x00, 0x02, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
;
static const struct {
  NI cap; NIM_CHAR data[0+1];
} TM__yu6cxgKBBXbNsTkT9cyMd4g_3 = { 0 | NIM_STRLIT_FLAG, "" };
static const NimStringV2 TM__yu6cxgKBBXbNsTkT9cyMd4g_4 = {0, (NimStrPayload*)&TM__yu6cxgKBBXbNsTkT9cyMd4g_3};
static const NimStringV2 TM__yu6cxgKBBXbNsTkT9cyMd4g_5 = {0, (NimStrPayload*)&TM__yu6cxgKBBXbNsTkT9cyMd4g_3};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__yu6cxgKBBXbNsTkT9cyMd4g_6 = { 1 | NIM_STRLIT_FLAG, "\"" };
static const NimStringV2 TM__yu6cxgKBBXbNsTkT9cyMd4g_7 = {1, (NimStrPayload*)&TM__yu6cxgKBBXbNsTkT9cyMd4g_6};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__yu6cxgKBBXbNsTkT9cyMd4g_14 = { 2 | NIM_STRLIT_FLAG, "\\\"" };
static const NimStringV2 TM__yu6cxgKBBXbNsTkT9cyMd4g_15 = {2, (NimStrPayload*)&TM__yu6cxgKBBXbNsTkT9cyMd4g_14};
static const struct {
  NI cap; NIM_CHAR data[111+1];
} TM__yu6cxgKBBXbNsTkT9cyMd4g_17 = { 111 | NIM_STRLIT_FLAG, "D:\\nim\\lib\\system\\iterators.nim(264, 11) `len(a) == L` the length of the string changed while iterating over it" };
static const NimStringV2 TM__yu6cxgKBBXbNsTkT9cyMd4g_18 = {111, (NimStrPayload*)&TM__yu6cxgKBBXbNsTkT9cyMd4g_17};
static const NimStringV2 TM__yu6cxgKBBXbNsTkT9cyMd4g_19 = {1, (NimStrPayload*)&TM__yu6cxgKBBXbNsTkT9cyMd4g_6};
static const NimStringV2 TM__yu6cxgKBBXbNsTkT9cyMd4g_20 = {0, (NimStrPayload*)&TM__yu6cxgKBBXbNsTkT9cyMd4g_3};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__yu6cxgKBBXbNsTkT9cyMd4g_21 = { 1 | NIM_STRLIT_FLAG, " " };
static const NimStringV2 TM__yu6cxgKBBXbNsTkT9cyMd4g_22 = {1, (NimStrPayload*)&TM__yu6cxgKBBXbNsTkT9cyMd4g_21};
static const NimStringV2 TM__yu6cxgKBBXbNsTkT9cyMd4g_24 = {0, (NimStrPayload*)&TM__yu6cxgKBBXbNsTkT9cyMd4g_3};
static const NimStringV2 TM__yu6cxgKBBXbNsTkT9cyMd4g_29 = {0, (NimStrPayload*)&TM__yu6cxgKBBXbNsTkT9cyMd4g_3};
extern TNimTypeV2 NTIv2__364R2OEHwjKXXXZy8WY36g_;
static const struct {
  NI cap; NIM_CHAR data[6+1];
} TM__yu6cxgKBBXbNsTkT9cyMd4g_30 = { 6 | NIM_STRLIT_FLAG, "file \'" };
static const NimStringV2 TM__yu6cxgKBBXbNsTkT9cyMd4g_31 = {6, (NimStrPayload*)&TM__yu6cxgKBBXbNsTkT9cyMd4g_30};
static const struct {
  NI cap; NIM_CHAR data[16+1];
} TM__yu6cxgKBBXbNsTkT9cyMd4g_32 = { 16 | NIM_STRLIT_FLAG, "\' does not exist" };
static const NimStringV2 TM__yu6cxgKBBXbNsTkT9cyMd4g_33 = {16, (NimStrPayload*)&TM__yu6cxgKBBXbNsTkT9cyMd4g_32};
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__yu6cxgKBBXbNsTkT9cyMd4g_35 = { 4 | NIM_STRLIT_FLAG, "PATH" };
static const NimStringV2 TM__yu6cxgKBBXbNsTkT9cyMd4g_36 = {4, (NimStrPayload*)&TM__yu6cxgKBBXbNsTkT9cyMd4g_35};
static const NimStringV2 TM__yu6cxgKBBXbNsTkT9cyMd4g_37 = {0, (NimStrPayload*)&TM__yu6cxgKBBXbNsTkT9cyMd4g_3};
static const NimStringV2 TM__yu6cxgKBBXbNsTkT9cyMd4g_45 = {0, (NimStrPayload*)&TM__yu6cxgKBBXbNsTkT9cyMd4g_3};
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__yu6cxgKBBXbNsTkT9cyMd4g_46 = { 3 | NIM_STRLIT_FLAG, "exe" };
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__yu6cxgKBBXbNsTkT9cyMd4g_47 = { 3 | NIM_STRLIT_FLAG, "cmd" };
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__yu6cxgKBBXbNsTkT9cyMd4g_48 = { 3 | NIM_STRLIT_FLAG, "bat" };
N_LIB_PRIVATE NIM_CONST tyArray__24KAM9afIUgUaqBaEBB6r9bg ExeExts__pureZos_u70 = {{3, (NimStrPayload*)&TM__yu6cxgKBBXbNsTkT9cyMd4g_46},
{3, (NimStrPayload*)&TM__yu6cxgKBBXbNsTkT9cyMd4g_47},
{3, (NimStrPayload*)&TM__yu6cxgKBBXbNsTkT9cyMd4g_48}}
;
extern NIM_BOOL nimInErrorMode__system_u4097;
extern TFrame* framePtr__system_u3743;
extern TFrame* framePtr__system_u3743;
extern TFrame* framePtr__system_u3743;
extern TFrame* framePtr__system_u3743;
extern TFrame* framePtr__system_u3743;
extern TFrame* framePtr__system_u3743;
extern tyProc__G0MNqLrkAnRVz4cDlgVcRg Dl_1409286341_;
extern tyProc__Rzv0SS9bu3vYSxhvPQEKMBQ Dl_1409286403_;
extern tyProc__9a9b4MhG9cyzdGMncqnn5oCMg Dl_1409286398_;
extern tyProc__9bXer9a4ps9aSGctILcxWReVw Dl_1409286315_;
extern tyProc__ofoySXaAAlxxs9bQS9a1etlg Dl_1409286401_;
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__system_u1720)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1) {
{	{
		NI TM__yu6cxgKBBXbNsTkT9cyMd4g_8;
		NI TM__yu6cxgKBBXbNsTkT9cyMd4g_9;
		if (!(((NI)0) < src_p1.len)) goto LA3_;
		if (nimAddInt(src_p1.len, ((NI)1), &TM__yu6cxgKBBXbNsTkT9cyMd4g_8)) { raiseOverflow(); goto BeforeRet_;
		};
		if (((NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_8)) < ((NI)0) || ((NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_8)) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI((NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_8), ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
		}
		copyMem__system_u1720(((void*) ((&(*(*dest_p0).p).data[(*dest_p0).len]))), ((void*) ((&(*src_p1.p).data[((NI)0)]))), ((NI) ((NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_8))));
		if (nimAddInt((*dest_p0).len, src_p1.len, &TM__yu6cxgKBBXbNsTkT9cyMd4g_9)) { raiseOverflow(); goto BeforeRet_;
		};
		(*dest_p0).len = (NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_9);
	}
LA3_: ;
	}
BeforeRet_: ;
}
static N_INLINE(void, nimAddCharV1)(NimStringV2* s_p0, NIM_CHAR c_p1) {
	NI TM__yu6cxgKBBXbNsTkT9cyMd4g_10;
	NI TM__yu6cxgKBBXbNsTkT9cyMd4g_11;
{	prepareAdd(s_p0, ((NI)1));
	(*(*s_p0).p).data[(*s_p0).len] = c_p1;
	if (nimAddInt((*s_p0).len, ((NI)1), &TM__yu6cxgKBBXbNsTkT9cyMd4g_10)) { raiseOverflow(); goto BeforeRet_;
	};
	(*(*s_p0).p).data[(NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_10)] = 0;
	if (nimAddInt((*s_p0).len, ((NI)1), &TM__yu6cxgKBBXbNsTkT9cyMd4g_11)) { raiseOverflow(); goto BeforeRet_;
	};
	(*s_p0).len = (NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_11);
	}
BeforeRet_: ;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (NIM_BOOL*)0;
	result = (&nimInErrorMode__system_u4097);
	return result;
}
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u3743 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u3743).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u3743;
	framePtr__system_u3743 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4294();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u3743 = (*framePtr__system_u3743).prev;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nospquoteShellWindows)(NimStringV2 s_p0) {
	NimStringV2 result;
	NimStringV2 backslashBuff;
	NIM_BOOL needQuote;
	NIM_BOOL T1_;
NIM_BOOL* nimErr_;
	nimfr_("quoteShellWindows", "D:\\nim\\lib\\pure\\os.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	backslashBuff.len = 0; backslashBuff.p = NIM_NIL;
	nimlf_(146, "D:\\nim\\lib\\pure\\os.nim");
	T1_ = (NIM_BOOL)0;
	T1_ = contains__pureZstrutils_u1893(s_p0, TM__yu6cxgKBBXbNsTkT9cyMd4g_2);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	if (T1_) goto LA2_;
	T1_ = (s_p0.len == ((NI)0));
LA2_: ;
	needQuote = T1_;
	nimln_(147);
	result = TM__yu6cxgKBBXbNsTkT9cyMd4g_4;
	nimln_(148);
	backslashBuff = TM__yu6cxgKBBXbNsTkT9cyMd4g_5;
	nimln_(149);
	{
		if (!needQuote) goto LA5_;
		nimln_(150);
		prepareAdd((&result), 1);
appendString((&result), TM__yu6cxgKBBXbNsTkT9cyMd4g_7);
	}
LA5_: ;
	{
		NIM_CHAR c;
		NI i;
		NI L;
		c = (NIM_CHAR)0;
		nimlf_(259, "D:\\nim\\lib\\system\\iterators.nim");
		i = ((NI)0);
		nimln_(260);
		L = s_p0.len;
		{
			nimln_(261);
			while (1) {
				NI TM__yu6cxgKBBXbNsTkT9cyMd4g_16;
				if (!(i < L)) goto LA9;
				nimlf_(152, "D:\\nim\\lib\\pure\\os.nim");
				if (i < 0 || i >= s_p0.len){ raiseIndexError2(i,s_p0.len-1); goto BeforeRet_;
				}
				c = s_p0.p->data[i];
				{
					nimln_(153);
					if (!((NU8)(c) == (NU8)(92))) goto LA12_;
					nimln_(154);
					nimAddCharV1((&backslashBuff), c);
				}
				goto LA10_;
LA12_: ;
				{
					nimln_(155);
					if (!((NU8)(c) == (NU8)(34))) goto LA15_;
					{
						NI i_2;
						NI colontmp_;
						NI TM__yu6cxgKBBXbNsTkT9cyMd4g_12;
						NI i_3;
						i_2 = (NI)0;
						colontmp_ = (NI)0;
						nimlf_(117, "D:\\nim\\lib\\system\\iterators_1.nim");
						nimlf_(156, "D:\\nim\\lib\\pure\\os.nim");
						if (nimMulInt(backslashBuff.len, ((NI)2), &TM__yu6cxgKBBXbNsTkT9cyMd4g_12)) { raiseOverflow(); goto BeforeRet_;
						};
						colontmp_ = (NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_12);
						nimlf_(119, "D:\\nim\\lib\\system\\iterators_1.nim");
						i_3 = ((NI)0);
						{
							nimln_(120);
							while (1) {
								NI TM__yu6cxgKBBXbNsTkT9cyMd4g_13;
								if (!(i_3 < colontmp_)) goto LA19;
								nimlf_(156, "D:\\nim\\lib\\pure\\os.nim");
								i_2 = i_3;
								nimAddCharV1((&result), 92);
								nimlf_(122, "D:\\nim\\lib\\system\\iterators_1.nim");
								if (nimAddInt(i_3, ((NI)1), &TM__yu6cxgKBBXbNsTkT9cyMd4g_13)) { raiseOverflow(); goto BeforeRet_;
								};
								i_3 = (NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_13);
							} LA19: ;
						}
					}
					nimlf_(158, "D:\\nim\\lib\\pure\\os.nim");
					setLengthStrV2((&backslashBuff), ((NI)0));
					nimln_(159);
					prepareAdd((&result), 2);
appendString((&result), TM__yu6cxgKBBXbNsTkT9cyMd4g_15);
				}
				goto LA10_;
LA15_: ;
				{
					nimln_(161);
					{
						if (!!((backslashBuff.len == ((NI)0)))) goto LA23_;
						nimln_(162);
						prepareAdd((&result), backslashBuff.len + 0);
appendString((&result), backslashBuff);
						nimln_(163);
						setLengthStrV2((&backslashBuff), ((NI)0));
					}
LA23_: ;
					nimln_(164);
					nimAddCharV1((&result), c);
				}
LA10_: ;
				nimlf_(263, "D:\\nim\\lib\\system\\iterators.nim");
				if (nimAddInt(i, ((NI)1), &TM__yu6cxgKBBXbNsTkT9cyMd4g_16)) { raiseOverflow(); goto BeforeRet_;
				};
				i = (NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_16);
				nimln_(264);
				{
					if (!!((s_p0.len == L))) goto LA27_;
					failedAssertImpl__stdZassertions_u274(TM__yu6cxgKBBXbNsTkT9cyMd4g_18);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				}
LA27_: ;
			} LA9: ;
		}
	}
	nimlf_(166, "D:\\nim\\lib\\pure\\os.nim");
	{
		if (!(((NI)0) < backslashBuff.len)) goto LA31_;
		nimln_(167);
		prepareAdd((&result), backslashBuff.len + 0);
appendString((&result), backslashBuff);
	}
LA31_: ;
	nimln_(168);
	{
		if (!needQuote) goto LA35_;
		nimln_(169);
		prepareAdd((&result), backslashBuff.len + 0);
appendString((&result), backslashBuff);
		nimln_(170);
		prepareAdd((&result), 1);
appendString((&result), TM__yu6cxgKBBXbNsTkT9cyMd4g_19);
	}
LA35_: ;
	nimlf_(25, "D:\\nim\\lib\\std\\assertions.nim");
	eqdestroy___stdZassertions_u16((&backslashBuff));
	}
BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nospquoteShell)(NimStringV2 s_p0) {
	NimStringV2 result;
NIM_BOOL* nimErr_;
	nimfr_("quoteShell", "D:\\nim\\lib\\pure\\os.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimlf_(191, "D:\\nim\\lib\\pure\\os.nim");
	result = nospquoteShellWindows(s_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, quoteShellCommand__pureZos_u57)(NimStringV2* args_p0, NI args_p0Len_0) {
	NimStringV2 result;
NIM_BOOL* nimErr_;
	nimfr_("quoteShellCommand", "D:\\nim\\lib\\pure\\os.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimlf_(204, "D:\\nim\\lib\\pure\\os.nim");
	result = TM__yu6cxgKBBXbNsTkT9cyMd4g_20;
	{
		NI i;
		NI colontmp_;
		NI i_2;
		i = (NI)0;
		colontmp_ = (NI)0;
		nimlf_(117, "D:\\nim\\lib\\system\\iterators_1.nim");
		nimlf_(205, "D:\\nim\\lib\\pure\\os.nim");
		colontmp_ = args_p0Len_0;
		nimlf_(119, "D:\\nim\\lib\\system\\iterators_1.nim");
		i_2 = ((NI)0);
		{
			nimln_(120);
			while (1) {
				NimStringV2 colontmpD_;
				NI TM__yu6cxgKBBXbNsTkT9cyMd4g_23;
				if (!(i_2 < colontmp_)) goto LA3;
				colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
				nimlf_(205, "D:\\nim\\lib\\pure\\os.nim");
				i = i_2;
				{
					nimln_(206);
					if (!(((NI)0) < i)) goto LA6_;
					prepareAdd((&result), 1);
appendString((&result), TM__yu6cxgKBBXbNsTkT9cyMd4g_22);
				}
LA6_: ;
				nimln_(205);
				nimln_(207);
				if (i < 0 || i >= args_p0Len_0){ raiseIndexError2(i,args_p0Len_0-1); goto BeforeRet_;
				}
				colontmpD_ = nospquoteShell(args_p0[i]);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				prepareAdd((&result), colontmpD_.len + 0);
appendString((&result), colontmpD_);
				nimlf_(122, "D:\\nim\\lib\\system\\iterators_1.nim");
				if (nimAddInt(i_2, ((NI)1), &TM__yu6cxgKBBXbNsTkT9cyMd4g_23)) { raiseOverflow(); goto BeforeRet_;
				};
				i_2 = (NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_23);
				nimlf_(25, "D:\\nim\\lib\\std\\assertions.nim");
				eqdestroy___stdZassertions_u16((&colontmpD_));
			} LA3: ;
		}
	}
	}
BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NimStringV2, slash___stdZprivateZospaths50_u90)(NimStringV2 head_p0, NimStringV2 tail_p1) {
	NimStringV2 result;
NIM_BOOL* nimErr_;
	nimfr_("/", "D:\\nim\\lib\\std\\private\\ospaths2.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimlf_(180, "D:\\nim\\lib\\std\\private\\ospaths2.nim");
	result = nosjoinPath(head_p0, tail_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, expandTilde__pureZos_u32)(NimStringV2 path_p0) {
	NimStringV2 result;
NIM_BOOL* nimErr_;
	nimfr_("expandTilde", "D:\\nim\\lib\\pure\\os.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimlf_(130, "D:\\nim\\lib\\pure\\os.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (path_p0.len == ((NI)0));
		if (T3_) goto LA4_;
		if (((NI)0) < 0 || ((NI)0) >= path_p0.len){ raiseIndexError2(((NI)0),path_p0.len-1); goto BeforeRet_;
		}
		T3_ = !(((NU8)(path_p0.p->data[((NI)0)]) == (NU8)(126)));
LA4_: ;
		if (!T3_) goto LA5_;
		nimlf_(25, "D:\\nim\\lib\\std\\assertions.nim");
		eqcopy___stdZassertions_u19((&result), path_p0);
	}
	goto LA1_;
LA5_: ;
	{
		nimlf_(132, "D:\\nim\\lib\\pure\\os.nim");
		if (!(path_p0.len == ((NI)1))) goto LA8_;
		nimln_(133);
		result = nosgetHomeDir();
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	goto LA1_;
LA8_: ;
	{
		NimStringV2 colontmpD_;
		NimStringV2 colontmpD__2;
		nimln_(134);
		if (((NI)1) < 0 || ((NI)1) >= path_p0.len){ raiseIndexError2(((NI)1),path_p0.len-1); goto BeforeRet_;
		}
		if (!(((NU8)(path_p0.p->data[((NI)1)])) == ((NU8)(92)) || ((NU8)(path_p0.p->data[((NI)1)])) == ((NU8)(47)))) goto LA11_;
		colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
		colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
		nimln_(135);
		colontmpD_ = nosgetHomeDir();
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		colontmpD__2 = substr__system_u7976(path_p0, ((NI)2));
		result = slash___stdZprivateZospaths50_u90(colontmpD_, colontmpD__2);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimlf_(25, "D:\\nim\\lib\\std\\assertions.nim");
		eqdestroy___stdZassertions_u16((&colontmpD__2));
		eqdestroy___stdZassertions_u16((&colontmpD_));
	}
	goto LA1_;
LA11_: ;
	{
		eqcopy___stdZassertions_u19((&result), path_p0);
	}
LA1_: ;
	}
BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimSetMem__systemZmemory_u7(p_p0, ((int)0), size_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
BeforeRet_: ;
}
static N_INLINE(NI16*, toWideCString__stdZwidestrs_u45)(tyObject_WideCStringObj__qZlS9aXUUYG9cVv6VNCsI5NQ x_p0) {
	NI16* result;
	nimfr_("toWideCString", "D:\\nim\\lib\\std\\widestrs.nim");
	result = (NI16*)0;
	nimlf_(54, "D:\\nim\\lib\\std\\widestrs.nim");
	result = x_p0.data;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nosgetAppFilename)(void) {
	NimStringV2 result;
	tyObject_WideCStringObj__qZlS9aXUUYG9cVv6VNCsI5NQ buf;
	NI32 bufsize;
NIM_BOOL oldNimErrFin1_;
NIM_BOOL* nimErr_;
	nimfr_("getAppFilename", "D:\\nim\\lib\\pure\\os.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimZeroMem((void*)(&buf), sizeof(tyObject_WideCStringObj__qZlS9aXUUYG9cVv6VNCsI5NQ));
	nimlf_(639, "D:\\nim\\lib\\pure\\os.nim");
	bufsize = ((NI32)260);
	nimln_(640);
	buf = newWideCString__stdZwidestrs_u271("", ((NI) (bufsize)));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		nimln_(641);
		while (1) {
			NI32 L;
			NI16* T4_;
			nimln_(642);
			T4_ = (NI16*)0;
			T4_ = toWideCString__stdZwidestrs_u45(buf);
			if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
			L = Dl_1409286341_(((NI)0), T4_, bufsize);
			nimln_(643);
			{
				if (!(L == ((NI32)0))) goto LA7_;
				nimlf_(25, "D:\\nim\\lib\\std\\assertions.nim");
				eqsink___stdZassertions_u22((&result), TM__yu6cxgKBBXbNsTkT9cyMd4g_24);
				nimlf_(645, "D:\\nim\\lib\\pure\\os.nim");
				goto LA2;
			}
			goto LA5_;
LA7_: ;
			{
				tyObject_WideCStringObj__qZlS9aXUUYG9cVv6VNCsI5NQ T12_;
				nimln_(646);
				if (!(bufsize < L)) goto LA10_;
				nimlf_(37, "D:\\nim\\lib\\std\\widestrs.nim");
				nimlf_(647, "D:\\nim\\lib\\pure\\os.nim");
				T12_ = newWideCString__stdZwidestrs_u271("", ((NI) (L)));
				if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
				nimlf_(37, "D:\\nim\\lib\\std\\widestrs.nim");
				eqsink___stdZwidestrs_u31((&buf), T12_);
				if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
				nimlf_(648, "D:\\nim\\lib\\pure\\os.nim");
				bufsize = L;
			}
			goto LA5_;
LA10_: ;
			{
				NimStringV2 T14_;
				nimlf_(25, "D:\\nim\\lib\\std\\assertions.nim");
				nimlf_(650, "D:\\nim\\lib\\pure\\os.nim");
				T14_.len = 0; T14_.p = NIM_NIL;
				T14_ = dollar___stdZwidestrs_u375(buf, ((NI) (L)), ((NI)65533));
				if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
				nimlf_(25, "D:\\nim\\lib\\std\\assertions.nim");
				eqsink___stdZassertions_u22((&result), T14_);
				nimlf_(651, "D:\\nim\\lib\\pure\\os.nim");
				goto LA2;
			}
LA5_: ;
		}
	} LA2: ;
	{
		LA1_:;
	}
	{
		oldNimErrFin1_ = *nimErr_; *nimErr_ = NIM_FALSE;
		nimlf_(28, "D:\\nim\\lib\\std\\widestrs.nim");
		eqdestroy___stdZwidestrs_u6((&buf));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		*nimErr_ = oldNimErrFin1_;
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nosgetAppDir)(void) {
	NimStringV2 result;
	tyTuple__7q7q3E6Oj24ZNVJb9aonhAg colontmpD_;
	NimStringV2 T1_;
NIM_BOOL* nimErr_;
	nimfr_("getAppDir", "D:\\nim\\lib\\pure\\os.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimZeroMem((void*)(&colontmpD_), sizeof(tyTuple__7q7q3E6Oj24ZNVJb9aonhAg));
	nimlf_(25, "D:\\nim\\lib\\std\\assertions.nim");
	nimlf_(685, "D:\\nim\\lib\\pure\\os.nim");
	T1_.len = 0; T1_.p = NIM_NIL;
	T1_ = nosgetAppFilename();
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nossplitFile(T1_, (&colontmpD_));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimlf_(25, "D:\\nim\\lib\\std\\assertions.nim");
	eqcopy___stdZassertions_u19((&result), colontmpD_.Field0);
	nimlf_(77, "D:\\nim\\lib\\std\\private\\osdirs.nim");
	eqdestroy___stdZprivateZosdirs_u84((&colontmpD_));
	}
BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL, skipFindData__stdZprivateZoscommon_u34)(tyObject_WIN32_FIND_DATA__m9cbpw3LqlaVzCliEIMPxoA* f_p0) {
	NIM_BOOL result;
	NIM_BOOL T1_;
	NIM_BOOL T3_;
	NIM_BOOL T5_;
	nimfr_("skipFindData", "D:\\nim\\lib\\std\\private\\oscommon.nim");
	result = (NIM_BOOL)0;
	nimlf_(65, "D:\\nim\\lib\\std\\private\\oscommon.nim");
	T1_ = (NIM_BOOL)0;
	T1_ = (((NI) ((*f_p0).cFileName[(((NI)0))- 0])) == ((NI)46));
	if (!(T1_)) goto LA2_;
	T3_ = (NIM_BOOL)0;
	T3_ = (((NI) ((*f_p0).cFileName[(((NI)1))- 0])) == ((NI)0));
	if (T3_) goto LA4_;
	nimln_(66);
	T5_ = (NIM_BOOL)0;
	T5_ = (((NI) ((*f_p0).cFileName[(((NI)1))- 0])) == ((NI)46));
	if (!(T5_)) goto LA6_;
	T5_ = (((NI) ((*f_p0).cFileName[(((NI)2))- 0])) == ((NI)0));
LA6_: ;
	T3_ = T5_;
LA4_: ;
	T1_ = T3_;
LA2_: ;
	result = T1_;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nosexpandFilename)(NimStringV2 filename_p0) {
	NimStringV2 result;
	tyObject_WideCStringObj__qZlS9aXUUYG9cVv6VNCsI5NQ res;
	NI32 bufsize;
	NI16* unused;
NIM_BOOL oldNimErrFin4_;
NIM_BOOL oldNimErrFin1_;
NIM_BOOL* nimErr_;
	nimfr_("expandFilename", "D:\\nim\\lib\\pure\\os.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimZeroMem((void*)(&res), sizeof(tyObject_WideCStringObj__qZlS9aXUUYG9cVv6VNCsI5NQ));
	nimlf_(424, "D:\\nim\\lib\\pure\\os.nim");
	bufsize = ((NI32)260);
	nimln_(425);
	unused = ((NI16*) NIM_NIL);
	nimln_(426);
	res = newWideCString__stdZwidestrs_u271("", ((NI) (bufsize)));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		nimln_(427);
		while (1) {
			tyObject_WideCStringObj__qZlS9aXUUYG9cVv6VNCsI5NQ colontmpD_;
			NI32 L;
			NI16* T5_;
			NI16* T6_;
			nimZeroMem((void*)(&colontmpD_), sizeof(tyObject_WideCStringObj__qZlS9aXUUYG9cVv6VNCsI5NQ));
			nimln_(428);
			colontmpD_ = newWideCString__stdZwidestrs_u303(filename_p0);
			if (NIM_UNLIKELY(*nimErr_)) goto LA4_;
			T5_ = (NI16*)0;
			T5_ = toWideCString__stdZwidestrs_u45(colontmpD_);
			if (NIM_UNLIKELY(*nimErr_)) goto LA4_;
			T6_ = (NI16*)0;
			T6_ = toWideCString__stdZwidestrs_u45(res);
			if (NIM_UNLIKELY(*nimErr_)) goto LA4_;
			L = Dl_1409286403_(T5_, bufsize, T6_, &unused);
			nimln_(429);
			{
				NI32 T11_;
				if (!(L == ((NI32)0))) goto LA9_;
				nimln_(430);
				T11_ = (NI32)0;
				T11_ = osLastError__stdZoserrors_u105();
				if (NIM_UNLIKELY(*nimErr_)) goto LA4_;
				raiseOSError__stdZoserrors_u102(T11_, filename_p0);
				if (NIM_UNLIKELY(*nimErr_)) goto LA4_;
			}
			goto LA7_;
LA9_: ;
			{
				tyObject_WideCStringObj__qZlS9aXUUYG9cVv6VNCsI5NQ T15_;
				nimln_(431);
				if (!(bufsize < L)) goto LA13_;
				nimlf_(37, "D:\\nim\\lib\\std\\widestrs.nim");
				nimlf_(432, "D:\\nim\\lib\\pure\\os.nim");
				T15_ = newWideCString__stdZwidestrs_u271("", ((NI) (L)));
				if (NIM_UNLIKELY(*nimErr_)) goto LA4_;
				nimlf_(37, "D:\\nim\\lib\\std\\widestrs.nim");
				eqsink___stdZwidestrs_u31((&res), T15_);
				if (NIM_UNLIKELY(*nimErr_)) goto LA4_;
				nimlf_(433, "D:\\nim\\lib\\pure\\os.nim");
				bufsize = L;
			}
			goto LA7_;
LA13_: ;
			{
				NimStringV2 T17_;
				nimlf_(25, "D:\\nim\\lib\\std\\assertions.nim");
				nimlf_(435, "D:\\nim\\lib\\pure\\os.nim");
				T17_.len = 0; T17_.p = NIM_NIL;
				T17_ = dollar___stdZwidestrs_u375(res, ((NI) (L)), ((NI)65533));
				if (NIM_UNLIKELY(*nimErr_)) goto LA4_;
				nimlf_(25, "D:\\nim\\lib\\std\\assertions.nim");
				eqsink___stdZassertions_u22((&result), T17_);
				nimlf_(28, "D:\\nim\\lib\\std\\widestrs.nim");
				eqdestroy___stdZwidestrs_u6((&colontmpD_));
				if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
				nimlf_(436, "D:\\nim\\lib\\pure\\os.nim");
				goto LA2;
			}
LA7_: ;
			{
				LA4_:;
			}
			{
				oldNimErrFin4_ = *nimErr_; *nimErr_ = NIM_FALSE;
				nimlf_(28, "D:\\nim\\lib\\std\\widestrs.nim");
				eqdestroy___stdZwidestrs_u6((&colontmpD_));
				if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
				*nimErr_ = oldNimErrFin4_;
			}
			if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		}
	} LA2: ;
	{
		NimStringV2 x;
		tyObject_WIN32_FIND_DATA__m9cbpw3LqlaVzCliEIMPxoA fX60gensym10_;
		NI resX60gensym10_;
		x.len = 0; x.p = NIM_NIL;
		nimZeroMem((void*)(&fX60gensym10_), sizeof(tyObject_WIN32_FIND_DATA__m9cbpw3LqlaVzCliEIMPxoA));
		resX60gensym10_ = (NI)0;
		nimlf_(65, "D:\\nim\\lib\\std\\private\\osdirs.nim");
		resX60gensym10_ = findFirstFile__stdZprivateZoscommon_u25(result, (&fX60gensym10_));
		if (NIM_UNLIKELY(*nimErr_)) goto LA21_;
		nimln_(66);
		{
			NI dotPosX60gensym10_;
			if (!!((resX60gensym10_ == ((NI)-1)))) goto LA24_;
			nimln_(68);
			dotPosX60gensym10_ = searchExtPos__stdZprivateZospaths50_u291(result);
			if (NIM_UNLIKELY(*nimErr_)) goto LA26_;
			{
				nimln_(69);
				while (1) {
					nimln_(70);
					{
						NIM_BOOL T31_;
						NIM_BOOL T32_;
						NimStringV2 ffX60gensym10_;
						NI idxX60gensym10_;
						NI TM__yu6cxgKBBXbNsTkT9cyMd4g_25;
						NI TM__yu6cxgKBBXbNsTkT9cyMd4g_26;
						T31_ = (NIM_BOOL)0;
						T32_ = (NIM_BOOL)0;
						T32_ = skipFindData__stdZprivateZoscommon_u34((&fX60gensym10_));
						if (NIM_UNLIKELY(*nimErr_)) goto LA26_;
						T31_ = !(T32_);
						if (!(T31_)) goto LA33_;
						nimln_(134);
						nimln_(46);
						nimln_(44);
						T31_ = !(!(((NI32)(fX60gensym10_.dwFileAttributes & ((NI32)16)) == ((NI32)0))));
LA33_: ;
						if (!T31_) goto LA34_;
						ffX60gensym10_.len = 0; ffX60gensym10_.p = NIM_NIL;
						nimln_(73);
						ffX60gensym10_ = dollar___stdZwidestrs_u372(((NI16*) ((&fX60gensym10_.cFileName[(((NI)0))- 0]))));
						if (NIM_UNLIKELY(*nimErr_)) goto LA26_;
						nimln_(74);
						if (nimSubInt(ffX60gensym10_.len, result.len, &TM__yu6cxgKBBXbNsTkT9cyMd4g_25)) { raiseOverflow(); goto LA26_;
						};
						if (nimAddInt((NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_25), dotPosX60gensym10_, &TM__yu6cxgKBBXbNsTkT9cyMd4g_26)) { raiseOverflow(); goto LA26_;
						};
						idxX60gensym10_ = (NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_26);
						nimln_(75);
						{
							NIM_BOOL T38_;
							NIM_BOOL T39_;
							NIM_BOOL T40_;
							NIM_BOOL T43_;
							NIM_BOOL T46_;
							NIM_BOOL T47_;
							NI TM__yu6cxgKBBXbNsTkT9cyMd4g_27;
							NI TM__yu6cxgKBBXbNsTkT9cyMd4g_28;
							tyTuple__7q7q3E6Oj24ZNVJb9aonhAg colontmpD__2;
							NimStringV2 colontmpD__3;
							NimStringV2 blitTmp;
							NimStringV2 T52_;
							T38_ = (NIM_BOOL)0;
							T39_ = (NIM_BOOL)0;
							T40_ = (NIM_BOOL)0;
							T40_ = (dotPosX60gensym10_ < ((NI)0));
							if (T40_) goto LA41_;
							T40_ = (ffX60gensym10_.len <= idxX60gensym10_);
LA41_: ;
							T39_ = T40_;
							if (T39_) goto LA42_;
							T43_ = (NIM_BOOL)0;
							T43_ = (((NI)0) <= idxX60gensym10_);
							if (!(T43_)) goto LA44_;
							if (idxX60gensym10_ < 0 || idxX60gensym10_ >= ffX60gensym10_.len){ raiseIndexError2(idxX60gensym10_,ffX60gensym10_.len-1); goto LA26_;
							}
							T43_ = ((NU8)(ffX60gensym10_.p->data[idxX60gensym10_]) == (NU8)(46));
LA44_: ;
							T39_ = T43_;
LA42_: ;
							T38_ = T39_;
							if (T38_) goto LA45_;
							nimln_(76);
							T46_ = (NIM_BOOL)0;
							T47_ = (NIM_BOOL)0;
							T47_ = (((NI)0) <= dotPosX60gensym10_);
							if (!(T47_)) goto LA48_;
							if (nimAddInt(dotPosX60gensym10_, ((NI)1), &TM__yu6cxgKBBXbNsTkT9cyMd4g_27)) { raiseOverflow(); goto LA26_;
							};
							T47_ = ((NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_27) < result.len);
LA48_: ;
							T46_ = T47_;
							if (!(T46_)) goto LA49_;
							if (nimAddInt(dotPosX60gensym10_, ((NI)1), &TM__yu6cxgKBBXbNsTkT9cyMd4g_28)) { raiseOverflow(); goto LA26_;
							};
							if ((NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_28) < 0 || (NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_28) >= result.len){ raiseIndexError2((NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_28),result.len-1); goto LA26_;
							}
							T46_ = ((NU8)(result.p->data[(NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_28)]) == (NU8)(42));
LA49_: ;
							T38_ = T46_;
LA45_: ;
							if (!T38_) goto LA50_;
							nimZeroMem((void*)(&colontmpD__2), sizeof(tyTuple__7q7q3E6Oj24ZNVJb9aonhAg));
							colontmpD__3.len = 0; colontmpD__3.p = NIM_NIL;
							nimlf_(25, "D:\\nim\\lib\\std\\assertions.nim");
							nimlf_(439, "D:\\nim\\lib\\pure\\os.nim");
							nimlf_(77, "D:\\nim\\lib\\std\\private\\osdirs.nim");
							nimln_(134);
							blitTmp = result;
							nimlf_(25, "D:\\nim\\lib\\std\\assertions.nim");
							eqwasMoved___stdZassertions_u13((&result));
							nimlf_(77, "D:\\nim\\lib\\std\\private\\osdirs.nim");
							nossplitFile(blitTmp, (&colontmpD__2));
							if (NIM_UNLIKELY(*nimErr_)) goto LA26_;
							colontmpD__3 = nosextractFilename(ffX60gensym10_);
							if (NIM_UNLIKELY(*nimErr_)) goto LA26_;
							nimlf_(439, "D:\\nim\\lib\\pure\\os.nim");
							T52_.len = 0; T52_.p = NIM_NIL;
							T52_ = slash___stdZprivateZospaths50_u90(colontmpD__2.Field0, colontmpD__3);
							if (NIM_UNLIKELY(*nimErr_)) goto LA26_;
							nimlf_(25, "D:\\nim\\lib\\std\\assertions.nim");
							eqsink___stdZassertions_u22((&x), T52_);
							eqsink___stdZassertions_u22((&result), x);
							eqwasMoved___stdZassertions_u13((&x));
							eqdestroy___stdZassertions_u16((&colontmpD__3));
							nimlf_(77, "D:\\nim\\lib\\std\\private\\osdirs.nim");
							eqdestroy___stdZprivateZosdirs_u84((&colontmpD__2));
						}
LA50_: ;
						nimlf_(25, "D:\\nim\\lib\\std\\assertions.nim");
						eqdestroy___stdZassertions_u16((&ffX60gensym10_));
					}
LA34_: ;
					nimlf_(78, "D:\\nim\\lib\\std\\private\\osdirs.nim");
					{
						NI32 T55_;
						NI32 errCodeX60gensym10_;
						T55_ = (NI32)0;
						T55_ = Dl_1409286398_(resX60gensym10_, (&fX60gensym10_));
						if (!(T55_ == ((NI32)0))) goto LA56_;
						nimln_(79);
						errCodeX60gensym10_ = Dl_1409286315_();
						nimln_(80);
						{
							if (!(errCodeX60gensym10_ == ((NI32)18))) goto LA60_;
							goto LA27;
						}
						goto LA58_;
LA60_: ;
						{
							nimln_(81);
							raiseOSError__stdZoserrors_u102(errCodeX60gensym10_, TM__yu6cxgKBBXbNsTkT9cyMd4g_29);
							if (NIM_UNLIKELY(*nimErr_)) goto LA26_;
						}
LA58_: ;
					}
LA56_: ;
				}
			} LA27: ;
			{
				LA26_:;
			}
			{
				nimln_(67);
				Dl_1409286401_(resX60gensym10_);
			}
			if (NIM_UNLIKELY(*nimErr_)) goto LA21_;
		}
LA24_: ;
		{
			LA21_:;
		}
		{
			nimlf_(25, "D:\\nim\\lib\\std\\assertions.nim");
			eqdestroy___stdZassertions_u16((&x));
		}
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	}
	nimlf_(441, "D:\\nim\\lib\\pure\\os.nim");
	{
		NIM_BOOL T69_;
		NIM_BOOL T70_;
		NIM_BOOL T72_;
		tyObject_OSError__364R2OEHwjKXXXZy8WY36g* T75_;
		NimStringV2 T76_;
		T69_ = (NIM_BOOL)0;
		T70_ = (NIM_BOOL)0;
		T70_ = nosfileExists(result);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		T69_ = !(T70_);
		if (!(T69_)) goto LA71_;
		T72_ = (NIM_BOOL)0;
		T72_ = nosdirExists(result);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		T69_ = !(T72_);
LA71_: ;
		if (!T69_) goto LA73_;
		T75_ = NIM_NIL;
		T75_ = (tyObject_OSError__364R2OEHwjKXXXZy8WY36g*) nimNewObj(sizeof(tyObject_OSError__364R2OEHwjKXXXZy8WY36g), NIM_ALIGNOF(tyObject_OSError__364R2OEHwjKXXXZy8WY36g));
		(*T75_).Sup.Sup.Sup.m_type = (&NTIv2__364R2OEHwjKXXXZy8WY36g_);
		(*T75_).Sup.Sup.name = "OSError";
		nimln_(443);
		T76_.len = 0; T76_.p = NIM_NIL;
		T76_ = rawNewString(result.len + 22);
appendString((&T76_), TM__yu6cxgKBBXbNsTkT9cyMd4g_31);
appendString((&T76_), result);
appendString((&T76_), TM__yu6cxgKBBXbNsTkT9cyMd4g_33);
		(*T75_).Sup.Sup.message = T76_;
		(*T75_).Sup.Sup.parent = ((Exception*) NIM_NIL);
		raiseExceptionEx((Exception*)T75_, "OSError", "expandFilename", "D:\\nim\\lib\\pure\\os.nim", 443);
goto LA1_;
	}
LA73_: ;
	{
		LA1_:;
	}
	{
		oldNimErrFin1_ = *nimErr_; *nimErr_ = NIM_FALSE;
		nimlf_(28, "D:\\nim\\lib\\std\\widestrs.nim");
		eqdestroy___stdZwidestrs_u6((&res));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		*nimErr_ = oldNimErrFin1_;
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NIM_CHAR, X5BX5D___system_u7429)(NimStringV2 s_p0, NI i_p1) {
	NIM_CHAR result;
	NI TM__yu6cxgKBBXbNsTkT9cyMd4g_40;
	nimfr_("[]", "D:\\nim\\lib\\system\\indices.nim");
{	result = (NIM_CHAR)0;
	nimlf_(27, "D:\\nim\\lib\\system\\indices.nim");
	if (nimSubInt(s_p0.len, i_p1, &TM__yu6cxgKBBXbNsTkT9cyMd4g_40)) { raiseOverflow(); goto BeforeRet_;
	};
	if ((NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_40) < 0 || (NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_40) >= s_p0.len){ raiseIndexError2((NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_40),s_p0.len-1); goto BeforeRet_;
	}
	result = s_p0.p->data[(NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_40)];
	}
BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, findExe__pureZos_u71)(NimStringV2 exe_p0, NIM_BOOL followSymlinks_p1, NimStringV2* extensions_p2, NI extensions_p2Len_0) {
	NimStringV2 result;
	NimStringV2 path;
NIM_BOOL* nimErr_;
	nimfr_("findExe", "D:\\nim\\lib\\pure\\os.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	path.len = 0; path.p = NIM_NIL;
	nimlf_(236, "D:\\nim\\lib\\pure\\os.nim");
	{
		if (!(exe_p0.len == ((NI)0))) goto LA4_;
		nimlf_(25, "D:\\nim\\lib\\std\\assertions.nim");
		eqdestroy___stdZassertions_u16((&path));
		goto BeforeRet_;
	}
LA4_: ;
	{
		NimStringV2* extX60gensym8_;
		NI i;
		extX60gensym8_ = (NimStringV2*)0;
		nimlf_(13, "D:\\nim\\lib\\system\\iterators.nim");
		i = ((NI)0);
		{
			nimln_(14);
			while (1) {
				NimStringV2 T9_;
				NI TM__yu6cxgKBBXbNsTkT9cyMd4g_34;
				if (!(i < extensions_p2Len_0)) goto LA8;
				nimlf_(244, "D:\\nim\\lib\\pure\\os.nim");
				if (i < 0 || i >= extensions_p2Len_0){ raiseIndexError2(i,extensions_p2Len_0-1); goto LA1_;
				}
				extX60gensym8_ = (&extensions_p2[i]);
				nimlf_(25, "D:\\nim\\lib\\std\\assertions.nim");
				nimlf_(239, "D:\\nim\\lib\\pure\\os.nim");
				T9_.len = 0; T9_.p = NIM_NIL;
				T9_ = nosaddFileExt(exe_p0, (*extX60gensym8_));
				if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
				nimlf_(25, "D:\\nim\\lib\\std\\assertions.nim");
				eqsink___stdZassertions_u22((&result), T9_);
				nimlf_(244, "D:\\nim\\lib\\pure\\os.nim");
				{
					NIM_BOOL T12_;
					nimln_(240);
					T12_ = (NIM_BOOL)0;
					T12_ = nosfileExists(result);
					if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
					if (!T12_) goto LA13_;
					nimlf_(25, "D:\\nim\\lib\\std\\assertions.nim");
					eqdestroy___stdZassertions_u16((&path));
					goto BeforeRet_;
				}
LA13_: ;
				nimlf_(16, "D:\\nim\\lib\\system\\iterators.nim");
				if (nimAddInt(i, ((NI)1), &TM__yu6cxgKBBXbNsTkT9cyMd4g_34)) { raiseOverflow(); goto LA1_;
				};
				i = (NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_34);
			} LA8: ;
		}
	}
	nimlf_(245, "D:\\nim\\lib\\pure\\os.nim");
	path = getEnv__stdZenvvars_u32(TM__yu6cxgKBBXbNsTkT9cyMd4g_36, TM__yu6cxgKBBXbNsTkT9cyMd4g_37);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		NimStringV2 candidate;
		NI lastX60gensym33_;
		NI splitsX60gensym33_;
		candidate.len = 0; candidate.p = NIM_NIL;
		nimlf_(386, "D:\\nim\\lib\\pure\\strutils.nim");
		lastX60gensym33_ = ((NI)0);
		nimln_(387);
		splitsX60gensym33_ = ((NI)-1);
		{
			nimln_(447);
			while (1) {
				NI firstX60gensym33_;
				NI TM__yu6cxgKBBXbNsTkT9cyMd4g_39;
				NimStringV2 T27_;
				NI TM__yu6cxgKBBXbNsTkT9cyMd4g_43;
				NI TM__yu6cxgKBBXbNsTkT9cyMd4g_44;
				nimln_(389);
				if (!(lastX60gensym33_ <= path.len)) goto LA18;
				nimln_(390);
				firstX60gensym33_ = lastX60gensym33_;
				{
					nimln_(391);
					while (1) {
						NIM_BOOL T21_;
						NI TM__yu6cxgKBBXbNsTkT9cyMd4g_38;
						T21_ = (NIM_BOOL)0;
						T21_ = (lastX60gensym33_ < path.len);
						if (!(T21_)) goto LA22_;
						if (lastX60gensym33_ < 0 || lastX60gensym33_ >= path.len){ raiseIndexError2(lastX60gensym33_,path.len-1); goto LA16_;
						}
						T21_ = !(((NU8)(path.p->data[lastX60gensym33_]) == (NU8)(59)));
LA22_: ;
						if (!T21_) goto LA20;
						nimln_(392);
						if (nimAddInt(lastX60gensym33_, ((NI)1), &TM__yu6cxgKBBXbNsTkT9cyMd4g_38)) { raiseOverflow(); goto LA16_;
						};
						lastX60gensym33_ = (NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_38);
					} LA20: ;
				}
				nimln_(393);
				{
					if (!(splitsX60gensym33_ == ((NI)0))) goto LA25_;
					lastX60gensym33_ = path.len;
				}
LA25_: ;
				nimlf_(25, "D:\\nim\\lib\\std\\assertions.nim");
				nimlf_(246, "D:\\nim\\lib\\pure\\os.nim");
				nimlf_(394, "D:\\nim\\lib\\pure\\strutils.nim");
				if (nimSubInt(lastX60gensym33_, ((NI)1), &TM__yu6cxgKBBXbNsTkT9cyMd4g_39)) { raiseOverflow(); goto LA16_;
				};
				nimlf_(246, "D:\\nim\\lib\\pure\\os.nim");
				T27_.len = 0; T27_.p = NIM_NIL;
				T27_ = substr__system_u7964(path, firstX60gensym33_, (NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_39));
				nimlf_(25, "D:\\nim\\lib\\std\\assertions.nim");
				eqsink___stdZassertions_u22((&candidate), T27_);
				{
					NimStringV2 x;
					NimStringV2 colontmpD_;
					NimStringV2 colontmpD__2;
					NimStringV2 T34_;
					x.len = 0; x.p = NIM_NIL;
					colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
					colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
					nimlf_(247, "D:\\nim\\lib\\pure\\os.nim");
					{
						if (!(candidate.len == ((NI)0))) goto LA32_;
						nimlf_(25, "D:\\nim\\lib\\std\\assertions.nim");
						eqdestroy___stdZassertions_u16((&colontmpD__2));
						eqdestroy___stdZassertions_u16((&colontmpD_));
						eqdestroy___stdZassertions_u16((&x));
						nimlf_(247, "D:\\nim\\lib\\pure\\os.nim");
						goto LA28;
					}
LA32_: ;
					nimln_(249);
					nimln_(250);
					T34_.len = 0; T34_.p = NIM_NIL;
					nimln_(249);
					{
						NIM_BOOL T37_;
						NIM_CHAR T39_;
						NI TM__yu6cxgKBBXbNsTkT9cyMd4g_41;
						T37_ = (NIM_BOOL)0;
						if (((NI)0) < 0 || ((NI)0) >= candidate.len){ raiseIndexError2(((NI)0),candidate.len-1); goto LA29_;
						}
						T37_ = ((NU8)(candidate.p->data[((NI)0)]) == (NU8)(34));
						if (!(T37_)) goto LA38_;
						T39_ = (NIM_CHAR)0;
						T39_ = X5BX5D___system_u7429(candidate, ((NI)1));
						if (NIM_UNLIKELY(*nimErr_)) goto LA29_;
						T37_ = ((NU8)(T39_) == (NU8)(34));
LA38_: ;
						if (!T37_) goto LA40_;
						nimln_(250);
						if (nimSubInt(candidate.len, ((NI)2), &TM__yu6cxgKBBXbNsTkT9cyMd4g_41)) { raiseOverflow(); goto LA29_;
						};
						colontmpD_ = substr__system_u7964(candidate, ((NI)1), (NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_41));
						T34_ = colontmpD_;
					}
					goto LA35_;
LA40_: ;
					{
						colontmpD__2 = candidate;
						nimlf_(25, "D:\\nim\\lib\\std\\assertions.nim");
						eqwasMoved___stdZassertions_u13((&candidate));
						T34_ = colontmpD__2;
					}
LA35_: ;
					nimlf_(250, "D:\\nim\\lib\\pure\\os.nim");
					x = slash___stdZprivateZospaths50_u90(T34_, exe_p0);
					if (NIM_UNLIKELY(*nimErr_)) goto LA29_;
					{
						NimStringV2* ext;
						NI i_2;
						ext = (NimStringV2*)0;
						nimlf_(13, "D:\\nim\\lib\\system\\iterators.nim");
						i_2 = ((NI)0);
						{
							nimln_(14);
							while (1) {
								NimStringV2 x_2;
								NI TM__yu6cxgKBBXbNsTkT9cyMd4g_42;
								if (!(i_2 < extensions_p2Len_0)) goto LA45;
								x_2.len = 0; x_2.p = NIM_NIL;
								nimlf_(254, "D:\\nim\\lib\\pure\\os.nim");
								if (i_2 < 0 || i_2 >= extensions_p2Len_0){ raiseIndexError2(i_2,extensions_p2Len_0-1); goto LA46_;
								}
								ext = (&extensions_p2[i_2]);
								nimln_(255);
								x_2 = nosaddFileExt(x, (*ext));
								if (NIM_UNLIKELY(*nimErr_)) goto LA46_;
								nimln_(254);
								{
									NIM_BOOL T49_;
									nimln_(256);
									T49_ = (NIM_BOOL)0;
									T49_ = nosfileExists(x_2);
									if (NIM_UNLIKELY(*nimErr_)) goto LA46_;
									if (!T49_) goto LA50_;
									nimln_(274);
									nimlf_(25, "D:\\nim\\lib\\std\\assertions.nim");
									eqsink___stdZassertions_u22((&result), x_2);
									eqwasMoved___stdZassertions_u13((&x_2));
									eqdestroy___stdZassertions_u16((&x_2));
									eqdestroy___stdZassertions_u16((&colontmpD__2));
									eqdestroy___stdZassertions_u16((&colontmpD_));
									eqdestroy___stdZassertions_u16((&x));
									eqdestroy___stdZassertions_u16((&candidate));
									eqdestroy___stdZassertions_u16((&path));
									goto BeforeRet_;
								}
LA50_: ;
								nimlf_(16, "D:\\nim\\lib\\system\\iterators.nim");
								if (nimAddInt(i_2, ((NI)1), &TM__yu6cxgKBBXbNsTkT9cyMd4g_42)) { raiseOverflow(); goto LA46_;
								};
								i_2 = (NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_42);
								{
									LA46_:;
								}
								{
									nimlf_(25, "D:\\nim\\lib\\std\\assertions.nim");
									eqdestroy___stdZassertions_u16((&x_2));
								}
								if (NIM_UNLIKELY(*nimErr_)) goto LA29_;
							} LA45: ;
						}
					}
					{
						LA29_:;
					}
					{
						eqdestroy___stdZassertions_u16((&colontmpD__2));
						eqdestroy___stdZassertions_u16((&colontmpD_));
						eqdestroy___stdZassertions_u16((&x));
					}
					if (NIM_UNLIKELY(*nimErr_)) goto LA16_;
				} LA28: ;
				nimlf_(395, "D:\\nim\\lib\\pure\\strutils.nim");
				{
					if (!(splitsX60gensym33_ == ((NI)0))) goto LA58_;
					goto LA17;
				}
LA58_: ;
				nimln_(396);
				if (nimSubInt(splitsX60gensym33_, ((NI)1), &TM__yu6cxgKBBXbNsTkT9cyMd4g_43)) { raiseOverflow(); goto LA16_;
				};
				splitsX60gensym33_ = (NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_43);
				nimln_(397);
				if (nimAddInt(lastX60gensym33_, ((NI)1), &TM__yu6cxgKBBXbNsTkT9cyMd4g_44)) { raiseOverflow(); goto LA16_;
				};
				lastX60gensym33_ = (NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_44);
			} LA18: ;
		} LA17: ;
		{
			LA16_:;
		}
		{
			nimlf_(25, "D:\\nim\\lib\\std\\assertions.nim");
			eqdestroy___stdZassertions_u16((&candidate));
		}
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	}
	nimlf_(275, "D:\\nim\\lib\\pure\\os.nim");
	result = TM__yu6cxgKBBXbNsTkT9cyMd4g_45;
	{
		LA1_:;
	}
	{
		nimlf_(25, "D:\\nim\\lib\\std\\assertions.nim");
		eqdestroy___stdZassertions_u16((&path));
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(int, exitStatusLikeShell__pureZos_u183)(int status_p0) {
	int result;
	nimfr_("exitStatusLikeShell", "D:\\nim\\lib\\pure\\os.nim");
	result = (int)0;
	nimlf_(389, "D:\\nim\\lib\\pure\\os.nim");
	nimln_(390);
	result = status_p0;
	popFrame();
	return result;
}
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0) {
	NCSTRING result;
	result = (NCSTRING)0;
	{
		if (!(s_p0.len == ((NI)0))) goto LA3_;
		result = "";
	}
	goto LA1_;
LA3_: ;
	{
		result = ((NCSTRING) ((*s_p0.p).data));
	}
LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, nosexecShellCmd)(NimStringV2 command_p0) {
	NI result;
	int T1_;
	int T2_;
NIM_BOOL* nimErr_;
	nimfr_("execShellCmd", "D:\\nim\\lib\\pure\\os.nim");
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	nimlf_(416, "D:\\nim\\lib\\pure\\os.nim");
	T1_ = (int)0;
	T1_ = system(nimToCStringConv(command_p0));
	T2_ = (int)0;
	T2_ = exitStatusLikeShell__pureZos_u183(T1_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result = ((NI) (T2_));
	}
BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_Time__f8Ov9bPTwk6nAIjCM1lESAw, nosgetLastModificationTime)(NimStringV2 file_p0) {
	tyObject_Time__f8Ov9bPTwk6nAIjCM1lESAw result;
	tyObject_WIN32_FIND_DATA__m9cbpw3LqlaVzCliEIMPxoA f;
	NI h;
	NI64 T6_;
NIM_BOOL* nimErr_;
	nimfr_("getLastModificationTime", "D:\\nim\\lib\\pure\\os.nim");
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&result), sizeof(tyObject_Time__f8Ov9bPTwk6nAIjCM1lESAw));
	nimZeroMem((void*)(&f), sizeof(tyObject_WIN32_FIND_DATA__m9cbpw3LqlaVzCliEIMPxoA));
	nimlf_(294, "D:\\nim\\lib\\pure\\os.nim");
	h = findFirstFile__stdZprivateZoscommon_u25(file_p0, (&f));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(295);
	{
		NI32 T5_;
		if (!(h == ((NI)-1))) goto LA3_;
		T5_ = (NI32)0;
		T5_ = osLastError__stdZoserrors_u105();
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		raiseOSError__stdZoserrors_u102(T5_, file_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA3_: ;
	nimln_(296);
	T6_ = (NI64)0;
	T6_ = rdFileTime__windowsZwinlean_u284(f.ftLastWriteTime);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result = fromWinTime__pureZtimes_u1131(T6_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(297);
	Dl_1409286401_(h);
	}
BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nosfileNewer)(NimStringV2 a_p0, NimStringV2 b_p1) {
	NIM_BOOL result;
	tyObject_Time__f8Ov9bPTwk6nAIjCM1lESAw T1_;
	tyObject_Time__f8Ov9bPTwk6nAIjCM1lESAw T2_;
NIM_BOOL* nimErr_;
	nimfr_("fileNewer", "D:\\nim\\lib\\pure\\os.nim");
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	nimlf_(354, "D:\\nim\\lib\\pure\\os.nim");
	T1_ = nosgetLastModificationTime(b_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T2_ = nosgetLastModificationTime(a_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result = ntLtTime(T1_, T2_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
BeforeRet_: ;
	popFrame();
	return result;
}
