/* Generated by Nim Compiler v1.9.3 */
#define NIM_INTBITS 32

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #define nimfrs_(proc, file, slots, length) \
    struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename;NI len;VarSlot s[slots];} FR_; \
    FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #define nimln_(n) \
    FR_.line = n;

  #define nimlf_(n, file) \
    FR_.line = n; FR_.filename = file;

typedef struct tySequence__RlbT8oLuVw9ay3ljjVb9c8lw tySequence__RlbT8oLuVw9ay3ljjVb9c8lw;
typedef struct tySequence__RlbT8oLuVw9ay3ljjVb9c8lw_Content tySequence__RlbT8oLuVw9ay3ljjVb9c8lw_Content;
typedef struct tySequence__1WrxDEO4S4oG9cJb0EDwItQ tySequence__1WrxDEO4S4oG9cJb0EDwItQ;
typedef struct tySequence__1WrxDEO4S4oG9cJb0EDwItQ_Content tySequence__1WrxDEO4S4oG9cJb0EDwItQ_Content;
typedef struct tyObject_ConfigRefcolonObjectType___bmtyrreM9bjbWfPTnr9btEbw tyObject_ConfigRefcolonObjectType___bmtyrreM9bjbWfPTnr9btEbw;
typedef struct tyObject_AliveContext__tphvFQ1TBCtddorfkjJxgA tyObject_AliveContext__tphvFQ1TBCtddorfkjJxgA;
typedef struct tySequence__Ce9b1KFbvUi5pelXDWCUccg tySequence__Ce9b1KFbvUi5pelXDWCUccg;
typedef struct tySequence__Ce9b1KFbvUi5pelXDWCUccg_Content tySequence__Ce9b1KFbvUi5pelXDWCUccg_Content;
typedef struct tyObject_PackedDecoder__YPhZig7ahPz3H2faubl5zA tyObject_PackedDecoder__YPhZig7ahPz3H2faubl5zA;
typedef struct tyObject_IdentCachecolonObjectType___LYhYfW7zHVa6k72gTbQGLw tyObject_IdentCachecolonObjectType___LYhYfW7zHVa6k72gTbQGLw;
typedef struct tyObject_Table__BRITh5ALH19awzG9aPprSxdw tyObject_Table__BRITh5ALH19awzG9aPprSxdw;
typedef struct tySequence__UuiPn6QjIiUTdSVwX2PZ6w tySequence__UuiPn6QjIiUTdSVwX2PZ6w;
typedef struct tySequence__UuiPn6QjIiUTdSVwX2PZ6w_Content tySequence__UuiPn6QjIiUTdSVwX2PZ6w_Content;
typedef struct tyTuple__Ipyq9bHX9c9bJZHIF5McOHjZw tyTuple__Ipyq9bHX9c9bJZHIF5McOHjZw;
typedef struct tyObject_Target__hsKrm4QXgGbK1Pq5KPccJQ tyObject_Target__hsKrm4QXgGbK1Pq5KPccJQ;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_StringTableObj__eQlzBfCID7uSzbD7mP9cuYw tyObject_StringTableObj__eQlzBfCID7uSzbD7mP9cuYw;
typedef struct tyObject_MsgConfig__8adZvkrggpoMFXAYi0CeGg tyObject_MsgConfig__8adZvkrggpoMFXAYi0CeGg;
typedef struct tyObject_TLineInfo__jkXFepOSR2bJfG4x3LVnQA tyObject_TLineInfo__jkXFepOSR2bJfG4x3LVnQA;
typedef struct tySequence__iivkFheiaN1lMy9aP9cChhQg tySequence__iivkFheiaN1lMy9aP9cChhQg;
typedef struct tySequence__iivkFheiaN1lMy9aP9cChhQg_Content tySequence__iivkFheiaN1lMy9aP9cChhQg_Content;
typedef struct tyObject_Table__4ZNca7r7IcU0Erc4ExAxtA tyObject_Table__4ZNca7r7IcU0Erc4ExAxtA;
typedef struct tySequence__7lEisrXlQEzwtUKW5pzRCw tySequence__7lEisrXlQEzwtUKW5pzRCw;
typedef struct tySequence__7lEisrXlQEzwtUKW5pzRCw_Content tySequence__7lEisrXlQEzwtUKW5pzRCw_Content;
typedef struct tySequence__Ec8z80lhwlXDEEuzxp8sbA tySequence__Ec8z80lhwlXDEEuzxp8sbA;
typedef struct tySequence__Ec8z80lhwlXDEEuzxp8sbA_Content tySequence__Ec8z80lhwlXDEEuzxp8sbA_Content;
typedef struct tyObject_HashSet__ETH9aHzKNAaU5daP7mekjgw tyObject_HashSet__ETH9aHzKNAaU5daP7mekjgw;
typedef struct tySequence__4eRCaZmrYLLw2k30GPTiMw tySequence__4eRCaZmrYLLw2k30GPTiMw;
typedef struct tySequence__4eRCaZmrYLLw2k30GPTiMw_Content tySequence__4eRCaZmrYLLw2k30GPTiMw_Content;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ tySequence__sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content;
typedef struct tyTuple__47w2DboNEPf69aPgubZdd7Q tyTuple__47w2DboNEPf69aPgubZdd7Q;
typedef struct tySequence__0hikNa9bKRVrWuae0sr9cIBQ tySequence__0hikNa9bKRVrWuae0sr9cIBQ;
typedef struct tySequence__0hikNa9bKRVrWuae0sr9cIBQ_Content tySequence__0hikNa9bKRVrWuae0sr9cIBQ_Content;
typedef struct tyObject_SuggestcolonObjectType___Isv9bWmKRnkSbNs9bLmS29aZg tyObject_SuggestcolonObjectType___Isv9bWmKRnkSbNs9bLmS29aZg;
typedef struct tyObject_ProfileDatacolonObjectType___5DKg4geAFa0PsZ8q9bZG2gw tyObject_ProfileDatacolonObjectType___5DKg4geAFa0PsZ8q9bZG2gw;
typedef struct tyObject_LoadedModule__CA9cqLkgUseSauH9b7VTT5GQ tyObject_LoadedModule__CA9cqLkgUseSauH9b7VTT5GQ;
typedef struct tyObject_PackedModule__v5lkl0I9chmqsXTPv6efngQ tyObject_PackedModule__v5lkl0I9chmqsXTPv6efngQ;
typedef struct tySequence__PXIzfWocnrafGz5p3CP5LA tySequence__PXIzfWocnrafGz5p3CP5LA;
typedef struct tySequence__PXIzfWocnrafGz5p3CP5LA_Content tySequence__PXIzfWocnrafGz5p3CP5LA_Content;
typedef struct tySequence__9bAGqSvkAaFL9bWjsEPslrFA tySequence__9bAGqSvkAaFL9bWjsEPslrFA;
typedef struct tySequence__9bAGqSvkAaFL9bWjsEPslrFA_Content tySequence__9bAGqSvkAaFL9bWjsEPslrFA_Content;
typedef struct tyObject_PackedTree__dwpfxIasCzder2kO8Kc6gw tyObject_PackedTree__dwpfxIasCzder2kO8Kc6gw;
typedef struct tySequence__ZcvIYD9bsYgy9bFldjJq24rw tySequence__ZcvIYD9bsYgy9bFldjJq24rw;
typedef struct tySequence__ZcvIYD9bsYgy9bFldjJq24rw_Content tySequence__ZcvIYD9bsYgy9bFldjJq24rw_Content;
typedef struct tySequence__b89aLriiJnVTD186H6zNIgg tySequence__b89aLriiJnVTD186H6zNIgg;
typedef struct tySequence__b89aLriiJnVTD186H6zNIgg_Content tySequence__b89aLriiJnVTD186H6zNIgg_Content;
typedef struct tySequence__3bxPwmc6PQgatJnuqUab4Q tySequence__3bxPwmc6PQgatJnuqUab4Q;
typedef struct tySequence__3bxPwmc6PQgatJnuqUab4Q_Content tySequence__3bxPwmc6PQgatJnuqUab4Q_Content;
typedef struct tySequence__48JTohSgTy339bRxHzUD8KA tySequence__48JTohSgTy339bRxHzUD8KA;
typedef struct tySequence__48JTohSgTy339bRxHzUD8KA_Content tySequence__48JTohSgTy339bRxHzUD8KA_Content;
typedef struct tySequence__sNXT7hZ7a8mB2x0sCU79a5w tySequence__sNXT7hZ7a8mB2x0sCU79a5w;
typedef struct tySequence__sNXT7hZ7a8mB2x0sCU79a5w_Content tySequence__sNXT7hZ7a8mB2x0sCU79a5w_Content;
typedef struct tySequence__j329br9bVA4goc39astPqfVxg tySequence__j329br9bVA4goc39astPqfVxg;
typedef struct tySequence__j329br9bVA4goc39astPqfVxg_Content tySequence__j329br9bVA4goc39astPqfVxg_Content;
typedef struct tySequence__3VrtD5xYcemlE5HK9aGwRPA tySequence__3VrtD5xYcemlE5HK9aGwRPA;
typedef struct tySequence__3VrtD5xYcemlE5HK9aGwRPA_Content tySequence__3VrtD5xYcemlE5HK9aGwRPA_Content;
typedef struct tySequence__sFzQ357hG51GtD9a6kfBT4A tySequence__sFzQ357hG51GtD9a6kfBT4A;
typedef struct tySequence__sFzQ357hG51GtD9a6kfBT4A_Content tySequence__sFzQ357hG51GtD9a6kfBT4A_Content;
typedef struct tySequence__QEITZWSuoXSvrTqFX9bjCGQ tySequence__QEITZWSuoXSvrTqFX9bjCGQ;
typedef struct tySequence__QEITZWSuoXSvrTqFX9bjCGQ_Content tySequence__QEITZWSuoXSvrTqFX9bjCGQ_Content;
typedef struct tySequence__Fk09bForaVq9c9b73dUDbI5Lw tySequence__Fk09bForaVq9c9b73dUDbI5Lw;
typedef struct tySequence__Fk09bForaVq9c9b73dUDbI5Lw_Content tySequence__Fk09bForaVq9c9b73dUDbI5Lw_Content;
typedef struct tyObject_BiTable__9aSseT9cM7Cq2kjAo9b9bjL0Fw tyObject_BiTable__9aSseT9cM7Cq2kjAo9b9bjL0Fw;
typedef struct tyObject_BiTable__qSIpmz5s819clC5IoOdEdPg tyObject_BiTable__qSIpmz5s819clC5IoOdEdPg;
typedef struct tySequence__IHUFRsFxZNv7YydiUO2esQ tySequence__IHUFRsFxZNv7YydiUO2esQ;
typedef struct tySequence__IHUFRsFxZNv7YydiUO2esQ_Content tySequence__IHUFRsFxZNv7YydiUO2esQ_Content;
typedef struct tyObject_PackedConfig__5Y12GnP3qMrx6uJEFRw3vQ tyObject_PackedConfig__5Y12GnP3qMrx6uJEFRw3vQ;
typedef struct tySequence__r9bzIJHCMzMaVrRBafZGiIA tySequence__r9bzIJHCMzMaVrRBafZGiIA;
typedef struct tySequence__r9bzIJHCMzMaVrRBafZGiIA_Content tySequence__r9bzIJHCMzMaVrRBafZGiIA_Content;
typedef struct tySequence__FxQD8iZ8Ixxg89bDGa61Sog tySequence__FxQD8iZ8Ixxg89bDGa61Sog;
typedef struct tySequence__FxQD8iZ8Ixxg89bDGa61Sog_Content tySequence__FxQD8iZ8Ixxg89bDGa61Sog_Content;
typedef struct tyObject_TSym__ZFLa1ljJflbjEpzKLkcDrw tyObject_TSym__ZFLa1ljJflbjEpzKLkcDrw;
typedef struct tyObject_Table__gbzO9cj0mtwZvydXGwvqGQg tyObject_Table__gbzO9cj0mtwZvydXGwvqGQg;
typedef struct tySequence__mp78ETZQBigS2r7n6bRnFg tySequence__mp78ETZQBigS2r7n6bRnFg;
typedef struct tySequence__mp78ETZQBigS2r7n6bRnFg_Content tySequence__mp78ETZQBigS2r7n6bRnFg_Content;
typedef struct tyObject_PackedNode__uUr9cVpPmPiXsXndseZXYHA tyObject_PackedNode__uUr9cVpPmPiXsXndseZXYHA;
typedef struct tyObject_PackedItemId__MGI6REyYkqYnT6SkM9bUi6Q tyObject_PackedItemId__MGI6REyYkqYnT6SkM9bUi6Q;
typedef struct tyObject_PackedLineInfo__G6xe00CTEr5daalQP9cOqig tyObject_PackedLineInfo__G6xe00CTEr5daalQP9cOqig;
typedef struct tyObject_PackedSet__hQybqrKgNDdlKXBvUVBhjw tyObject_PackedSet__hQybqrKgNDdlKXBvUVBhjw;
typedef struct tyObject_TrunkcolonObjectType___g8m5mxi6DLU1y8iqfA9bvZA tyObject_TrunkcolonObjectType___g8m5mxi6DLU1y8iqfA9bvZA;
typedef struct tySequence__cEwjM1aM2GQ0C6xRXTWhKA tySequence__cEwjM1aM2GQ0C6xRXTWhKA;
typedef struct tySequence__cEwjM1aM2GQ0C6xRXTWhKA_Content tySequence__cEwjM1aM2GQ0C6xRXTWhKA_Content;
typedef struct tyObject_PackedSym__wUguehdFzIlsbxpDQN0X4Q tyObject_PackedSym__wUguehdFzIlsbxpDQN0X4Q;
typedef struct tyObject_PackedLib__ZK9bHTMzKBC9bMZ5Sh6LadSg tyObject_PackedLib__ZK9bHTMzKBC9bMZ5Sh6LadSg;
typedef struct tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ;
typedef struct tyObject_ItemId__abVBMQpfEj0emlzyjx5rDg tyObject_ItemId__abVBMQpfEj0emlzyjx5rDg;
typedef struct tyObject_PackedType__KH6PxjEYGTJ9bUaqMMux9bxA tyObject_PackedType__KH6PxjEYGTJ9bUaqMMux9bxA;
typedef struct tySequence__WfKGJBagqh8D9bcGEywDAPQ tySequence__WfKGJBagqh8D9bcGEywDAPQ;
typedef struct tySequence__WfKGJBagqh8D9bcGEywDAPQ_Content tySequence__WfKGJBagqh8D9bcGEywDAPQ_Content;
typedef struct tyTuple__Ll5iolPASSzOEheeSNjmiw tyTuple__Ll5iolPASSzOEheeSNjmiw;
typedef struct tyObject_RefHeader__b9cZ5ThQEAqSv7VLAQu0wEw tyObject_RefHeader__b9cZ5ThQEAqSv7VLAQu0wEw;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tyTuple__9a3DhYVfcy14Fx42tD0lSEQ tyTuple__9a3DhYVfcy14Fx42tD0lSEQ;
typedef struct tyTuple__9byTBcumoD0uDfVmY4l4ExA tyTuple__9byTBcumoD0uDfVmY4l4ExA;
typedef struct tyTuple__xYhUhS7X82rKTqbT9bRfCnw tyTuple__xYhUhS7X82rKTqbT9bRfCnw;
typedef struct tyObject_TFileInfo__4QKBDx9cP0L2u152C4kcxXQ tyObject_TFileInfo__4QKBDx9cP0L2u152C4kcxXQ;
typedef struct tyTuple__QeWl6B6ffS4pU6WWrtcrDw tyTuple__QeWl6B6ffS4pU6WWrtcrDw;
typedef struct tyObject_Cfile__RJduG25jRMB9cnzw5y9a0SqA tyObject_Cfile__RJduG25jRMB9cnzw5y9a0SqA;
typedef struct tyTuple__0q9cmhneJEKnQERTpXXdz6Q tyTuple__0q9cmhneJEKnQERTpXXdz6Q;
typedef struct tyTuple__Izx9aRSX9a0diDXD84jOS9aMQ tyTuple__Izx9aRSX9a0diDXD84jOS9aMQ;
typedef struct tyTuple__vMchRL6KKSbNAnRM36DRXQ tyTuple__vMchRL6KKSbNAnRM36DRXQ;
typedef struct tyTuple__tvm4RD1JFf31Nx1wMfhQ9aA tyTuple__tvm4RD1JFf31Nx1wMfhQ9aA;
typedef struct tyObject_PackedInstantiation__TCYUwdKZ9buYE9bWw1QPOdGA tyObject_PackedInstantiation__TCYUwdKZ9buYE9bWw1QPOdGA;
typedef struct tyTuple__X6eozmG1j4CTbsn9bdr7abw tyTuple__X6eozmG1j4CTbsn9bdr7abw;
typedef struct tyTuple__JKjZxQ42GrTYFOtUz8XAGQ tyTuple__JKjZxQ42GrTYFOtUz8XAGQ;
typedef struct tyObject_TType__pP3zLOJKNCx6pERZKTaOFQ tyObject_TType__pP3zLOJKNCx6pERZKTaOFQ;
typedef struct tyTuple__JJXawatFisVOY79bLGYWJ0w tyTuple__JJXawatFisVOY79bLGYWJ0w;
typedef struct tyObject_TIdent__9bEjFg0XR5NuJrs6PYmIpkg tyObject_TIdent__9bEjFg0XR5NuJrs6PYmIpkg;
struct tySequence__RlbT8oLuVw9ay3ljjVb9c8lw {
  NI len; tySequence__RlbT8oLuVw9ay3ljjVb9c8lw_Content* p;
};
struct tySequence__1WrxDEO4S4oG9cJb0EDwItQ {
  NI len; tySequence__1WrxDEO4S4oG9cJb0EDwItQ_Content* p;
};
struct tySequence__Ce9b1KFbvUi5pelXDWCUccg {
  NI len; tySequence__Ce9b1KFbvUi5pelXDWCUccg_Content* p;
};
struct tyObject_PackedDecoder__YPhZig7ahPz3H2faubl5zA {
	NI lastModule;
	NU32 lastLit;
	NI32 lastFile;
	tyObject_ConfigRefcolonObjectType___bmtyrreM9bjbWfPTnr9btEbw* config;
	tyObject_IdentCachecolonObjectType___LYhYfW7zHVa6k72gTbQGLw* cache;
};
typedef NU32 tySet_tyEnum_TOption__CLLiALVaa7s1J9a3MO8USnA;
struct tySequence__UuiPn6QjIiUTdSVwX2PZ6w {
  NI len; tySequence__UuiPn6QjIiUTdSVwX2PZ6w_Content* p;
};
struct tyObject_Table__BRITh5ALH19awzG9aPprSxdw {
	tySequence__UuiPn6QjIiUTdSVwX2PZ6w data;
	NI counter;
};
struct tyObject_AliveContext__tphvFQ1TBCtddorfkjJxgA {
	tySequence__Ce9b1KFbvUi5pelXDWCUccg stack;
	tyObject_PackedDecoder__YPhZig7ahPz3H2faubl5zA decoder;
	NI thisModule;
	tySequence__RlbT8oLuVw9ay3ljjVb9c8lw alive;
	tySet_tyEnum_TOption__CLLiALVaa7s1J9a3MO8USnA options;
	tyObject_Table__BRITh5ALH19awzG9aPprSxdw compilerProcs;
};
struct tyTuple__Ipyq9bHX9c9bJZHIF5McOHjZw {
NI Field0;
tySet_tyEnum_TOption__CLLiALVaa7s1J9a3MO8USnA Field1;
NI Field2;
};
typedef NU8 tyEnum_TBackend__aWOiLuqu2mHiPrkukrmCtw;
typedef NU8 tyEnum_TSystemCPU__j3jEs0kSUxKqSeQaP9bfTfQ;
typedef NU8 tyEnum_TSystemOS__uMRwLSr9clqwYxQCSPBCldQ;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tyObject_Target__hsKrm4QXgGbK1Pq5KPccJQ {
	tyEnum_TSystemCPU__j3jEs0kSUxKqSeQaP9bfTfQ targetCPU;
	tyEnum_TSystemCPU__j3jEs0kSUxKqSeQaP9bfTfQ hostCPU;
	tyEnum_TSystemOS__uMRwLSr9clqwYxQCSPBCldQ targetOS;
	tyEnum_TSystemOS__uMRwLSr9clqwYxQCSPBCldQ hostOS;
	NI intSize;
	NI floatSize;
	NI ptrSize;
	NimStringV2 tnl;
};
typedef NU64 tySet_tyEnum_TGlobalOption__NzfAzt4HjiitM28h8LDW2Q;
struct tyObject_TLineInfo__jkXFepOSR2bJfG4x3LVnQA {
	NU16 line;
	NI16 col;
	NI32 fileIndex;
};
typedef NU8 tySet_tyEnum_TErrorOutput__b3NrdhN5GjGoUSneoFERvg;
struct tySequence__iivkFheiaN1lMy9aP9cChhQg {
  NI len; tySequence__iivkFheiaN1lMy9aP9cChhQg_Content* p;
};
struct tySequence__7lEisrXlQEzwtUKW5pzRCw {
  NI len; tySequence__7lEisrXlQEzwtUKW5pzRCw_Content* p;
};
struct tyObject_Table__4ZNca7r7IcU0Erc4ExAxtA {
	tySequence__7lEisrXlQEzwtUKW5pzRCw data;
	NI counter;
};
struct tySequence__Ec8z80lhwlXDEEuzxp8sbA {
  NI len; tySequence__Ec8z80lhwlXDEEuzxp8sbA_Content* p;
};
struct tyObject_MsgConfig__8adZvkrggpoMFXAYi0CeGg {
	tyObject_TLineInfo__jkXFepOSR2bJfG4x3LVnQA trackPos;
	NIM_BOOL trackPosAttached;
	tySet_tyEnum_TErrorOutput__b3NrdhN5GjGoUSneoFERvg errorOutputs;
	tySequence__iivkFheiaN1lMy9aP9cChhQg msgContext;
	tyObject_TLineInfo__jkXFepOSR2bJfG4x3LVnQA lastError;
	tyObject_Table__4ZNca7r7IcU0Erc4ExAxtA filenameToIndexTbl;
	tySequence__Ec8z80lhwlXDEEuzxp8sbA fileInfos;
	NI32 systemFileIdx;
};
typedef NU8 tyEnum_FilenameOption__QBykq5MJiZ6Q2zXn3OgALQ;
typedef NU8 tyEnum_Command__F9a4jE0eLQRsgBf9bPqODqRQ;
typedef NU8 tyEnum_TGCMode__hJMK13HuLpuWZTKCwRFU3Q;
typedef NU8 tyEnum_ExceptionSystem__EOrKVFs1wsQc0nEJYZHRwg;
typedef NU8 tyEnum_SymbolFilesOption__VCCXrb49a3Si9agqIt3cf14w;
struct tySequence__4eRCaZmrYLLw2k30GPTiMw {
  NI len; tySequence__4eRCaZmrYLLw2k30GPTiMw_Content* p;
};
struct tyObject_HashSet__ETH9aHzKNAaU5daP7mekjgw {
	tySequence__4eRCaZmrYLLw2k30GPTiMw data;
	NI counter;
};
typedef NU32 tySet_tyEnum_Feature__M3s7Uywm9c5BlzNIKwZFu3g;
typedef NU8 tySet_tyEnum_LegacyFeature__8EYX9bPgkyVe7BWtCVWXrwQ;
typedef NU8 tyEnum_IdeCmd__9abJolTVrNRUBtm1FQIhxJA;
typedef NU8 tyEnum_TSystemCC__QMG4oDa5CZwoPP3sQejolw;
typedef NU8 tySet_tyEnum_TMsgKind__tsG2CMS5iKcIy9bVp9bugpew[13];
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ {
  NI len; tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content* p;
};
struct tyTuple__47w2DboNEPf69aPgubZdd7Q {
NI Field0;
NI Field1;
NI Field2;
};
typedef NU8 tySet_tyEnum_StdOrrKind__BTSMCWVnjIgdVCzwOcHR5A;
struct tySequence__0hikNa9bKRVrWuae0sr9cIBQ {
  NI len; tySequence__0hikNa9bKRVrWuae0sr9cIBQ_Content* p;
};
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (tyObject_SuggestcolonObjectType___Isv9bWmKRnkSbNs9bLmS29aZg* result_p0, void* ClE_0);
void* ClE_0;
} tyProc__m4lZ53Za6LbxtTzrqLsrxA;
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (NimStringV2 output_p0, void* ClE_0);
void* ClE_0;
} tyProc__k2HFjxisIgDALbEUFojxaQ;
typedef NU8 tyEnum_Severity__4FxfpqqIYHhrYtr0gjWl9cw;
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (tyObject_ConfigRefcolonObjectType___bmtyrreM9bjbWfPTnr9btEbw* config_p0, tyObject_TLineInfo__jkXFepOSR2bJfG4x3LVnQA info_p1, NimStringV2 msg_p2, tyEnum_Severity__4FxfpqqIYHhrYtr0gjWl9cw severity_p3, void* ClE_0);
void* ClE_0;
} tyProc__qBlOAeWQQBfyw9aQDNrLzdw;
struct tyObject_ConfigRefcolonObjectType___bmtyrreM9bjbWfPTnr9btEbw {
	tyEnum_TBackend__aWOiLuqu2mHiPrkukrmCtw backend;
	tyObject_Target__hsKrm4QXgGbK1Pq5KPccJQ target;
	NI linesCompiled;
	tySet_tyEnum_TOption__CLLiALVaa7s1J9a3MO8USnA options;
	tySet_tyEnum_TGlobalOption__NzfAzt4HjiitM28h8LDW2Q globalOptions;
	tyObject_StringTableObj__eQlzBfCID7uSzbD7mP9cuYw* macrosToExpand;
	tyObject_StringTableObj__eQlzBfCID7uSzbD7mP9cuYw* arcToExpand;
	tyObject_MsgConfig__8adZvkrggpoMFXAYi0CeGg m;
	tyEnum_FilenameOption__QBykq5MJiZ6Q2zXn3OgALQ filenameOption;
	NimStringV2 unitSep;
	NI evalTemplateCounter;
	NI evalMacroCounter;
	NI8 exitcode;
	tyEnum_Command__F9a4jE0eLQRsgBf9bPqODqRQ cmd;
	NimStringV2 cmdInput;
	NIM_BOOL projectIsCmd;
	NIM_BOOL implicitCmd;
	tyEnum_TGCMode__hJMK13HuLpuWZTKCwRFU3Q selectedGC;
	tyEnum_ExceptionSystem__EOrKVFs1wsQc0nEJYZHRwg exc;
	NIM_BOOL hintProcessingDots;
	NI verbosity;
	NI numberOfProcessors;
	NF lastCmdTime;
	tyEnum_SymbolFilesOption__VCCXrb49a3Si9agqIt3cf14w symbolFiles;
	NI spellSuggestMax;
	tyObject_HashSet__ETH9aHzKNAaU5daP7mekjgw cppDefines;
	NimStringV2 headerFile;
	tySet_tyEnum_Feature__M3s7Uywm9c5BlzNIKwZFu3g features;
	tySet_tyEnum_LegacyFeature__8EYX9bPgkyVe7BWtCVWXrwQ legacyFeatures;
	NimStringV2 arguments;
	tyEnum_IdeCmd__9abJolTVrNRUBtm1FQIhxJA ideCmd;
	NIM_BOOL oldNewlines;
	tyEnum_TSystemCC__QMG4oDa5CZwoPP3sQejolw cCompiler;
	tySet_tyEnum_TMsgKind__tsG2CMS5iKcIy9bVp9bugpew modifiedyNotes;
	tySet_tyEnum_TMsgKind__tsG2CMS5iKcIy9bVp9bugpew cmdlineNotes;
	tySet_tyEnum_TMsgKind__tsG2CMS5iKcIy9bVp9bugpew foreignPackageNotes;
	tySet_tyEnum_TMsgKind__tsG2CMS5iKcIy9bVp9bugpew notes;
	tySet_tyEnum_TMsgKind__tsG2CMS5iKcIy9bVp9bugpew warningAsErrors;
	tySet_tyEnum_TMsgKind__tsG2CMS5iKcIy9bVp9bugpew mainPackageNotes;
	NI mainPackageId;
	NI errorCounter;
	NI hintCounter;
	NI warnCounter;
	NI errorMax;
	NI maxLoopIterationsVM;
	NIM_BOOL isVmTrace;
	tyObject_StringTableObj__eQlzBfCID7uSzbD7mP9cuYw* configVars;
	tyObject_StringTableObj__eQlzBfCID7uSzbD7mP9cuYw* symbols;
	tyObject_StringTableObj__eQlzBfCID7uSzbD7mP9cuYw* packageCache;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ nimblePaths;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ searchPaths;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ lazyPaths;
	NimStringV2 outFile;
	NimStringV2 outDir;
	NimStringV2 jsonBuildFile;
	NimStringV2 prefixDir;
	NimStringV2 libpath;
	NimStringV2 nimcacheDir;
	tyTuple__47w2DboNEPf69aPgubZdd7Q nimStdlibVersion;
	tyObject_StringTableObj__eQlzBfCID7uSzbD7mP9cuYw* dllOverrides;
	tyObject_StringTableObj__eQlzBfCID7uSzbD7mP9cuYw* moduleOverrides;
	tyObject_StringTableObj__eQlzBfCID7uSzbD7mP9cuYw* cfileSpecificOptions;
	NimStringV2 projectName;
	NimStringV2 projectPath;
	NimStringV2 projectFull;
	NIM_BOOL projectIsStdin;
	tySet_tyEnum_StdOrrKind__BTSMCWVnjIgdVCzwOcHR5A lastMsgWasDot;
	NI32 projectMainIdx;
	NI32 projectMainIdx2;
	NimStringV2 command;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ commandArgs;
	NimStringV2 commandLine;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ extraCmds;
	NIM_BOOL keepComments;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ implicitImports;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ implicitIncludes;
	NimStringV2 docSeeSrcUrl;
	NimStringV2 docRoot;
	NimStringV2 docCmd;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ configFiles;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ cIncludes;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ cLibs;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ cLinkedLibs;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ externalToLink;
	NimStringV2 linkOptionsCmd;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ compileOptionsCmd;
	NimStringV2 linkOptions;
	NimStringV2 compileOptions;
	NimStringV2 cCompilerPath;
	tySequence__0hikNa9bKRVrWuae0sr9cIBQ toCompile;
	tyProc__m4lZ53Za6LbxtTzrqLsrxA suggestionResultHook;
	NI suggestVersion;
	NI suggestMaxResults;
	tyObject_TLineInfo__jkXFepOSR2bJfG4x3LVnQA lastLineInfo;
	tyProc__k2HFjxisIgDALbEUFojxaQ writelnHook;
	tyProc__qBlOAeWQQBfyw9aQDNrLzdw structuredErrorHook;
	NimStringV2 cppCustomNamespace;
	NimStringV2 nimMainPrefix;
	tyObject_ProfileDatacolonObjectType___5DKg4geAFa0PsZ8q9bZG2gw* vmProfileData;
	NIM_BOOL expandProgress;
	NI expandLevels;
	NimStringV2 expandNodeResult;
	tyObject_TLineInfo__jkXFepOSR2bJfG4x3LVnQA expandPosition;
};
typedef NU8 tyEnum_ModuleStatus__0KkdgkcO3EbJQ2rT80ED9cQ;
typedef NU64 tySet_tyEnum_TSymFlag__KpFDhwzyzhjZdX3UjhPXbQ;
struct tySequence__PXIzfWocnrafGz5p3CP5LA {
  NI len; tySequence__PXIzfWocnrafGz5p3CP5LA_Content* p;
};
struct tySequence__9bAGqSvkAaFL9bWjsEPslrFA {
  NI len; tySequence__9bAGqSvkAaFL9bWjsEPslrFA_Content* p;
};
struct tySequence__ZcvIYD9bsYgy9bFldjJq24rw {
  NI len; tySequence__ZcvIYD9bsYgy9bFldjJq24rw_Content* p;
};
struct tyObject_PackedTree__dwpfxIasCzder2kO8Kc6gw {
	tySequence__ZcvIYD9bsYgy9bFldjJq24rw nodes;
};
struct tySequence__b89aLriiJnVTD186H6zNIgg {
  NI len; tySequence__b89aLriiJnVTD186H6zNIgg_Content* p;
};
struct tySequence__3bxPwmc6PQgatJnuqUab4Q {
  NI len; tySequence__3bxPwmc6PQgatJnuqUab4Q_Content* p;
};
struct tySequence__48JTohSgTy339bRxHzUD8KA {
  NI len; tySequence__48JTohSgTy339bRxHzUD8KA_Content* p;
};
struct tySequence__sNXT7hZ7a8mB2x0sCU79a5w {
  NI len; tySequence__sNXT7hZ7a8mB2x0sCU79a5w_Content* p;
};
struct tySequence__j329br9bVA4goc39astPqfVxg {
  NI len; tySequence__j329br9bVA4goc39astPqfVxg_Content* p;
};
struct tySequence__3VrtD5xYcemlE5HK9aGwRPA {
  NI len; tySequence__3VrtD5xYcemlE5HK9aGwRPA_Content* p;
};
struct tySequence__sFzQ357hG51GtD9a6kfBT4A {
  NI len; tySequence__sFzQ357hG51GtD9a6kfBT4A_Content* p;
};
typedef NU8 tySet_tyEnum_ModuleBackendFlag__9bxLYVZcLt9c3FrUPltbhJLw;
struct tySequence__QEITZWSuoXSvrTqFX9bjCGQ {
  NI len; tySequence__QEITZWSuoXSvrTqFX9bjCGQ_Content* p;
};
struct tySequence__Fk09bForaVq9c9b73dUDbI5Lw {
  NI len; tySequence__Fk09bForaVq9c9b73dUDbI5Lw_Content* p;
};
struct tyObject_BiTable__9aSseT9cM7Cq2kjAo9b9bjL0Fw {
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ vals;
	tySequence__9bAGqSvkAaFL9bWjsEPslrFA keys;
};
struct tySequence__IHUFRsFxZNv7YydiUO2esQ {
  NI len; tySequence__IHUFRsFxZNv7YydiUO2esQ_Content* p;
};
struct tyObject_BiTable__qSIpmz5s819clC5IoOdEdPg {
	tySequence__IHUFRsFxZNv7YydiUO2esQ vals;
	tySequence__9bAGqSvkAaFL9bWjsEPslrFA keys;
};
struct tyObject_PackedConfig__5Y12GnP3qMrx6uJEFRw3vQ {
	tyEnum_TBackend__aWOiLuqu2mHiPrkukrmCtw backend;
	tyEnum_TGCMode__hJMK13HuLpuWZTKCwRFU3Q selectedGC;
	tyEnum_TSystemCC__QMG4oDa5CZwoPP3sQejolw cCompiler;
	tySet_tyEnum_TOption__CLLiALVaa7s1J9a3MO8USnA options;
	tySet_tyEnum_TGlobalOption__NzfAzt4HjiitM28h8LDW2Q globalOptions;
};
struct tyObject_PackedModule__v5lkl0I9chmqsXTPv6efngQ {
	NimStringV2 definedSymbols;
	tySet_tyEnum_TSymFlag__KpFDhwzyzhjZdX3UjhPXbQ moduleFlags;
	tySequence__PXIzfWocnrafGz5p3CP5LA includes;
	tySequence__9bAGqSvkAaFL9bWjsEPslrFA imports;
	tyObject_PackedTree__dwpfxIasCzder2kO8Kc6gw toReplay;
	tyObject_PackedTree__dwpfxIasCzder2kO8Kc6gw topLevel;
	tyObject_PackedTree__dwpfxIasCzder2kO8Kc6gw bodies;
	tySequence__b89aLriiJnVTD186H6zNIgg exports;
	tySequence__b89aLriiJnVTD186H6zNIgg hidden;
	tySequence__3bxPwmc6PQgatJnuqUab4Q reexports;
	tySequence__b89aLriiJnVTD186H6zNIgg compilerProcs;
	tySequence__48JTohSgTy339bRxHzUD8KA converters;
	tySequence__48JTohSgTy339bRxHzUD8KA methods;
	tySequence__48JTohSgTy339bRxHzUD8KA trmacros;
	tySequence__48JTohSgTy339bRxHzUD8KA pureEnums;
	tySequence__sNXT7hZ7a8mB2x0sCU79a5w typeInstCache;
	tySequence__j329br9bVA4goc39astPqfVxg procInstCache;
	tySequence__3VrtD5xYcemlE5HK9aGwRPA attachedOps;
	tySequence__sFzQ357hG51GtD9a6kfBT4A methodsPerType;
	tySequence__sNXT7hZ7a8mB2x0sCU79a5w enumToStringProcs;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ emittedTypeInfo;
	tySet_tyEnum_ModuleBackendFlag__9bxLYVZcLt9c3FrUPltbhJLw backendFlags;
	tySequence__QEITZWSuoXSvrTqFX9bjCGQ syms;
	tySequence__Fk09bForaVq9c9b73dUDbI5Lw types;
	tyObject_BiTable__9aSseT9cM7Cq2kjAo9b9bjL0Fw strings;
	tyObject_BiTable__qSIpmz5s819clC5IoOdEdPg numbers;
	tyObject_PackedConfig__5Y12GnP3qMrx6uJEFRw3vQ cfg;
};
struct tySequence__r9bzIJHCMzMaVrRBafZGiIA {
  NI len; tySequence__r9bzIJHCMzMaVrRBafZGiIA_Content* p;
};
struct tySequence__FxQD8iZ8Ixxg89bDGa61Sog {
  NI len; tySequence__FxQD8iZ8Ixxg89bDGa61Sog_Content* p;
};
struct tySequence__mp78ETZQBigS2r7n6bRnFg {
  NI len; tySequence__mp78ETZQBigS2r7n6bRnFg_Content* p;
};
struct tyObject_Table__gbzO9cj0mtwZvydXGwvqGQg {
	tySequence__mp78ETZQBigS2r7n6bRnFg data;
	NI counter;
};
struct tyObject_LoadedModule__CA9cqLkgUseSauH9b7VTT5GQ {
	tyEnum_ModuleStatus__0KkdgkcO3EbJQ2rT80ED9cQ status;
	NIM_BOOL symsInit;
	NIM_BOOL typesInit;
	NIM_BOOL loadedButAliveSetChanged;
	tyObject_PackedModule__v5lkl0I9chmqsXTPv6efngQ fromDisk;
	tySequence__r9bzIJHCMzMaVrRBafZGiIA syms;
	tySequence__FxQD8iZ8Ixxg89bDGa61Sog types;
	tyObject_TSym__ZFLa1ljJflbjEpzKLkcDrw* module;
	tyObject_Table__gbzO9cj0mtwZvydXGwvqGQg iface;
	tyObject_Table__gbzO9cj0mtwZvydXGwvqGQg ifaceHidden;
};
typedef NU8 tyEnum_TNodeKind__iTsf7OFdDPsI9bz3USrneZA;
typedef NU32 tySet_tyEnum_TNodeFlag__B189abzIdXaFZwbqX6rJUug;
struct tyObject_PackedItemId__MGI6REyYkqYnT6SkM9bUi6Q {
	NU32 module;
	NI32 item;
};
struct tyObject_PackedLineInfo__G6xe00CTEr5daalQP9cOqig {
	NU16 line;
	NI16 col;
	NU32 file;
};
struct tyObject_PackedNode__uUr9cVpPmPiXsXndseZXYHA {
	tyEnum_TNodeKind__iTsf7OFdDPsI9bz3USrneZA kind;
	tySet_tyEnum_TNodeFlag__B189abzIdXaFZwbqX6rJUug flags;
	NI32 operand;
	tyObject_PackedItemId__MGI6REyYkqYnT6SkM9bUi6Q typeId_0;
	tyObject_PackedLineInfo__G6xe00CTEr5daalQP9cOqig info;
};
struct tySequence__cEwjM1aM2GQ0C6xRXTWhKA {
  NI len; tySequence__cEwjM1aM2GQ0C6xRXTWhKA_Content* p;
};
typedef NI tyArray__emiAJ8okywrJw7ZHLzlXbQ[34];
struct tyObject_PackedSet__hQybqrKgNDdlKXBvUVBhjw {
	NI elems;
	NI counter;
	NI max;
	tyObject_TrunkcolonObjectType___g8m5mxi6DLU1y8iqfA9bvZA* head;
	tySequence__cEwjM1aM2GQ0C6xRXTWhKA data;
	tyArray__emiAJ8okywrJw7ZHLzlXbQ a;
};
typedef NU8 tyEnum_TSymKind__WEw9cZhlaQ0BBcFYZb9b9cOYg;
typedef NU16 tyEnum_TMagic__kSp6H9c8v2GSNPgE9bRnqBSw;
typedef NU16 tySet_tyEnum_TLocFlag__xD65uqIe72bODUQQ6QCppQ;
typedef NU8 tyEnum_TLibKind__dBiQJoL79bQI9arr47hhYePw;
struct tyObject_PackedLib__ZK9bHTMzKBC9bMZ5Sh6LadSg {
	tyEnum_TLibKind__dBiQJoL79bQI9arr47hhYePw kind;
	NIM_BOOL generated;
	NIM_BOOL isOverriden;
	NU32 name;
	NI32 path;
};
struct tyObject_PackedSym__wUguehdFzIlsbxpDQN0X4Q {
	tyEnum_TSymKind__WEw9cZhlaQ0BBcFYZb9b9cOYg kind;
	NU32 name;
	tyObject_PackedItemId__MGI6REyYkqYnT6SkM9bUi6Q typ;
	tySet_tyEnum_TSymFlag__KpFDhwzyzhjZdX3UjhPXbQ flags;
	tyEnum_TMagic__kSp6H9c8v2GSNPgE9bRnqBSw magic;
	tyObject_PackedLineInfo__G6xe00CTEr5daalQP9cOqig info;
	NI32 ast;
	tyObject_PackedItemId__MGI6REyYkqYnT6SkM9bUi6Q owner;
	tyObject_PackedItemId__MGI6REyYkqYnT6SkM9bUi6Q guard;
	NI bitsize;
	NI alignment;
	tySet_tyEnum_TOption__CLLiALVaa7s1J9a3MO8USnA options;
	NI position;
	NI32 offset;
	NI32 disamb;
	NU32 externalName;
	tySet_tyEnum_TLocFlag__xD65uqIe72bODUQQ6QCppQ locFlags;
	tyObject_PackedLib__ZK9bHTMzKBC9bMZ5Sh6LadSg annex;
	NI32 constraint;
};
struct tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ {
NI Field0;
NI Field1;
};
typedef NU8 tyEnum_TTypeKind__ONzdjesiM9beeNBA9aZG5Ghw;
typedef NU8 tySet_tyEnum_TTypeKind__ONzdjesiM9beeNBA9aZG5Ghw[9];
struct tyObject_ItemId__abVBMQpfEj0emlzyjx5rDg {
	NI32 module;
	NI32 item;
};
typedef NU8 tyEnum_TCallingConvention__YGBqcuVZk02VOexpHqw79aA;
typedef NU64 tySet_tyEnum_TTypeFlag__ewjLDo034tp3GwWXYLjETg;
struct tySequence__WfKGJBagqh8D9bcGEywDAPQ {
  NI len; tySequence__WfKGJBagqh8D9bcGEywDAPQ_Content* p;
};
struct tyObject_PackedType__KH6PxjEYGTJ9bUaqMMux9bxA {
	tyEnum_TTypeKind__ONzdjesiM9beeNBA9aZG5Ghw kind;
	tyEnum_TCallingConvention__YGBqcuVZk02VOexpHqw79aA callConv;
	tySet_tyEnum_TTypeFlag__ewjLDo034tp3GwWXYLjETg flags;
	tySequence__WfKGJBagqh8D9bcGEywDAPQ types;
	NI32 n;
	tyObject_PackedItemId__MGI6REyYkqYnT6SkM9bUi6Q sym;
	tyObject_PackedItemId__MGI6REyYkqYnT6SkM9bUi6Q owner;
	NI64 size;
	NI16 align;
	NI16 paddingAtEnd;
	tyObject_PackedItemId__MGI6REyYkqYnT6SkM9bUi6Q typeInst;
	NI32 nonUniqueId;
};
typedef NU8 tyEnum_TOption__CLLiALVaa7s1J9a3MO8USnA;
struct tyTuple__Ll5iolPASSzOEheeSNjmiw {
NI Field0;
NI32 Field1;
};
typedef NU8 tyEnum_TSymFlag__KpFDhwzyzhjZdX3UjhPXbQ;
struct tyObject_RefHeader__b9cZ5ThQEAqSv7VLAQu0wEw {
	NI rc;
	NI rootIdx;
};
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
};


#ifndef tySequence__RlbT8oLuVw9ay3ljjVb9c8lw_Content_PP
#define tySequence__RlbT8oLuVw9ay3ljjVb9c8lw_Content_PP
struct tySequence__RlbT8oLuVw9ay3ljjVb9c8lw_Content { NI cap; tyObject_PackedSet__hQybqrKgNDdlKXBvUVBhjw data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__1WrxDEO4S4oG9cJb0EDwItQ_Content_PP
#define tySequence__1WrxDEO4S4oG9cJb0EDwItQ_Content_PP
struct tySequence__1WrxDEO4S4oG9cJb0EDwItQ_Content { NI cap; tyObject_LoadedModule__CA9cqLkgUseSauH9b7VTT5GQ data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__Ce9b1KFbvUi5pelXDWCUccg_Content_PP
#define tySequence__Ce9b1KFbvUi5pelXDWCUccg_Content_PP
struct tySequence__Ce9b1KFbvUi5pelXDWCUccg_Content { NI cap; tyTuple__Ipyq9bHX9c9bJZHIF5McOHjZw data[SEQ_DECL_SIZE];};
#endif

      struct tyTuple__9a3DhYVfcy14Fx42tD0lSEQ {
NI Field0;
NimStringV2 Field1;
tyTuple__Ll5iolPASSzOEheeSNjmiw Field2;
};


#ifndef tySequence__UuiPn6QjIiUTdSVwX2PZ6w_Content_PP
#define tySequence__UuiPn6QjIiUTdSVwX2PZ6w_Content_PP
struct tySequence__UuiPn6QjIiUTdSVwX2PZ6w_Content { NI cap; tyTuple__9a3DhYVfcy14Fx42tD0lSEQ data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__Ce9b1KFbvUi5pelXDWCUccg_Content_PP
#define tySequence__Ce9b1KFbvUi5pelXDWCUccg_Content_PP
struct tySequence__Ce9b1KFbvUi5pelXDWCUccg_Content { NI cap; tyTuple__Ipyq9bHX9c9bJZHIF5McOHjZw data[SEQ_DECL_SIZE];};
#endif

      struct tyTuple__9byTBcumoD0uDfVmY4l4ExA {
tyObject_TLineInfo__jkXFepOSR2bJfG4x3LVnQA Field0;
NimStringV2 Field1;
};


#ifndef tySequence__iivkFheiaN1lMy9aP9cChhQg_Content_PP
#define tySequence__iivkFheiaN1lMy9aP9cChhQg_Content_PP
struct tySequence__iivkFheiaN1lMy9aP9cChhQg_Content { NI cap; tyTuple__9byTBcumoD0uDfVmY4l4ExA data[SEQ_DECL_SIZE];};
#endif

      struct tyTuple__xYhUhS7X82rKTqbT9bRfCnw {
NI Field0;
NimStringV2 Field1;
NI32 Field2;
};


#ifndef tySequence__7lEisrXlQEzwtUKW5pzRCw_Content_PP
#define tySequence__7lEisrXlQEzwtUKW5pzRCw_Content_PP
struct tySequence__7lEisrXlQEzwtUKW5pzRCw_Content { NI cap; tyTuple__xYhUhS7X82rKTqbT9bRfCnw data[SEQ_DECL_SIZE];};
#endif

      struct tyObject_TFileInfo__4QKBDx9cP0L2u152C4kcxXQ {
	NimStringV2 fullPath;
	NimStringV2 projPath;
	NimStringV2 shortName;
	NimStringV2 quotedName;
	NimStringV2 quotedFullName;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ lines;
	NimStringV2 dirtyFile;
	NimStringV2 hash;
	NIM_BOOL dirty;
};


#ifndef tySequence__Ec8z80lhwlXDEEuzxp8sbA_Content_PP
#define tySequence__Ec8z80lhwlXDEEuzxp8sbA_Content_PP
struct tySequence__Ec8z80lhwlXDEEuzxp8sbA_Content { NI cap; tyObject_TFileInfo__4QKBDx9cP0L2u152C4kcxXQ data[SEQ_DECL_SIZE];};
#endif

      struct tyTuple__QeWl6B6ffS4pU6WWrtcrDw {
NI Field0;
NimStringV2 Field1;
};


#ifndef tySequence__4eRCaZmrYLLw2k30GPTiMw_Content_PP
#define tySequence__4eRCaZmrYLLw2k30GPTiMw_Content_PP
struct tySequence__4eRCaZmrYLLw2k30GPTiMw_Content { NI cap; tyTuple__QeWl6B6ffS4pU6WWrtcrDw data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content_PP
#define tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content_PP
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content { NI cap; NimStringV2 data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content_PP
#define tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content_PP
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content { NI cap; NimStringV2 data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content_PP
#define tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content_PP
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content { NI cap; NimStringV2 data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content_PP
#define tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content_PP
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content { NI cap; NimStringV2 data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content_PP
#define tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content_PP
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content { NI cap; NimStringV2 data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content_PP
#define tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content_PP
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content { NI cap; NimStringV2 data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content_PP
#define tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content_PP
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content { NI cap; NimStringV2 data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content_PP
#define tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content_PP
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content { NI cap; NimStringV2 data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content_PP
#define tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content_PP
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content { NI cap; NimStringV2 data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content_PP
#define tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content_PP
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content { NI cap; NimStringV2 data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content_PP
#define tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content_PP
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content { NI cap; NimStringV2 data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content_PP
#define tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content_PP
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content { NI cap; NimStringV2 data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content_PP
#define tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content_PP
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content { NI cap; NimStringV2 data[SEQ_DECL_SIZE];};
#endif

      typedef NU8 tySet_tyEnum_CfileFlag__b68gbqLCFrcZUavbEz3QRQ;
struct tyObject_Cfile__RJduG25jRMB9cnzw5y9a0SqA {
	NimStringV2 nimname;
	NimStringV2 cname;
	NimStringV2 obj;
	tySet_tyEnum_CfileFlag__b68gbqLCFrcZUavbEz3QRQ flags;
	NimStringV2 customArgs;
};


#ifndef tySequence__0hikNa9bKRVrWuae0sr9cIBQ_Content_PP
#define tySequence__0hikNa9bKRVrWuae0sr9cIBQ_Content_PP
struct tySequence__0hikNa9bKRVrWuae0sr9cIBQ_Content { NI cap; tyObject_Cfile__RJduG25jRMB9cnzw5y9a0SqA data[SEQ_DECL_SIZE];};
#endif

      struct tyTuple__0q9cmhneJEKnQERTpXXdz6Q {
NU32 Field0;
NimStringV2 Field1;
};


#ifndef tySequence__PXIzfWocnrafGz5p3CP5LA_Content_PP
#define tySequence__PXIzfWocnrafGz5p3CP5LA_Content_PP
struct tySequence__PXIzfWocnrafGz5p3CP5LA_Content { NI cap; tyTuple__0q9cmhneJEKnQERTpXXdz6Q data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__9bAGqSvkAaFL9bWjsEPslrFA_Content_PP
#define tySequence__9bAGqSvkAaFL9bWjsEPslrFA_Content_PP
struct tySequence__9bAGqSvkAaFL9bWjsEPslrFA_Content { NI cap; NU32 data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__ZcvIYD9bsYgy9bFldjJq24rw_Content_PP
#define tySequence__ZcvIYD9bsYgy9bFldjJq24rw_Content_PP
struct tySequence__ZcvIYD9bsYgy9bFldjJq24rw_Content { NI cap; tyObject_PackedNode__uUr9cVpPmPiXsXndseZXYHA data[SEQ_DECL_SIZE];};
#endif

      struct tyTuple__Izx9aRSX9a0diDXD84jOS9aMQ {
NU32 Field0;
NI32 Field1;
};


#ifndef tySequence__b89aLriiJnVTD186H6zNIgg_Content_PP
#define tySequence__b89aLriiJnVTD186H6zNIgg_Content_PP
struct tySequence__b89aLriiJnVTD186H6zNIgg_Content { NI cap; tyTuple__Izx9aRSX9a0diDXD84jOS9aMQ data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__b89aLriiJnVTD186H6zNIgg_Content_PP
#define tySequence__b89aLriiJnVTD186H6zNIgg_Content_PP
struct tySequence__b89aLriiJnVTD186H6zNIgg_Content { NI cap; tyTuple__Izx9aRSX9a0diDXD84jOS9aMQ data[SEQ_DECL_SIZE];};
#endif

      struct tyTuple__vMchRL6KKSbNAnRM36DRXQ {
NU32 Field0;
tyObject_PackedItemId__MGI6REyYkqYnT6SkM9bUi6Q Field1;
};


#ifndef tySequence__3bxPwmc6PQgatJnuqUab4Q_Content_PP
#define tySequence__3bxPwmc6PQgatJnuqUab4Q_Content_PP
struct tySequence__3bxPwmc6PQgatJnuqUab4Q_Content { NI cap; tyTuple__vMchRL6KKSbNAnRM36DRXQ data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__b89aLriiJnVTD186H6zNIgg_Content_PP
#define tySequence__b89aLriiJnVTD186H6zNIgg_Content_PP
struct tySequence__b89aLriiJnVTD186H6zNIgg_Content { NI cap; tyTuple__Izx9aRSX9a0diDXD84jOS9aMQ data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__48JTohSgTy339bRxHzUD8KA_Content_PP
#define tySequence__48JTohSgTy339bRxHzUD8KA_Content_PP
struct tySequence__48JTohSgTy339bRxHzUD8KA_Content { NI cap; NI32 data[SEQ_DECL_SIZE];};
#endif

      struct tyTuple__tvm4RD1JFf31Nx1wMfhQ9aA {
tyObject_PackedItemId__MGI6REyYkqYnT6SkM9bUi6Q Field0;
tyObject_PackedItemId__MGI6REyYkqYnT6SkM9bUi6Q Field1;
};


#ifndef tySequence__sNXT7hZ7a8mB2x0sCU79a5w_Content_PP
#define tySequence__sNXT7hZ7a8mB2x0sCU79a5w_Content_PP
struct tySequence__sNXT7hZ7a8mB2x0sCU79a5w_Content { NI cap; tyTuple__tvm4RD1JFf31Nx1wMfhQ9aA data[SEQ_DECL_SIZE];};
#endif

      struct tyObject_PackedInstantiation__TCYUwdKZ9buYE9bWw1QPOdGA {
	tyObject_PackedItemId__MGI6REyYkqYnT6SkM9bUi6Q key;
	tyObject_PackedItemId__MGI6REyYkqYnT6SkM9bUi6Q sym;
	tySequence__WfKGJBagqh8D9bcGEywDAPQ concreteTypes;
};


#ifndef tySequence__j329br9bVA4goc39astPqfVxg_Content_PP
#define tySequence__j329br9bVA4goc39astPqfVxg_Content_PP
struct tySequence__j329br9bVA4goc39astPqfVxg_Content { NI cap; tyObject_PackedInstantiation__TCYUwdKZ9buYE9bWw1QPOdGA data[SEQ_DECL_SIZE];};
#endif

      typedef NU8 tyEnum_TTypeAttachedOp__CLbN35NnJ466CL9bU7JmGvQ;
struct tyTuple__X6eozmG1j4CTbsn9bdr7abw {
tyObject_PackedItemId__MGI6REyYkqYnT6SkM9bUi6Q Field0;
tyEnum_TTypeAttachedOp__CLbN35NnJ466CL9bU7JmGvQ Field1;
tyObject_PackedItemId__MGI6REyYkqYnT6SkM9bUi6Q Field2;
};


#ifndef tySequence__3VrtD5xYcemlE5HK9aGwRPA_Content_PP
#define tySequence__3VrtD5xYcemlE5HK9aGwRPA_Content_PP
struct tySequence__3VrtD5xYcemlE5HK9aGwRPA_Content { NI cap; tyTuple__X6eozmG1j4CTbsn9bdr7abw data[SEQ_DECL_SIZE];};
#endif

      struct tyTuple__JKjZxQ42GrTYFOtUz8XAGQ {
tyObject_PackedItemId__MGI6REyYkqYnT6SkM9bUi6Q Field0;
NI Field1;
tyObject_PackedItemId__MGI6REyYkqYnT6SkM9bUi6Q Field2;
};


#ifndef tySequence__sFzQ357hG51GtD9a6kfBT4A_Content_PP
#define tySequence__sFzQ357hG51GtD9a6kfBT4A_Content_PP
struct tySequence__sFzQ357hG51GtD9a6kfBT4A_Content { NI cap; tyTuple__JKjZxQ42GrTYFOtUz8XAGQ data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__sNXT7hZ7a8mB2x0sCU79a5w_Content_PP
#define tySequence__sNXT7hZ7a8mB2x0sCU79a5w_Content_PP
struct tySequence__sNXT7hZ7a8mB2x0sCU79a5w_Content { NI cap; tyTuple__tvm4RD1JFf31Nx1wMfhQ9aA data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content_PP
#define tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content_PP
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content { NI cap; NimStringV2 data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__QEITZWSuoXSvrTqFX9bjCGQ_Content_PP
#define tySequence__QEITZWSuoXSvrTqFX9bjCGQ_Content_PP
struct tySequence__QEITZWSuoXSvrTqFX9bjCGQ_Content { NI cap; tyObject_PackedSym__wUguehdFzIlsbxpDQN0X4Q data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__Fk09bForaVq9c9b73dUDbI5Lw_Content_PP
#define tySequence__Fk09bForaVq9c9b73dUDbI5Lw_Content_PP
struct tySequence__Fk09bForaVq9c9b73dUDbI5Lw_Content { NI cap; tyObject_PackedType__KH6PxjEYGTJ9bUaqMMux9bxA data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content_PP
#define tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content_PP
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content { NI cap; NimStringV2 data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__9bAGqSvkAaFL9bWjsEPslrFA_Content_PP
#define tySequence__9bAGqSvkAaFL9bWjsEPslrFA_Content_PP
struct tySequence__9bAGqSvkAaFL9bWjsEPslrFA_Content { NI cap; NU32 data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__IHUFRsFxZNv7YydiUO2esQ_Content_PP
#define tySequence__IHUFRsFxZNv7YydiUO2esQ_Content_PP
struct tySequence__IHUFRsFxZNv7YydiUO2esQ_Content { NI cap; NI64 data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__r9bzIJHCMzMaVrRBafZGiIA_Content_PP
#define tySequence__r9bzIJHCMzMaVrRBafZGiIA_Content_PP
struct tySequence__r9bzIJHCMzMaVrRBafZGiIA_Content { NI cap; tyObject_TSym__ZFLa1ljJflbjEpzKLkcDrw* data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__FxQD8iZ8Ixxg89bDGa61Sog_Content_PP
#define tySequence__FxQD8iZ8Ixxg89bDGa61Sog_Content_PP
struct tySequence__FxQD8iZ8Ixxg89bDGa61Sog_Content { NI cap; tyObject_TType__pP3zLOJKNCx6pERZKTaOFQ* data[SEQ_DECL_SIZE];};
#endif

      struct tyTuple__JJXawatFisVOY79bLGYWJ0w {
NI Field0;
tyObject_TIdent__9bEjFg0XR5NuJrs6PYmIpkg* Field1;
tySequence__WfKGJBagqh8D9bcGEywDAPQ Field2;
};


#ifndef tySequence__mp78ETZQBigS2r7n6bRnFg_Content_PP
#define tySequence__mp78ETZQBigS2r7n6bRnFg_Content_PP
struct tySequence__mp78ETZQBigS2r7n6bRnFg_Content { NI cap; tyTuple__JJXawatFisVOY79bLGYWJ0w data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__cEwjM1aM2GQ0C6xRXTWhKA_Content_PP
#define tySequence__cEwjM1aM2GQ0C6xRXTWhKA_Content_PP
struct tySequence__cEwjM1aM2GQ0C6xRXTWhKA_Content { NI cap; tyObject_TrunkcolonObjectType___g8m5mxi6DLU1y8iqfA9bvZA* data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__Ce9b1KFbvUi5pelXDWCUccg_Content_PP
#define tySequence__Ce9b1KFbvUi5pelXDWCUccg_Content_PP
struct tySequence__Ce9b1KFbvUi5pelXDWCUccg_Content { NI cap; tyTuple__Ipyq9bHX9c9bJZHIF5McOHjZw data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__WfKGJBagqh8D9bcGEywDAPQ_Content_PP
#define tySequence__WfKGJBagqh8D9bcGEywDAPQ_Content_PP
struct tySequence__WfKGJBagqh8D9bcGEywDAPQ_Content { NI cap; tyObject_PackedItemId__MGI6REyYkqYnT6SkM9bUi6Q data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__RlbT8oLuVw9ay3ljjVb9c8lw_Content_PP
#define tySequence__RlbT8oLuVw9ay3ljjVb9c8lw_Content_PP
struct tySequence__RlbT8oLuVw9ay3ljjVb9c8lw_Content { NI cap; tyObject_PackedSet__hQybqrKgNDdlKXBvUVBhjw data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__UuiPn6QjIiUTdSVwX2PZ6w_Content_PP
#define tySequence__UuiPn6QjIiUTdSVwX2PZ6w_Content_PP
struct tySequence__UuiPn6QjIiUTdSVwX2PZ6w_Content { NI cap; tyTuple__9a3DhYVfcy14Fx42tD0lSEQ data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content_PP
#define tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content_PP
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content { NI cap; NimStringV2 data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__WfKGJBagqh8D9bcGEywDAPQ_Content_PP
#define tySequence__WfKGJBagqh8D9bcGEywDAPQ_Content_PP
struct tySequence__WfKGJBagqh8D9bcGEywDAPQ_Content { NI cap; tyObject_PackedItemId__MGI6REyYkqYnT6SkM9bUi6Q data[SEQ_DECL_SIZE];};
#endif

      static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void*, newSeqPayload)(NI cap_p0, NI elemSize_p1, NI elemAlign_p2);
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___options_u3750)(tyObject_ConfigRefcolonObjectType___bmtyrreM9bjbWfPTnr9btEbw** dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___options_u3756)(tyObject_ConfigRefcolonObjectType___bmtyrreM9bjbWfPTnr9btEbw** dest_p0, tyObject_ConfigRefcolonObjectType___bmtyrreM9bjbWfPTnr9btEbw* src_p1);
N_LIB_PRIVATE N_NIMCALL(tySequence__RlbT8oLuVw9ay3ljjVb9c8lw, newSeq__icZdce_u2126)(NI len_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___icZpacked95ast_u589)(tyObject_PackedTree__dwpfxIasCzder2kO8Kc6gw* dest_p0, tyObject_PackedTree__dwpfxIasCzder2kO8Kc6gw src_p1);
static N_INLINE(NI, len__icZpacked95ast_u510)(tyObject_PackedTree__dwpfxIasCzder2kO8Kc6gw tree_p0);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4294)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(void, aliveCode__icZdce_u1986)(tyObject_AliveContext__tphvFQ1TBCtddorfkjJxgA* c_p0, tySequence__1WrxDEO4S4oG9cJb0EDwItQ g_p1, tyObject_PackedTree__dwpfxIasCzder2kO8Kc6gw tree_p2, NI n_p3);
N_LIB_PRIVATE N_NIMCALL(void, followLater__icZdce_u1685)(tyObject_AliveContext__tphvFQ1TBCtddorfkjJxgA* c_p0, tySequence__1WrxDEO4S4oG9cJb0EDwItQ g_p1, NI module_p2, NI32 item_p3);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, containsOrIncl__astalgo_u410)(tyObject_PackedSet__hQybqrKgNDdlKXBvUVBhjw* s_p0, NI key_p1);
N_LIB_PRIVATE N_NIMCALL(NI, ithSon__icZpacked95ast_u822)(tyObject_PackedTree__dwpfxIasCzder2kO8Kc6gw tree_p0, NI n_p1, NI i_p2);
N_LIB_PRIVATE N_NIMCALL(void, add__icZdce_u1700)(tySequence__Ce9b1KFbvUi5pelXDWCUccg* x_p0, tyTuple__Ipyq9bHX9c9bJZHIF5McOHjZw value_p1);
N_LIB_PRIVATE N_NIMCALL(tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ, sons2__icZpacked95ast_u764)(tyObject_PackedTree__dwpfxIasCzder2kO8Kc6gw tree_p0, NI n_p1);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__stdZassertions_u274)(NimStringV2 msg_p0);
N_LIB_PRIVATE N_NIMCALL(NI32, toFileIndexCached__icZic_u7725)(tyObject_PackedDecoder__YPhZig7ahPz3H2faubl5zA* c_p0, tySequence__1WrxDEO4S4oG9cJb0EDwItQ g_p1, NI thisModule_p2, NU32 f_p3);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, nextChild__icZpacked95ast_u536)(tyObject_PackedTree__dwpfxIasCzder2kO8Kc6gw tree_p0, NI* pos_p1);
N_LIB_PRIVATE N_NIMCALL(void, rangeCheckAnalysis__icZdce_u1966)(tyObject_AliveContext__tphvFQ1TBCtddorfkjJxgA* c_p0, tySequence__1WrxDEO4S4oG9cJb0EDwItQ g_p1, tyObject_PackedTree__dwpfxIasCzder2kO8Kc6gw tree_p2, NI n_p3);
N_LIB_PRIVATE N_NIMCALL(tyEnum_TTypeKind__ONzdjesiM9beeNBA9aZG5Ghw, loadTypeKind__icZdce_u1945)(tyObject_PackedItemId__MGI6REyYkqYnT6SkM9bUi6Q t_p0, tyObject_AliveContext__tphvFQ1TBCtddorfkjJxgA* c_p1, tySequence__1WrxDEO4S4oG9cJb0EDwItQ g_p2, tySet_tyEnum_TTypeKind__ONzdjesiM9beeNBA9aZG5Ghw toSkip_p3);
N_LIB_PRIVATE N_NIMCALL(tyObject_ItemId__abVBMQpfEj0emlzyjx5rDg, translateId__icZic_u11262)(tyObject_PackedItemId__MGI6REyYkqYnT6SkM9bUi6Q id_p0, tySequence__1WrxDEO4S4oG9cJb0EDwItQ g_p1, NI thisModule_p2, tyObject_ConfigRefcolonObjectType___bmtyrreM9bjbWfPTnr9btEbw* config_p3);
static N_INLINE(tyObject_PackedItemId__MGI6REyYkqYnT6SkM9bUi6Q, X5BX5D___icZdce_u1958)(tyObject_PackedItemId__MGI6REyYkqYnT6SkM9bUi6Q* s_p0, NI s_p0Len_0, NI i_p1);
static N_INLINE(NI, firstSon__icZpacked95ast_u851)(NI n_p0);
N_LIB_PRIVATE N_NIMCALL(void, requestCompilerProc__icZdce_u1791)(tyObject_AliveContext__tphvFQ1TBCtddorfkjJxgA* c_p0, tySequence__1WrxDEO4S4oG9cJb0EDwItQ g_p1, NimStringV2 name_p2);
N_LIB_PRIVATE N_NIMCALL(tyTuple__Ll5iolPASSzOEheeSNjmiw*, X5BX5D___icZdce_u1852)(tyObject_Table__BRITh5ALH19awzG9aPprSxdw* t_p0, NimStringV2 key_p1);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isExportedToC__icZdce_u26)(tyObject_AliveContext__tphvFQ1TBCtddorfkjJxgA* c_p0, tySequence__1WrxDEO4S4oG9cJb0EDwItQ g_p1, NI32 symId_p2);
N_LIB_PRIVATE N_NIMCALL(void, X5BX5Deq___icZdce_u154)(tyObject_Table__BRITh5ALH19awzG9aPprSxdw* t_p0, NimStringV2 key_p1, tyTuple__Ll5iolPASSzOEheeSNjmiw val_p2);
static N_INLINE(NimStringV2*, X5BX5D___icZic_u156)(tyObject_BiTable__9aSseT9cM7Cq2kjAo9b9bjL0Fw* t_p0, NU32 litId_p1);
static N_INLINE(NI, span__icZpacked95ast_u760)(tyObject_PackedTree__dwpfxIasCzder2kO8Kc6gw tree_p0, NI pos_p1);
static N_INLINE(NIM_BOOL, isAtom__icZpacked95ast_u392)(tyObject_PackedTree__dwpfxIasCzder2kO8Kc6gw tree_p0, NI pos_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___icZpacked95ast_u586)(tyObject_PackedTree__dwpfxIasCzder2kO8Kc6gw* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, followNow__icZdce_u2036)(tyObject_AliveContext__tphvFQ1TBCtddorfkjJxgA* c_p0, tySequence__1WrxDEO4S4oG9cJb0EDwItQ g_p1);
static N_INLINE(tyTuple__Ipyq9bHX9c9bJZHIF5McOHjZw, pop__icZdce_u2042)(tySequence__Ce9b1KFbvUi5pelXDWCUccg* s_p0);
N_LIB_PRIVATE N_NIMCALL(void, shrink__icZdce_u2057)(tySequence__Ce9b1KFbvUi5pelXDWCUccg* x_p0, NI newLen_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___icZdce_u2208)(tyObject_AliveContext__tphvFQ1TBCtddorfkjJxgA* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___icZdce_u2162)(tySequence__Ce9b1KFbvUi5pelXDWCUccg* dest_p0);
static N_INLINE(NIM_BOOL, nimDecRefIsLastDyn)(void* p_p0);
static N_INLINE(NI, minuspercent___system_u790)(NI x_p0, NI y_p1);
N_LIB_PRIVATE N_NIMCALL(void, unregisterCycle__system_u2848)(tyObject_RefHeader__b9cZ5ThQEAqSv7VLAQu0wEw* s_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___options_u3373)(tyObject_ConfigRefcolonObjectType___bmtyrreM9bjbWfPTnr9btEbw* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimRawDispose)(void* p_p0, NI alignment_p1);
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicStatic)(void* p_p0, TNimTypeV2* desc_p1);
N_LIB_PRIVATE N_NOINLINE(void, rememberCycle__system_u3251)(NIM_BOOL isDestroyAction_p0, tyObject_RefHeader__b9cZ5ThQEAqSv7VLAQu0wEw* s_p1, TNimTypeV2* desc_p2);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___idents_u262)(tyObject_IdentCachecolonObjectType___LYhYfW7zHVa6k72gTbQGLw* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___nilcheck_u1382)(tySequence__RlbT8oLuVw9ay3ljjVb9c8lw* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___icZdce_u609)(tySequence__UuiPn6QjIiUTdSVwX2PZ6w* dest_p0);
static const struct {
  NI cap; NIM_CHAR data[59+1];
} TM__VOZez4W9a02yKrIR7zij6nQ_2 = { 59 | NIM_STRLIT_FLAG, "D:\\nim\\compiler\\ic\\dce.nim(111, 5) `n1.kind == nkInt32Lit` " };
static const NimStringV2 TM__VOZez4W9a02yKrIR7zij6nQ_3 = {59, (NimStrPayload*)&TM__VOZez4W9a02yKrIR7zij6nQ_2};
static const struct {
  NI cap; NIM_CHAR data[59+1];
} TM__VOZez4W9a02yKrIR7zij6nQ_4 = { 59 | NIM_STRLIT_FLAG, "D:\\nim\\compiler\\ic\\dce.nim(112, 5) `n2.kind == nkInt32Lit` " };
static const NimStringV2 TM__VOZez4W9a02yKrIR7zij6nQ_5 = {59, (NimStrPayload*)&TM__VOZez4W9a02yKrIR7zij6nQ_4};
static const struct {
  NI cap; NIM_CHAR data[76+1];
} TM__VOZez4W9a02yKrIR7zij6nQ_6 = { 76 | NIM_STRLIT_FLAG, "D:\\nim\\compiler\\ic\\packed_ast.nim(207, 3) `tree.nodes[pos].kind > nkNilLit` " };
static const NimStringV2 TM__VOZez4W9a02yKrIR7zij6nQ_7 = {76, (NimStrPayload*)&TM__VOZez4W9a02yKrIR7zij6nQ_6};
static const struct {
  NI cap; NIM_CHAR data[72+1];
} TM__VOZez4W9a02yKrIR7zij6nQ_10 = { 72 | NIM_STRLIT_FLAG, "D:\\nim\\compiler\\ic\\packed_ast.nim(200, 5) `tree.nodes[pos].operand > 0` " };
static const NimStringV2 TM__VOZez4W9a02yKrIR7zij6nQ_11 = {72, (NimStrPayload*)&TM__VOZez4W9a02yKrIR7zij6nQ_10};
static NIM_CONST tySet_tyEnum_TTypeKind__ONzdjesiM9beeNBA9aZG5Ghw TM__VOZez4W9a02yKrIR7zij6nQ_15 = {
0x10, 0xa9, 0x80, 0x00, 0x00, 0xe0, 0x80, 0x00,
0x00}
;
static const struct {
  NI cap; NIM_CHAR data[21+1];
} TM__VOZez4W9a02yKrIR7zij6nQ_17 = { 21 | NIM_STRLIT_FLAG, "raiseRangeErrorNoArgs" };
static const NimStringV2 TM__VOZez4W9a02yKrIR7zij6nQ_18 = {21, (NimStrPayload*)&TM__VOZez4W9a02yKrIR7zij6nQ_17};
static NIM_CONST tySet_tyEnum_TTypeKind__ONzdjesiM9beeNBA9aZG5Ghw TM__VOZez4W9a02yKrIR7zij6nQ_19 = {
0x10, 0xa9, 0x90, 0x00, 0x00, 0x60, 0x80, 0x00,
0x00}
;
static const struct {
  NI cap; NIM_CHAR data[16+1];
} TM__VOZez4W9a02yKrIR7zij6nQ_20 = { 16 | NIM_STRLIT_FLAG, "raiseRangeErrorU" };
static const NimStringV2 TM__VOZez4W9a02yKrIR7zij6nQ_21 = {16, (NimStrPayload*)&TM__VOZez4W9a02yKrIR7zij6nQ_20};
static const struct {
  NI cap; NIM_CHAR data[16+1];
} TM__VOZez4W9a02yKrIR7zij6nQ_22 = { 16 | NIM_STRLIT_FLAG, "raiseRangeErrorF" };
static const NimStringV2 TM__VOZez4W9a02yKrIR7zij6nQ_23 = {16, (NimStrPayload*)&TM__VOZez4W9a02yKrIR7zij6nQ_22};
static const struct {
  NI cap; NIM_CHAR data[16+1];
} TM__VOZez4W9a02yKrIR7zij6nQ_24 = { 16 | NIM_STRLIT_FLAG, "raiseRangeErrorI" };
static const NimStringV2 TM__VOZez4W9a02yKrIR7zij6nQ_25 = {16, (NimStrPayload*)&TM__VOZez4W9a02yKrIR7zij6nQ_24};
static const struct {
  NI cap; NIM_CHAR data[57+1];
} TM__VOZez4W9a02yKrIR7zij6nQ_27 = { 57 | NIM_STRLIT_FLAG, "D:\\nim\\compiler\\ic\\bitabs.nim(103, 3) `idx < t.vals.len` " };
static const NimStringV2 TM__VOZez4W9a02yKrIR7zij6nQ_28 = {57, (NimStrPayload*)&TM__VOZez4W9a02yKrIR7zij6nQ_27};
static const NimStringV2 TM__VOZez4W9a02yKrIR7zij6nQ_29 = {76, (NimStrPayload*)&TM__VOZez4W9a02yKrIR7zij6nQ_6};
extern TNimTypeV2 NTIv2__LYhYfW7zHVa6k72gTbQGLw_;
extern NIM_BOOL nimInErrorMode__system_u4097;
extern TFrame* framePtr__system_u3743;
extern TFrame* framePtr__system_u3743;
extern TFrame* framePtr__system_u3743;
extern TFrame* framePtr__system_u3743;
extern TFrame* framePtr__system_u3743;
extern TFrame* framePtr__system_u3743;
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (NIM_BOOL*)0;
	result = (&nimInErrorMode__system_u4097);
	return result;
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimSetMem__systemZmemory_u7(p_p0, ((int)0), size_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
BeforeRet_: ;
}
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u3743 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u3743).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u3743;
	framePtr__system_u3743 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4294();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u3743 = (*framePtr__system_u3743).prev;
}
static N_INLINE(NI, len__icZpacked95ast_u510)(tyObject_PackedTree__dwpfxIasCzder2kO8Kc6gw tree_p0) {
	NI result;
	NI T1_;
	nimfr_("len", "D:\\nim\\compiler\\ic\\packed_ast.nim");
	result = (NI)0;
	nimlf_(193, "D:\\nim\\compiler\\ic\\packed_ast.nim");
	T1_ = tree_p0.nodes.len;
	result = T1_;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, followLater__icZdce_u1685)(tyObject_AliveContext__tphvFQ1TBCtddorfkjJxgA* c_p0, tySequence__1WrxDEO4S4oG9cJb0EDwItQ g_p1, NI module_p2, NI32 item_p3) {
NIM_BOOL* nimErr_;
	nimfr_("followLater", "D:\\nim\\compiler\\ic\\dce.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(53, "D:\\nim\\compiler\\ic\\dce.nim");
	{
		NIM_BOOL T3_;
		NI32 body;
		if (module_p2 < 0 || module_p2 >= (*c_p0).alive.len){ raiseIndexError2(module_p2,(*c_p0).alive.len-1); goto BeforeRet_;
		}
		T3_ = (NIM_BOOL)0;
		T3_ = containsOrIncl__astalgo_u410((&(*c_p0).alive.p->data[module_p2]), ((NI) (item_p3)));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!!(T3_)) goto LA4_;
		nimln_(54);
		if (module_p2 < 0 || module_p2 >= g_p1.len){ raiseIndexError2(module_p2,g_p1.len-1); goto BeforeRet_;
		}
		if (item_p3 < 0 || item_p3 >= g_p1.p->data[module_p2].fromDisk.syms.len){ raiseIndexError2(item_p3,g_p1.p->data[module_p2].fromDisk.syms.len-1); goto BeforeRet_;
		}
		body = g_p1.p->data[module_p2].fromDisk.syms.p->data[item_p3].ast;
		nimln_(55);
		{
			NI colontmpD_;
			tySet_tyEnum_TOption__CLLiALVaa7s1J9a3MO8USnA opt;
			tyTuple__Ipyq9bHX9c9bJZHIF5McOHjZw T15_;
			if (!!((body == ((NI32)-1)))) goto LA8_;
			colontmpD_ = (NI)0;
			nimln_(56);
			if (module_p2 < 0 || module_p2 >= g_p1.len){ raiseIndexError2(module_p2,g_p1.len-1); goto BeforeRet_;
			}
			if (item_p3 < 0 || item_p3 >= g_p1.p->data[module_p2].fromDisk.syms.len){ raiseIndexError2(item_p3,g_p1.p->data[module_p2].fromDisk.syms.len-1); goto BeforeRet_;
			}
			opt = g_p1.p->data[module_p2].fromDisk.syms.p->data[item_p3].options;
			nimln_(57);
			{
				NI T14_;
				if (module_p2 < 0 || module_p2 >= g_p1.len){ raiseIndexError2(module_p2,g_p1.len-1); goto BeforeRet_;
				}
				if (item_p3 < 0 || item_p3 >= g_p1.p->data[module_p2].fromDisk.syms.len){ raiseIndexError2(item_p3,g_p1.p->data[module_p2].fromDisk.syms.len-1); goto BeforeRet_;
				}
				if (!(g_p1.p->data[module_p2].fromDisk.syms.p->data[item_p3].kind == ((tyEnum_TSymKind__WEw9cZhlaQ0BBcFYZb9b9cOYg)12) || g_p1.p->data[module_p2].fromDisk.syms.p->data[item_p3].kind == ((tyEnum_TSymKind__WEw9cZhlaQ0BBcFYZb9b9cOYg)13) || g_p1.p->data[module_p2].fromDisk.syms.p->data[item_p3].kind == ((tyEnum_TSymKind__WEw9cZhlaQ0BBcFYZb9b9cOYg)14) || g_p1.p->data[module_p2].fromDisk.syms.p->data[item_p3].kind == ((tyEnum_TSymKind__WEw9cZhlaQ0BBcFYZb9b9cOYg)15) || g_p1.p->data[module_p2].fromDisk.syms.p->data[item_p3].kind == ((tyEnum_TSymKind__WEw9cZhlaQ0BBcFYZb9b9cOYg)16) || g_p1.p->data[module_p2].fromDisk.syms.p->data[item_p3].kind == ((tyEnum_TSymKind__WEw9cZhlaQ0BBcFYZb9b9cOYg)17) || g_p1.p->data[module_p2].fromDisk.syms.p->data[item_p3].kind == ((tyEnum_TSymKind__WEw9cZhlaQ0BBcFYZb9b9cOYg)18))) goto LA12_;
				nimln_(58);
				if (module_p2 < 0 || module_p2 >= g_p1.len){ raiseIndexError2(module_p2,g_p1.len-1); goto BeforeRet_;
				}
				T14_ = (NI)0;
				T14_ = ithSon__icZpacked95ast_u822(g_p1.p->data[module_p2].fromDisk.bodies, ((NI) (body)), ((NI)6));
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				body = ((NI32) (T14_));
			}
LA12_: ;
			nimln_(59);
			colontmpD_ = module_p2;
			T15_.Field0 = colontmpD_;
			T15_.Field1 = opt;
			T15_.Field2 = ((NI) (body));
			add__icZdce_u1700((&(*c_p0).stack), T15_);
		}
LA8_: ;
	}
LA4_: ;
	}
BeforeRet_: ;
	popFrame();
}
static N_INLINE(void, nextChild__icZpacked95ast_u536)(tyObject_PackedTree__dwpfxIasCzder2kO8Kc6gw tree_p0, NI* pos_p1) {
NIM_BOOL* nimErr_;
	nimfr_("nextChild", "D:\\nim\\compiler\\ic\\packed_ast.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(199, "D:\\nim\\compiler\\ic\\packed_ast.nim");
	{
		NI TM__VOZez4W9a02yKrIR7zij6nQ_12;
		if ((*pos_p1) < 0 || (*pos_p1) >= tree_p0.nodes.len){ raiseIndexError2((*pos_p1),tree_p0.nodes.len-1); goto BeforeRet_;
		}
		if (!(((tyEnum_TNodeKind__iTsf7OFdDPsI9bz3USrneZA)23) < tree_p0.nodes.p->data[(*pos_p1)].kind)) goto LA3_;
		nimln_(200);
		{
			if ((*pos_p1) < 0 || (*pos_p1) >= tree_p0.nodes.len){ raiseIndexError2((*pos_p1),tree_p0.nodes.len-1); goto BeforeRet_;
			}
			if (!!((((NI32)0) < tree_p0.nodes.p->data[(*pos_p1)].operand))) goto LA7_;
			failedAssertImpl__stdZassertions_u274(TM__VOZez4W9a02yKrIR7zij6nQ_11);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
LA7_: ;
		nimln_(201);
		if ((*pos_p1) < 0 || (*pos_p1) >= tree_p0.nodes.len){ raiseIndexError2((*pos_p1),tree_p0.nodes.len-1); goto BeforeRet_;
		}
		if (nimAddInt((*pos_p1), tree_p0.nodes.p->data[(*pos_p1)].operand, &TM__VOZez4W9a02yKrIR7zij6nQ_12)) { raiseOverflow(); goto BeforeRet_;
		};
		(*pos_p1) = (NI)(TM__VOZez4W9a02yKrIR7zij6nQ_12);
	}
	goto LA1_;
LA3_: ;
	{
		NI TM__VOZez4W9a02yKrIR7zij6nQ_13;
		nimln_(203);
		if (nimAddInt((*pos_p1), ((NI)1), &TM__VOZez4W9a02yKrIR7zij6nQ_13)) { raiseOverflow(); goto BeforeRet_;
		};
		(*pos_p1) = (NI)(TM__VOZez4W9a02yKrIR7zij6nQ_13);
	}
LA1_: ;
	}
BeforeRet_: ;
	popFrame();
}
static N_INLINE(tyObject_PackedItemId__MGI6REyYkqYnT6SkM9bUi6Q, X5BX5D___icZdce_u1958)(tyObject_PackedItemId__MGI6REyYkqYnT6SkM9bUi6Q* s_p0, NI s_p0Len_0, NI i_p1) {
	tyObject_PackedItemId__MGI6REyYkqYnT6SkM9bUi6Q result;
	NI TM__VOZez4W9a02yKrIR7zij6nQ_14;
	nimfr_("[]", "D:\\nim\\lib\\system\\indices.nim");
{	nimZeroMem((void*)(&result), sizeof(tyObject_PackedItemId__MGI6REyYkqYnT6SkM9bUi6Q));
	nimlf_(22, "D:\\nim\\lib\\system\\indices.nim");
	nimln_(23);
	if (nimSubInt(s_p0Len_0, i_p1, &TM__VOZez4W9a02yKrIR7zij6nQ_14)) { raiseOverflow(); goto BeforeRet_;
	};
	if ((NI)(TM__VOZez4W9a02yKrIR7zij6nQ_14) < 0 || (NI)(TM__VOZez4W9a02yKrIR7zij6nQ_14) >= s_p0Len_0){ raiseIndexError2((NI)(TM__VOZez4W9a02yKrIR7zij6nQ_14),s_p0Len_0-1); goto BeforeRet_;
	}
	result = s_p0[(NI)(TM__VOZez4W9a02yKrIR7zij6nQ_14)];
	}
BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyEnum_TTypeKind__ONzdjesiM9beeNBA9aZG5Ghw, loadTypeKind__icZdce_u1945)(tyObject_PackedItemId__MGI6REyYkqYnT6SkM9bUi6Q t_p0, tyObject_AliveContext__tphvFQ1TBCtddorfkjJxgA* c_p1, tySequence__1WrxDEO4S4oG9cJb0EDwItQ g_p2, tySet_tyEnum_TTypeKind__ONzdjesiM9beeNBA9aZG5Ghw toSkip_p3) {
	tyEnum_TTypeKind__ONzdjesiM9beeNBA9aZG5Ghw result;
	tyObject_ItemId__abVBMQpfEj0emlzyjx5rDg t2;
NIM_BOOL* nimErr_;
	nimfr_("loadTypeKind", "D:\\nim\\compiler\\ic\\dce.nim");
{nimErr_ = nimErrorFlag();
	result = (tyEnum_TTypeKind__ONzdjesiM9beeNBA9aZG5Ghw)0;
	nimlf_(75, "D:\\nim\\compiler\\ic\\dce.nim");
	t2 = translateId__icZic_u11262(t_p0, g_p2, (*c_p1).thisModule, (*c_p1).decoder.config);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(76);
	if (t2.module < 0 || t2.module >= g_p2.len){ raiseIndexError2(t2.module,g_p2.len-1); goto BeforeRet_;
	}
	if (t2.item < 0 || t2.item >= g_p2.p->data[t2.module].fromDisk.types.len){ raiseIndexError2(t2.item,g_p2.p->data[t2.module].fromDisk.types.len-1); goto BeforeRet_;
	}
	result = g_p2.p->data[t2.module].fromDisk.types.p->data[t2.item].kind;
	{
		nimln_(77);
		while (1) {
			tyObject_PackedItemId__MGI6REyYkqYnT6SkM9bUi6Q T3_;
			if (!((toSkip_p3[(NU)((result))>>3] &(1U<<((NU)((result))&7U)))!=0)) goto LA2;
			nimln_(78);
			if (t2.module < 0 || t2.module >= g_p2.len){ raiseIndexError2(t2.module,g_p2.len-1); goto BeforeRet_;
			}
			if (t2.item < 0 || t2.item >= g_p2.p->data[t2.module].fromDisk.types.len){ raiseIndexError2(t2.item,g_p2.p->data[t2.module].fromDisk.types.len-1); goto BeforeRet_;
			}
			T3_ = X5BX5D___icZdce_u1958(((g_p2.p->data[t2.module].fromDisk.types.p->data[t2.item].types).p) ? (g_p2.p->data[t2.module].fromDisk.types.p->data[t2.item].types.p->data) : NIM_NIL, g_p2.p->data[t2.module].fromDisk.types.p->data[t2.item].types.len, ((NI)1));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			t2 = translateId__icZic_u11262(T3_, g_p2, ((NI) (t2.module)), (*c_p1).decoder.config);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			nimln_(79);
			if (t2.module < 0 || t2.module >= g_p2.len){ raiseIndexError2(t2.module,g_p2.len-1); goto BeforeRet_;
			}
			if (t2.item < 0 || t2.item >= g_p2.p->data[t2.module].fromDisk.types.len){ raiseIndexError2(t2.item,g_p2.p->data[t2.module].fromDisk.types.len-1); goto BeforeRet_;
			}
			result = g_p2.p->data[t2.module].fromDisk.types.p->data[t2.item].kind;
		} LA2: ;
	}
	}
BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NI, firstSon__icZpacked95ast_u851)(NI n_p0) {
	NI result;
	NI TM__VOZez4W9a02yKrIR7zij6nQ_16;
	nimfr_("firstSon", "D:\\nim\\compiler\\ic\\packed_ast.nim");
{	result = (NI)0;
	nimlf_(325, "D:\\nim\\compiler\\ic\\packed_ast.nim");
	if (nimAddInt(n_p0, ((NI)1), &TM__VOZez4W9a02yKrIR7zij6nQ_16)) { raiseOverflow(); goto BeforeRet_;
	};
	result = (NI)(TM__VOZez4W9a02yKrIR7zij6nQ_16);
	}
BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, requestCompilerProc__icZdce_u1791)(tyObject_AliveContext__tphvFQ1TBCtddorfkjJxgA* c_p0, tySequence__1WrxDEO4S4oG9cJb0EDwItQ g_p1, NimStringV2 name_p2) {
	tyTuple__Ll5iolPASSzOEheeSNjmiw tmpTuple;
	tyTuple__Ll5iolPASSzOEheeSNjmiw* T1_;
	NI module;
	NI32 item;
NIM_BOOL* nimErr_;
	nimfr_("requestCompilerProc", "D:\\nim\\compiler\\ic\\dce.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(69, "D:\\nim\\compiler\\ic\\dce.nim");
	T1_ = (tyTuple__Ll5iolPASSzOEheeSNjmiw*)0;
	T1_ = X5BX5D___icZdce_u1852((&(*c_p0).compilerProcs), name_p2);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	tmpTuple = (*T1_);
	module = tmpTuple.Field0;
	item = tmpTuple.Field1;
	nimln_(70);
	followLater__icZdce_u1685(c_p0, g_p1, module, item);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, rangeCheckAnalysis__icZdce_u1966)(tyObject_AliveContext__tphvFQ1TBCtddorfkjJxgA* c_p0, tySequence__1WrxDEO4S4oG9cJb0EDwItQ g_p1, tyObject_PackedTree__dwpfxIasCzder2kO8Kc6gw tree_p2, NI n_p3) {
	tyEnum_TTypeKind__ONzdjesiM9beeNBA9aZG5Ghw dest;
NIM_BOOL* nimErr_;
	nimfr_("rangeCheckAnalysis", "D:\\nim\\compiler\\ic\\dce.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(85, "D:\\nim\\compiler\\ic\\dce.nim");
	if (n_p3 < 0 || n_p3 >= tree_p2.nodes.len){ raiseIndexError2(n_p3,tree_p2.nodes.len-1); goto BeforeRet_;
	}
	dest = loadTypeKind__icZdce_u1945(tree_p2.nodes.p->data[n_p3].typeId_0, (&(*c_p0)), g_p1, TM__VOZez4W9a02yKrIR7zij6nQ_15);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(86);
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = !((((*c_p0).options &((NU32)1<<((NU)((((tyEnum_TOption__CLLiALVaa7s1J9a3MO8USnA)3)))&31U)))!=0));
		if (T3_) goto LA4_;
		T3_ = (dest >= ((tyEnum_TTypeKind__ONzdjesiM9beeNBA9aZG5Ghw)40) && dest <= ((tyEnum_TTypeKind__ONzdjesiM9beeNBA9aZG5Ghw)44));
LA4_: ;
		if (!T3_) goto LA5_;
	}
	goto LA1_;
LA5_: ;
	{
		tyEnum_TTypeKind__ONzdjesiM9beeNBA9aZG5Ghw n0t;
		NI T8_;
		tySet_tyEnum_TTypeKind__ONzdjesiM9beeNBA9aZG5Ghw T9_;
		nimln_(89);
		T8_ = (NI)0;
		T8_ = firstSon__icZpacked95ast_u851(n_p3);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (T8_ < 0 || T8_ >= tree_p2.nodes.len){ raiseIndexError2(T8_,tree_p2.nodes.len-1); goto BeforeRet_;
		}
		nimZeroMem(T9_, sizeof(tySet_tyEnum_TTypeKind__ONzdjesiM9beeNBA9aZG5Ghw));
		n0t = loadTypeKind__icZdce_u1945(tree_p2.nodes.p->data[T8_].typeId_0, (&(*c_p0)), g_p1, T9_);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimln_(90);
		{
			if (!(n0t == ((tyEnum_TTypeKind__ONzdjesiM9beeNBA9aZG5Ghw)40) || n0t == ((tyEnum_TTypeKind__ONzdjesiM9beeNBA9aZG5Ghw)44))) goto LA12_;
			nimln_(91);
			requestCompilerProc__icZdce_u1791(c_p0, g_p1, TM__VOZez4W9a02yKrIR7zij6nQ_18);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
		goto LA10_;
LA12_: ;
		{
			NimStringV2 raiser;
			NimStringV2 T15_;
			tyEnum_TTypeKind__ONzdjesiM9beeNBA9aZG5Ghw T16_;
			raiser.len = 0; raiser.p = NIM_NIL;
			nimln_(94);
			T15_.len = 0; T15_.p = NIM_NIL;
			if (n_p3 < 0 || n_p3 >= tree_p2.nodes.len){ raiseIndexError2(n_p3,tree_p2.nodes.len-1); goto BeforeRet_;
			}
			T16_ = (tyEnum_TTypeKind__ONzdjesiM9beeNBA9aZG5Ghw)0;
			T16_ = loadTypeKind__icZdce_u1945(tree_p2.nodes.p->data[n_p3].typeId_0, (&(*c_p0)), g_p1, TM__VOZez4W9a02yKrIR7zij6nQ_19);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			switch (T16_) {
			case ((tyEnum_TTypeKind__ONzdjesiM9beeNBA9aZG5Ghw)40) ... ((tyEnum_TTypeKind__ONzdjesiM9beeNBA9aZG5Ghw)44):
			case ((tyEnum_TTypeKind__ONzdjesiM9beeNBA9aZG5Ghw)2):
			{
				nimln_(93);
				nimln_(95);
				raiser = TM__VOZez4W9a02yKrIR7zij6nQ_21;
			}
			break;
			case ((tyEnum_TTypeKind__ONzdjesiM9beeNBA9aZG5Ghw)36) ... ((tyEnum_TTypeKind__ONzdjesiM9beeNBA9aZG5Ghw)39):
			{
				nimln_(93);
				nimln_(96);
				raiser = TM__VOZez4W9a02yKrIR7zij6nQ_23;
			}
			break;
			default:
			{
				nimln_(93);
				nimln_(97);
				raiser = TM__VOZez4W9a02yKrIR7zij6nQ_25;
			}
			break;
			}
			nimln_(98);
			requestCompilerProc__icZdce_u1791(c_p0, g_p1, raiser);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
LA10_: ;
	}
LA1_: ;
	}
BeforeRet_: ;
	popFrame();
}
static N_INLINE(NimStringV2*, X5BX5D___icZic_u156)(tyObject_BiTable__9aSseT9cM7Cq2kjAo9b9bjL0Fw* t_p0, NU32 litId_p1) {
	NimStringV2* result;
	NI idx;
	NI TM__VOZez4W9a02yKrIR7zij6nQ_26;
NIM_BOOL* nimErr_;
	nimfr_("[]", "D:\\nim\\compiler\\ic\\bitabs.nim");
{nimErr_ = nimErrorFlag();
	result = (NimStringV2*)0;
	nimlf_(102, "D:\\nim\\compiler\\ic\\bitabs.nim");
	if ((NI64)(litId_p1) < ((NI)(-2147483647 -1)) || (NI64)(litId_p1) > ((NI)2147483647)){ raiseRangeErrorI(litId_p1, ((NI)(-2147483647 -1)), ((NI)2147483647)); goto BeforeRet_;
	}
	if (nimSubInt(((NI) (litId_p1)), ((NI)256), &TM__VOZez4W9a02yKrIR7zij6nQ_26)) { raiseOverflow(); goto BeforeRet_;
	};
	idx = (NI)(TM__VOZez4W9a02yKrIR7zij6nQ_26);
	nimln_(103);
	{
		NI T3_;
		T3_ = (*t_p0).vals.len;
		if (!!((idx < T3_))) goto LA4_;
		failedAssertImpl__stdZassertions_u274(TM__VOZez4W9a02yKrIR7zij6nQ_28);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA4_: ;
	nimln_(104);
	if (idx < 0 || idx >= (*t_p0).vals.len){ raiseIndexError2(idx,(*t_p0).vals.len-1); goto BeforeRet_;
	}
	result = (&(*t_p0).vals.p->data[idx]);
	}
BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isExportedToC__icZdce_u26)(tyObject_AliveContext__tphvFQ1TBCtddorfkjJxgA* c_p0, tySequence__1WrxDEO4S4oG9cJb0EDwItQ g_p1, NI32 symId_p2) {
	NIM_BOOL result;
	tyObject_PackedSym__wUguehdFzIlsbxpDQN0X4Q* symPtr;
	tySet_tyEnum_TSymFlag__KpFDhwzyzhjZdX3UjhPXbQ flags;
NIM_BOOL* nimErr_;
	nimfr_("isExportedToC", "D:\\nim\\compiler\\ic\\dce.nim");
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	nimlf_(34, "D:\\nim\\compiler\\ic\\dce.nim");
	if ((*c_p0).thisModule < 0 || (*c_p0).thisModule >= g_p1.len){ raiseIndexError2((*c_p0).thisModule,g_p1.len-1); goto BeforeRet_;
	}
	if (symId_p2 < 0 || symId_p2 >= g_p1.p->data[(*c_p0).thisModule].fromDisk.syms.len){ raiseIndexError2(symId_p2,g_p1.p->data[(*c_p0).thisModule].fromDisk.syms.len-1); goto BeforeRet_;
	}
	symPtr = (&g_p1.p->data[(*c_p0).thisModule].fromDisk.syms.p->data[symId_p2]);
	nimln_(35);
	flags = (*symPtr).flags;
	nimln_(39);
	{
		if (!!(((flags &((NU64)1<<((NU)((((tyEnum_TSymFlag__KpFDhwzyzhjZdX3UjhPXbQ)28)))&63U)))!=0))) goto LA3_;
		nimln_(40);
		{
			NIM_BOOL T7_;
			tySet_tyEnum_TSymFlag__KpFDhwzyzhjZdX3UjhPXbQ T8_;
			T7_ = (NIM_BOOL)0;
			T8_ = 0;
			T7_ = !(((262272 & flags) == T8_));
			if (T7_) goto LA9_;
			nimln_(41);
			T7_ = ((*symPtr).kind == ((tyEnum_TSymKind__WEw9cZhlaQ0BBcFYZb9b9cOYg)14));
LA9_: ;
			if (!T7_) goto LA10_;
			nimln_(42);
			result = NIM_TRUE;
		}
LA10_: ;
		nimln_(45);
		{
			NI colontmpD_;
			NI32 colontmpD__2;
			NimStringV2* T16_;
			tyTuple__Ll5iolPASSzOEheeSNjmiw T17_;
			if (!((flags &((NU64)1<<((NU)((((tyEnum_TSymFlag__KpFDhwzyzhjZdX3UjhPXbQ)18)))&63U)))!=0)) goto LA14_;
			colontmpD_ = (NI)0;
			colontmpD__2 = (NI32)0;
			nimln_(46);
			if ((*c_p0).thisModule < 0 || (*c_p0).thisModule >= g_p1.len){ raiseIndexError2((*c_p0).thisModule,g_p1.len-1); goto BeforeRet_;
			}
			T16_ = (NimStringV2*)0;
			T16_ = X5BX5D___icZic_u156((&g_p1.p->data[(*c_p0).thisModule].fromDisk.strings), (*symPtr).name);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			colontmpD_ = (*c_p0).thisModule;
			T17_.Field0 = colontmpD_;
			colontmpD__2 = symId_p2;
			T17_.Field1 = colontmpD__2;
			X5BX5Deq___icZdce_u154((&(*c_p0).compilerProcs), (*T16_), T17_);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
LA14_: ;
	}
LA3_: ;
	}
BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, aliveCode__icZdce_u1986)(tyObject_AliveContext__tphvFQ1TBCtddorfkjJxgA* c_p0, tySequence__1WrxDEO4S4oG9cJb0EDwItQ g_p1, tyObject_PackedTree__dwpfxIasCzder2kO8Kc6gw tree_p2, NI n_p3) {
NIM_BOOL* nimErr_;
	nimfr_("aliveCode", "D:\\nim\\compiler\\ic\\dce.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(103, "D:\\nim\\compiler\\ic\\dce.nim");
	if (n_p3 < 0 || n_p3 >= tree_p2.nodes.len){ raiseIndexError2(n_p3,tree_p2.nodes.len-1); goto BeforeRet_;
	}
	switch (tree_p2.nodes.p->data[n_p3].kind) {
	case ((tyEnum_TNodeKind__iTsf7OFdDPsI9bz3USrneZA)0) ... ((tyEnum_TNodeKind__iTsf7OFdDPsI9bz3USrneZA)2):
	case ((tyEnum_TNodeKind__iTsf7OFdDPsI9bz3USrneZA)4) ... ((tyEnum_TNodeKind__iTsf7OFdDPsI9bz3USrneZA)23):
	{
	}
	break;
	case ((tyEnum_TNodeKind__iTsf7OFdDPsI9bz3USrneZA)3):
	{
		nimln_(108);
		if (n_p3 < 0 || n_p3 >= tree_p2.nodes.len){ raiseIndexError2(n_p3,tree_p2.nodes.len-1); goto BeforeRet_;
		}
		followLater__icZdce_u1685(c_p0, g_p1, (*c_p0).thisModule, tree_p2.nodes.p->data[n_p3].operand);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	break;
	case ((tyEnum_TNodeKind__iTsf7OFdDPsI9bz3USrneZA)162):
	{
		tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ tmpTuple;
		NI n1;
		NI n2;
		NU32 m;
		NI32 item;
		NI otherModule;
		NI32 T12_;
		nimln_(110);
		tmpTuple = sons2__icZpacked95ast_u764(tree_p2, n_p3);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		n1 = tmpTuple.Field0;
		n2 = tmpTuple.Field1;
		nimln_(111);
		{
			if (n1 < 0 || n1 >= tree_p2.nodes.len){ raiseIndexError2(n1,tree_p2.nodes.len-1); goto BeforeRet_;
			}
			if (!!((tree_p2.nodes.p->data[n1].kind == ((tyEnum_TNodeKind__iTsf7OFdDPsI9bz3USrneZA)9)))) goto LA6_;
			failedAssertImpl__stdZassertions_u274(TM__VOZez4W9a02yKrIR7zij6nQ_3);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
LA6_: ;
		nimln_(112);
		{
			if (n2 < 0 || n2 >= tree_p2.nodes.len){ raiseIndexError2(n2,tree_p2.nodes.len-1); goto BeforeRet_;
			}
			if (!!((tree_p2.nodes.p->data[n2].kind == ((tyEnum_TNodeKind__iTsf7OFdDPsI9bz3USrneZA)9)))) goto LA10_;
			failedAssertImpl__stdZassertions_u274(TM__VOZez4W9a02yKrIR7zij6nQ_5);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
LA10_: ;
		nimln_(113);
		if (n1 < 0 || n1 >= tree_p2.nodes.len){ raiseIndexError2(n1,tree_p2.nodes.len-1); goto BeforeRet_;
		}
		m = ((NU32) (tree_p2.nodes.p->data[n1].operand));
		nimln_(114);
		if (n2 < 0 || n2 >= tree_p2.nodes.len){ raiseIndexError2(n2,tree_p2.nodes.len-1); goto BeforeRet_;
		}
		item = tree_p2.nodes.p->data[n2].operand;
		nimln_(115);
		T12_ = (NI32)0;
		T12_ = toFileIndexCached__icZic_u7725((&(*c_p0).decoder), g_p1, (*c_p0).thisModule, m);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		otherModule = ((NI) (T12_));
		nimln_(116);
		followLater__icZdce_u1685(c_p0, g_p1, otherModule, item);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	break;
	case ((tyEnum_TNodeKind__iTsf7OFdDPsI9bz3USrneZA)82):
	case ((tyEnum_TNodeKind__iTsf7OFdDPsI9bz3USrneZA)83):
	case ((tyEnum_TNodeKind__iTsf7OFdDPsI9bz3USrneZA)98):
	case ((tyEnum_TNodeKind__iTsf7OFdDPsI9bz3USrneZA)132):
	case ((tyEnum_TNodeKind__iTsf7OFdDPsI9bz3USrneZA)125):
	case ((tyEnum_TNodeKind__iTsf7OFdDPsI9bz3USrneZA)121):
	case ((tyEnum_TNodeKind__iTsf7OFdDPsI9bz3USrneZA)116):
	case ((tyEnum_TNodeKind__iTsf7OFdDPsI9bz3USrneZA)117):
	case ((tyEnum_TNodeKind__iTsf7OFdDPsI9bz3USrneZA)118):
	case ((tyEnum_TNodeKind__iTsf7OFdDPsI9bz3USrneZA)119):
	case ((tyEnum_TNodeKind__iTsf7OFdDPsI9bz3USrneZA)120):
	case ((tyEnum_TNodeKind__iTsf7OFdDPsI9bz3USrneZA)113):
	{
	}
	break;
	case ((tyEnum_TNodeKind__iTsf7OFdDPsI9bz3USrneZA)99):
	case ((tyEnum_TNodeKind__iTsf7OFdDPsI9bz3USrneZA)100):
	case ((tyEnum_TNodeKind__iTsf7OFdDPsI9bz3USrneZA)101):
	{
		{
			NI son;
			NI pos;
			NI32 last;
			NI32 TM__VOZez4W9a02yKrIR7zij6nQ_8;
			NI TM__VOZez4W9a02yKrIR7zij6nQ_9;
			son = (NI)0;
			nimlf_(206, "D:\\nim\\compiler\\ic\\packed_ast.nim");
			pos = n_p3;
			nimln_(207);
			{
				if (pos < 0 || pos >= tree_p2.nodes.len){ raiseIndexError2(pos,tree_p2.nodes.len-1); goto BeforeRet_;
				}
				if (!!((((tyEnum_TNodeKind__iTsf7OFdDPsI9bz3USrneZA)23) < tree_p2.nodes.p->data[pos].kind))) goto LA18_;
				failedAssertImpl__stdZassertions_u274(TM__VOZez4W9a02yKrIR7zij6nQ_7);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			}
LA18_: ;
			nimln_(208);
			if (pos < 0 || pos >= tree_p2.nodes.len){ raiseIndexError2(pos,tree_p2.nodes.len-1); goto BeforeRet_;
			}
			if (nimAddInt(((NI32) (pos)), tree_p2.nodes.p->data[pos].operand, &TM__VOZez4W9a02yKrIR7zij6nQ_8)) { raiseOverflow(); goto BeforeRet_;
			};
			last = (NI32)(TM__VOZez4W9a02yKrIR7zij6nQ_8);
			nimln_(209);
			if (nimAddInt(pos, ((NI)1), &TM__VOZez4W9a02yKrIR7zij6nQ_9)) { raiseOverflow(); goto BeforeRet_;
			};
			pos = (NI)(TM__VOZez4W9a02yKrIR7zij6nQ_9);
			{
				nimln_(210);
				while (1) {
					if (!(((NI32) (pos)) < last)) goto LA21;
					nimlf_(124, "D:\\nim\\compiler\\ic\\dce.nim");
					son = pos;
					aliveCode__icZdce_u1986(c_p0, g_p1, tree_p2, son);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					nimlf_(212, "D:\\nim\\compiler\\ic\\packed_ast.nim");
					nextChild__icZpacked95ast_u536(tree_p2, (&pos));
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				} LA21: ;
			}
		}
	}
	break;
	case ((tyEnum_TNodeKind__iTsf7OFdDPsI9bz3USrneZA)68):
	case ((tyEnum_TNodeKind__iTsf7OFdDPsI9bz3USrneZA)69):
	case ((tyEnum_TNodeKind__iTsf7OFdDPsI9bz3USrneZA)70):
	{
		nimlf_(127, "D:\\nim\\compiler\\ic\\dce.nim");
		rangeCheckAnalysis__icZdce_u1966(c_p0, g_p1, tree_p2, n_p3);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	break;
	case ((tyEnum_TNodeKind__iTsf7OFdDPsI9bz3USrneZA)79):
	case ((tyEnum_TNodeKind__iTsf7OFdDPsI9bz3USrneZA)81):
	case ((tyEnum_TNodeKind__iTsf7OFdDPsI9bz3USrneZA)80):
	case ((tyEnum_TNodeKind__iTsf7OFdDPsI9bz3USrneZA)159):
	case ((tyEnum_TNodeKind__iTsf7OFdDPsI9bz3USrneZA)84):
	{
		nimln_(129);
		{
			NIM_BOOL T26_;
			NI T27_;
			NI T29_;
			NI32 item_2;
			NI T32_;
			T26_ = (NIM_BOOL)0;
			T27_ = (NI)0;
			T27_ = firstSon__icZpacked95ast_u851(n_p3);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (T27_ < 0 || T27_ >= tree_p2.nodes.len){ raiseIndexError2(T27_,tree_p2.nodes.len-1); goto BeforeRet_;
			}
			T26_ = (tree_p2.nodes.p->data[T27_].kind == ((tyEnum_TNodeKind__iTsf7OFdDPsI9bz3USrneZA)3));
			if (!(T26_)) goto LA28_;
			nimln_(48);
			T29_ = (NI)0;
			T29_ = ithSon__icZpacked95ast_u822(tree_p2, n_p3, ((NI)2));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (T29_ < 0 || T29_ >= tree_p2.nodes.len){ raiseIndexError2(T29_,tree_p2.nodes.len-1); goto BeforeRet_;
			}
			T26_ = (tree_p2.nodes.p->data[T29_].kind == ((tyEnum_TNodeKind__iTsf7OFdDPsI9bz3USrneZA)1));
LA28_: ;
			if (!T26_) goto LA30_;
			nimln_(130);
			T32_ = (NI)0;
			T32_ = firstSon__icZpacked95ast_u851(n_p3);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (T32_ < 0 || T32_ >= tree_p2.nodes.len){ raiseIndexError2(T32_,tree_p2.nodes.len-1); goto BeforeRet_;
			}
			item_2 = tree_p2.nodes.p->data[T32_].operand;
			nimln_(131);
			{
				NIM_BOOL T35_;
				T35_ = (NIM_BOOL)0;
				T35_ = isExportedToC__icZdce_u26(c_p0, g_p1, item_2);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				if (!T35_) goto LA36_;
				nimln_(133);
				followLater__icZdce_u1685(c_p0, g_p1, (*c_p0).thisModule, item_2);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			}
LA36_: ;
		}
LA30_: ;
	}
	break;
	default:
	{
		{
			NI son_2;
			NI pos_2;
			NI32 last_2;
			NI32 TM__VOZez4W9a02yKrIR7zij6nQ_30;
			NI TM__VOZez4W9a02yKrIR7zij6nQ_31;
			son_2 = (NI)0;
			nimlf_(206, "D:\\nim\\compiler\\ic\\packed_ast.nim");
			pos_2 = n_p3;
			nimln_(207);
			{
				if (pos_2 < 0 || pos_2 >= tree_p2.nodes.len){ raiseIndexError2(pos_2,tree_p2.nodes.len-1); goto BeforeRet_;
				}
				if (!!((((tyEnum_TNodeKind__iTsf7OFdDPsI9bz3USrneZA)23) < tree_p2.nodes.p->data[pos_2].kind))) goto LA42_;
				failedAssertImpl__stdZassertions_u274(TM__VOZez4W9a02yKrIR7zij6nQ_29);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			}
LA42_: ;
			nimln_(208);
			if (pos_2 < 0 || pos_2 >= tree_p2.nodes.len){ raiseIndexError2(pos_2,tree_p2.nodes.len-1); goto BeforeRet_;
			}
			if (nimAddInt(((NI32) (pos_2)), tree_p2.nodes.p->data[pos_2].operand, &TM__VOZez4W9a02yKrIR7zij6nQ_30)) { raiseOverflow(); goto BeforeRet_;
			};
			last_2 = (NI32)(TM__VOZez4W9a02yKrIR7zij6nQ_30);
			nimln_(209);
			if (nimAddInt(pos_2, ((NI)1), &TM__VOZez4W9a02yKrIR7zij6nQ_31)) { raiseOverflow(); goto BeforeRet_;
			};
			pos_2 = (NI)(TM__VOZez4W9a02yKrIR7zij6nQ_31);
			{
				nimln_(210);
				while (1) {
					if (!(((NI32) (pos_2)) < last_2)) goto LA45;
					nimlf_(135, "D:\\nim\\compiler\\ic\\dce.nim");
					son_2 = pos_2;
					aliveCode__icZdce_u1986(c_p0, g_p1, tree_p2, son_2);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					nimlf_(212, "D:\\nim\\compiler\\ic\\packed_ast.nim");
					nextChild__icZpacked95ast_u536(tree_p2, (&pos_2));
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				} LA45: ;
			}
		}
	}
	break;
	}
	}
BeforeRet_: ;
	popFrame();
}
static N_INLINE(NIM_BOOL, isAtom__icZpacked95ast_u392)(tyObject_PackedTree__dwpfxIasCzder2kO8Kc6gw tree_p0, NI pos_p1) {
	NIM_BOOL result;
	nimfr_("isAtom", "D:\\nim\\compiler\\ic\\packed_ast.nim");
{	result = (NIM_BOOL)0;
	nimlf_(151, "D:\\nim\\compiler\\ic\\packed_ast.nim");
	if (pos_p1 < 0 || pos_p1 >= tree_p0.nodes.len){ raiseIndexError2(pos_p1,tree_p0.nodes.len-1); goto BeforeRet_;
	}
	result = (tree_p0.nodes.p->data[pos_p1].kind <= ((tyEnum_TNodeKind__iTsf7OFdDPsI9bz3USrneZA)23));
	}
BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NI, span__icZpacked95ast_u760)(tyObject_PackedTree__dwpfxIasCzder2kO8Kc6gw tree_p0, NI pos_p1) {
	NI result;
	NI colontmpD_;
	NI colontmpD__2;
NIM_BOOL* nimErr_;
	nimfr_("span", "D:\\nim\\compiler\\ic\\packed_ast.nim");
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	colontmpD_ = (NI)0;
	colontmpD__2 = (NI)0;
	nimlf_(291, "D:\\nim\\compiler\\ic\\packed_ast.nim");
	nimln_(292);
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = isAtom__icZpacked95ast_u392(tree_p0, pos_p1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!T3_) goto LA4_;
		colontmpD_ = ((NI)1);
		result = colontmpD_;
	}
	goto LA1_;
LA4_: ;
	{
		if (pos_p1 < 0 || pos_p1 >= tree_p0.nodes.len){ raiseIndexError2(pos_p1,tree_p0.nodes.len-1); goto BeforeRet_;
		}
		colontmpD__2 = ((NI) (tree_p0.nodes.p->data[pos_p1].operand));
		result = colontmpD__2;
	}
LA1_: ;
	}
BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(tyTuple__Ipyq9bHX9c9bJZHIF5McOHjZw, pop__icZdce_u2042)(tySequence__Ce9b1KFbvUi5pelXDWCUccg* s_p0) {
	tyTuple__Ipyq9bHX9c9bJZHIF5McOHjZw result;
	NI L;
	NI T1_;
	NI TM__VOZez4W9a02yKrIR7zij6nQ_34;
	nimfr_("pop", "D:\\nim\\lib\\system.nim");
{	nimZeroMem((void*)(&result), sizeof(tyTuple__Ipyq9bHX9c9bJZHIF5McOHjZw));
	nimlf_(1654, "D:\\nim\\lib\\system.nim");
	T1_ = (*s_p0).len;
	if (nimSubInt(T1_, ((NI)1), &TM__VOZez4W9a02yKrIR7zij6nQ_34)) { raiseOverflow(); goto BeforeRet_;
	};
	L = (NI)(TM__VOZez4W9a02yKrIR7zij6nQ_34);
	nimln_(1656);
	if (L < 0 || L >= (*s_p0).len){ raiseIndexError2(L,(*s_p0).len-1); goto BeforeRet_;
	}
	result = (*s_p0).p->data[L];
	nimZeroMem((void*)(&(*s_p0).p->data[L]), sizeof(tyTuple__Ipyq9bHX9c9bJZHIF5McOHjZw));
	nimln_(1657);
	if ((L) < ((NI)0) || (L) > ((NI)2147483647)){ raiseRangeErrorI(L, ((NI)0), ((NI)2147483647)); goto BeforeRet_;
	}
	shrink__icZdce_u2057(s_p0, ((NI) (L)));
	}
BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, followNow__icZdce_u2036)(tyObject_AliveContext__tphvFQ1TBCtddorfkjJxgA* c_p0, tySequence__1WrxDEO4S4oG9cJb0EDwItQ g_p1) {
NIM_BOOL* nimErr_;
	nimfr_("followNow", "D:\\nim\\compiler\\ic\\dce.nim");
{nimErr_ = nimErrorFlag();
	{
		nimlf_(141, "D:\\nim\\compiler\\ic\\dce.nim");
		while (1) {
			NI T3_;
			tyTuple__Ipyq9bHX9c9bJZHIF5McOHjZw tmpTuple;
			NI modId;
			tySet_tyEnum_TOption__CLLiALVaa7s1J9a3MO8USnA opt;
			NI ast;
			T3_ = (*c_p0).stack.len;
			if (!(((NI)0) < T3_)) goto LA2;
			nimln_(142);
			tmpTuple = pop__icZdce_u2042((&(*c_p0).stack));
			modId = tmpTuple.Field0;
			opt = tmpTuple.Field1;
			ast = tmpTuple.Field2;
			nimln_(143);
			(*c_p0).thisModule = modId;
			nimln_(144);
			(*c_p0).options = opt;
			nimln_(145);
			if (modId < 0 || modId >= g_p1.len){ raiseIndexError2(modId,g_p1.len-1); goto BeforeRet_;
			}
			aliveCode__icZdce_u1986(c_p0, g_p1, g_p1.p->data[modId].fromDisk.bodies, ast);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		} LA2: ;
	}
	}
BeforeRet_: ;
	popFrame();
}
static N_INLINE(NI, minuspercent___system_u790)(NI x_p0, NI y_p1) {
	NI result;
	nimfr_("-%", "D:\\nim\\lib\\system\\arithmetics.nim");
	result = (NI)0;
	nimlf_(363, "D:\\nim\\lib\\system\\arithmetics.nim");
	nimln_(364);
	nimln_(368);
	result = ((NI) ((NU)((NU32)(((NU) (x_p0))) - (NU32)(((NU) (y_p1))))));
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL, nimDecRefIsLastDyn)(void* p_p0) {
	NIM_BOOL result;
	nimfr_("nimDecRefIsLastDyn", "D:\\nim\\lib\\system\\orc.nim");
{	result = (NIM_BOOL)0;
	nimlf_(489, "D:\\nim\\lib\\system\\orc.nim");
	{
		tyObject_RefHeader__b9cZ5ThQEAqSv7VLAQu0wEw* cell;
		NI T5_;
		if (!!((p_p0 == NIM_NIL))) goto LA3_;
		nimln_(490);
		nimlf_(43, "D:\\nim\\lib\\system\\arc.nim");
		T5_ = (NI)0;
		T5_ = minuspercent___system_u790(((NI) (ptrdiff_t) (p_p0)), ((NI)8));
		cell = ((tyObject_RefHeader__b9cZ5ThQEAqSv7VLAQu0wEw*) (T5_));
		nimlf_(491, "D:\\nim\\lib\\system\\orc.nim");
		{
			if (!((NI)((*cell).rc & ((NI)-16)) == ((NI)0))) goto LA8_;
			nimln_(492);
			result = NIM_TRUE;
		}
		goto LA6_;
LA8_: ;
		{
			NI TM__VOZez4W9a02yKrIR7zij6nQ_35;
			nimln_(495);
			if (nimSubInt((*cell).rc, ((NI)16), &TM__VOZez4W9a02yKrIR7zij6nQ_35)) { raiseOverflow(); goto BeforeRet_;
			};
			(*cell).rc = (NI)(TM__VOZez4W9a02yKrIR7zij6nQ_35);
		}
LA6_: ;
		nimln_(497);
		{
			if (!result) goto LA13_;
			nimln_(498);
			{
				if (!(((NI)0) < (*cell).rootIdx)) goto LA17_;
				nimln_(499);
				unregisterCycle__system_u2848(cell);
			}
LA17_: ;
		}
LA13_: ;
	}
LA3_: ;
	}
BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicStatic)(void* p_p0, TNimTypeV2* desc_p1) {
	NIM_BOOL result;
NIM_BOOL* nimErr_;
	nimfr_("nimDecRefIsLastCyclicStatic", "D:\\nim\\lib\\system\\orc.nim");
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	nimlf_(502, "D:\\nim\\lib\\system\\orc.nim");
	{
		tyObject_RefHeader__b9cZ5ThQEAqSv7VLAQu0wEw* cell;
		NI T5_;
		if (!!((p_p0 == NIM_NIL))) goto LA3_;
		nimln_(503);
		nimlf_(43, "D:\\nim\\lib\\system\\arc.nim");
		T5_ = (NI)0;
		T5_ = minuspercent___system_u790(((NI) (ptrdiff_t) (p_p0)), ((NI)8));
		cell = ((tyObject_RefHeader__b9cZ5ThQEAqSv7VLAQu0wEw*) (T5_));
		nimlf_(504, "D:\\nim\\lib\\system\\orc.nim");
		{
			if (!((NI)((*cell).rc & ((NI)-16)) == ((NI)0))) goto LA8_;
			nimln_(505);
			result = NIM_TRUE;
		}
		goto LA6_;
LA8_: ;
		{
			NI TM__VOZez4W9a02yKrIR7zij6nQ_36;
			nimln_(508);
			if (nimSubInt((*cell).rc, ((NI)16), &TM__VOZez4W9a02yKrIR7zij6nQ_36)) { raiseOverflow(); goto BeforeRet_;
			};
			(*cell).rc = (NI)(TM__VOZez4W9a02yKrIR7zij6nQ_36);
		}
LA6_: ;
		nimln_(510);
		rememberCycle__system_u3251(result, cell, desc_p1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA3_: ;
	}
BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___icZdce_u2208)(tyObject_AliveContext__tphvFQ1TBCtddorfkjJxgA* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___icZdce_u2162((&(*dest_p0).stack));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastDyn((*dest_p0).decoder.config);
		if (!T3_) goto LA4_;
		eqdestroy___options_u3373((*dest_p0).decoder.config);
		nimRawDispose((*dest_p0).decoder.config, ((NI)4));
	}
LA4_: ;
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicStatic((*dest_p0).decoder.cache, (&NTIv2__LYhYfW7zHVa6k72gTbQGLw_));
		if (!T8_) goto LA9_;
		eqdestroy___idents_u262((*dest_p0).decoder.cache);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimRawDispose((*dest_p0).decoder.cache, ((NI)4));
	}
LA9_: ;
	eqdestroy___nilcheck_u1382((&(*dest_p0).alive));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	eqdestroy___icZdce_u609((&(*dest_p0).compilerProcs.data));
	}
BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(tySequence__RlbT8oLuVw9ay3ljjVb9c8lw, computeAliveSyms__icZdce_u2106)(tySequence__1WrxDEO4S4oG9cJb0EDwItQ g_p0, tyObject_ConfigRefcolonObjectType___bmtyrreM9bjbWfPTnr9btEbw* conf_p1) {
	tySequence__RlbT8oLuVw9ay3ljjVb9c8lw result;
	tyObject_AliveContext__tphvFQ1TBCtddorfkjJxgA c;
	tyObject_ConfigRefcolonObjectType___bmtyrreM9bjbWfPTnr9btEbw* colontmpD_;
	tySet_tyEnum_TOption__CLLiALVaa7s1J9a3MO8USnA colontmpD__2;
	NI T2_;
NIM_BOOL oldNimErrFin1_;
NIM_BOOL* nimErr_;
	nimfr_("computeAliveSyms", "D:\\nim\\compiler\\ic\\dce.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimZeroMem((void*)(&c), sizeof(tyObject_AliveContext__tphvFQ1TBCtddorfkjJxgA));
	colontmpD_ = NIM_NIL;
	nimZeroMem((void*)(&colontmpD__2), sizeof(tySet_tyEnum_TOption__CLLiALVaa7s1J9a3MO8USnA));
	nimlf_(149, "D:\\nim\\compiler\\ic\\dce.nim");
	nimZeroMem((void*)(&c), sizeof(tyObject_AliveContext__tphvFQ1TBCtddorfkjJxgA));
	c.stack.len = 0; c.stack.p = (tySequence__Ce9b1KFbvUi5pelXDWCUccg_Content*) newSeqPayload(0, sizeof(tyTuple__Ipyq9bHX9c9bJZHIF5McOHjZw), NIM_ALIGNOF(tyTuple__Ipyq9bHX9c9bJZHIF5McOHjZw));
	nimZeroMem((void*)(&c.decoder), sizeof(tyObject_PackedDecoder__YPhZig7ahPz3H2faubl5zA));
	nimlf_(533, "D:\\nim\\compiler\\options.nim");
	eqwasMoved___options_u3750(&colontmpD_);
	eqcopy___options_u3756(&colontmpD_, conf_p1);
	c.decoder.config = colontmpD_;
	c.thisModule = ((NI)-1);
	nimlf_(150, "D:\\nim\\compiler\\ic\\dce.nim");
	T2_ = g_p0.len;
	if ((T2_) < ((NI)0) || (T2_) > ((NI)2147483647)){ raiseRangeErrorI(T2_, ((NI)0), ((NI)2147483647)); goto LA1_;
	}
	c.alive = newSeq__icZdce_u2126(((NI) (T2_)));
	nimln_(151);
	colontmpD__2 = (*conf_p1).options;
	c.options = colontmpD__2;
	{
		NI i;
		NI colontmp_;
		NI T4_;
		NI res;
		i = (NI)0;
		colontmp_ = (NI)0;
		nimlf_(6, "D:\\nim\\lib\\system\\iterators_1.nim");
		nimlf_(152, "D:\\nim\\compiler\\ic\\dce.nim");
		T4_ = (g_p0.len-1);
		colontmp_ = T4_;
		nimlf_(33, "D:\\nim\\lib\\system\\iterators_1.nim");
		res = colontmp_;
		{
			nimln_(34);
			while (1) {
				NI TM__VOZez4W9a02yKrIR7zij6nQ_33;
				if (!(((NI)0) <= res)) goto LA6;
				nimlf_(152, "D:\\nim\\compiler\\ic\\dce.nim");
				i = res;
				{
					nimln_(153);
					if (i < 0 || i >= g_p0.len){ raiseIndexError2(i,g_p0.len-1); goto LA1_;
					}
					if (!!((g_p0.p->data[i].status == ((tyEnum_ModuleStatus__0KkdgkcO3EbJQ2rT80ED9cQ)0)))) goto LA9_;
					nimln_(154);
					c.thisModule = i;
					{
						tyObject_PackedTree__dwpfxIasCzder2kO8Kc6gw colontmp__2;
						NI p;
						NI p_2;
						nimZeroMem((void*)(&colontmp__2), sizeof(tyObject_PackedTree__dwpfxIasCzder2kO8Kc6gw));
						p = (NI)0;
						nimlf_(412, "D:\\nim\\compiler\\ic\\packed_ast.nim");
						nimZeroMem((void*)(&colontmp__2), sizeof(tyObject_PackedTree__dwpfxIasCzder2kO8Kc6gw));
						nimln_(216);
						if (i < 0 || i >= g_p0.len){ raiseIndexError2(i,g_p0.len-1); goto LA12_;
						}
						eqcopy___icZpacked95ast_u589((&colontmp__2), g_p0.p->data[i].fromDisk.topLevel);
						nimln_(413);
						p_2 = ((NI)0);
						{
							nimln_(414);
							while (1) {
								NI T15_;
								NI s;
								NI TM__VOZez4W9a02yKrIR7zij6nQ_32;
								T15_ = (NI)0;
								T15_ = len__icZpacked95ast_u510(colontmp__2);
								if (NIM_UNLIKELY(*nimErr_)) goto LA12_;
								if (!(p_2 < T15_)) goto LA14;
								nimlf_(155, "D:\\nim\\compiler\\ic\\dce.nim");
								p = p_2;
								if (i < 0 || i >= g_p0.len){ raiseIndexError2(i,g_p0.len-1); goto LA12_;
								}
								aliveCode__icZdce_u1986((&c), g_p0, g_p0.p->data[i].fromDisk.topLevel, p);
								if (NIM_UNLIKELY(*nimErr_)) goto LA12_;
								nimlf_(416, "D:\\nim\\compiler\\ic\\packed_ast.nim");
								s = span__icZpacked95ast_u760(colontmp__2, p_2);
								if (NIM_UNLIKELY(*nimErr_)) goto LA12_;
								nimln_(417);
								if (nimAddInt(p_2, s, &TM__VOZez4W9a02yKrIR7zij6nQ_32)) { raiseOverflow(); goto LA12_;
								};
								p_2 = (NI)(TM__VOZez4W9a02yKrIR7zij6nQ_32);
							} LA14: ;
						}
						{
							LA12_:;
						}
						{
							nimln_(216);
							eqdestroy___icZpacked95ast_u586((&colontmp__2));
						}
						if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
					}
				}
LA9_: ;
				nimlf_(36, "D:\\nim\\lib\\system\\iterators_1.nim");
				if (nimSubInt(res, ((NI)1), &TM__VOZez4W9a02yKrIR7zij6nQ_33)) { raiseOverflow(); goto LA1_;
				};
				res = (NI)(TM__VOZez4W9a02yKrIR7zij6nQ_33);
			} LA6: ;
		}
	}
	nimlf_(158, "D:\\nim\\compiler\\ic\\dce.nim");
	followNow__icZdce_u2036((&c), g_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimln_(159);
	result = c.alive;
	c.alive.len = 0; c.alive.p = NIM_NIL;
	{
		LA1_:;
	}
	{
		oldNimErrFin1_ = *nimErr_; *nimErr_ = NIM_FALSE;
		nimln_(149);
		eqdestroy___icZdce_u2208((&c));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		*nimErr_ = oldNimErrFin1_;
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
BeforeRet_: ;
	popFrame();
	return result;
}
