/* Generated by Nim Compiler v1.9.3 */
#define NIM_INTBITS 32

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #define nimfrs_(proc, file, slots, length) \
    struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename;NI len;VarSlot s[slots];} FR_; \
    FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #define nimln_(n) \
    FR_.line = n;

  #define nimlf_(n, file) \
    FR_.line = n; FR_.filename = file;

typedef struct tyObject_StringTableObj__eQlzBfCID7uSzbD7mP9cuYw tyObject_StringTableObj__eQlzBfCID7uSzbD7mP9cuYw;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
typedef NU8 tyEnum_Feature__M3s7Uywm9c5BlzNIKwZFu3g;
typedef NU8 tyEnum_TMsgKind__aghsq7zHWm205GRPJE9a2yw;
N_LIB_PRIVATE N_NIMCALL(void, nstPut)(tyObject_StringTableObj__eQlzBfCID7uSzbD7mP9cuYw* t_p0, NimStringV2 key_p1, NimStringV2 val_p2);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4294)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(void, del__pureZstrtabs_u591)(tyObject_StringTableObj__eQlzBfCID7uSzbD7mP9cuYw* t_p0, NimStringV2 key_p1);
N_LIB_PRIVATE N_NIMCALL(void, defineSymbol__condsyms_u4)(tyObject_StringTableObj__eQlzBfCID7uSzbD7mP9cuYw* symbols_p0, NimStringV2 symbol_p1, NimStringV2 value_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(void, copyMem__system_u1720)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___options_u255)(tyEnum_Feature__M3s7Uywm9c5BlzNIKwZFu3g e_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, rawNewString)(NI space_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___stdZassertions_u16)(NimStringV2* dest_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___lineinfos_u127)(tyEnum_TMsgKind__aghsq7zHWm205GRPJE9a2yw e_p0);
static const struct {
  NI cap; NIM_CHAR data[10+1];
} TM__9cXbbi8LuWedlpH77PUxfew_2 = { 10 | NIM_STRLIT_FLAG, "nimhygiene" };
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_3 = {10, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_2};
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__9cXbbi8LuWedlpH77PUxfew_4 = { 4 | NIM_STRLIT_FLAG, "true" };
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_5 = {4, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_4};
static const struct {
  NI cap; NIM_CHAR data[14+1];
} TM__9cXbbi8LuWedlpH77PUxfew_6 = { 14 | NIM_STRLIT_FLAG, "niminheritable" };
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_7 = {14, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_6};
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_8 = {4, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_4};
static const struct {
  NI cap; NIM_CHAR data[8+1];
} TM__9cXbbi8LuWedlpH77PUxfew_9 = { 8 | NIM_STRLIT_FLAG, "nimmixin" };
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_10 = {8, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_9};
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_11 = {4, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_4};
static const struct {
  NI cap; NIM_CHAR data[10+1];
} TM__9cXbbi8LuWedlpH77PUxfew_12 = { 10 | NIM_STRLIT_FLAG, "nimeffects" };
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_13 = {10, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_12};
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_14 = {4, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_4};
static const struct {
  NI cap; NIM_CHAR data[8+1];
} TM__9cXbbi8LuWedlpH77PUxfew_15 = { 8 | NIM_STRLIT_FLAG, "nimbabel" };
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_16 = {8, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_15};
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_17 = {4, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_4};
static const struct {
  NI cap; NIM_CHAR data[15+1];
} TM__9cXbbi8LuWedlpH77PUxfew_18 = { 15 | NIM_STRLIT_FLAG, "nimcomputedgoto" };
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_19 = {15, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_18};
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_20 = {4, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_4};
static const struct {
  NI cap; NIM_CHAR data[8+1];
} TM__9cXbbi8LuWedlpH77PUxfew_21 = { 8 | NIM_STRLIT_FLAG, "nimunion" };
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_22 = {8, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_21};
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_23 = {4, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_4};
static const struct {
  NI cap; NIM_CHAR data[12+1];
} TM__9cXbbi8LuWedlpH77PUxfew_24 = { 12 | NIM_STRLIT_FLAG, "nimnewshared" };
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_25 = {12, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_24};
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_26 = {4, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_4};
static const struct {
  NI cap; NIM_CHAR data[14+1];
} TM__9cXbbi8LuWedlpH77PUxfew_27 = { 14 | NIM_STRLIT_FLAG, "nimNewTypedesc" };
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_28 = {14, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_27};
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_29 = {4, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_4};
static const struct {
  NI cap; NIM_CHAR data[19+1];
} TM__9cXbbi8LuWedlpH77PUxfew_30 = { 19 | NIM_STRLIT_FLAG, "nimrequiresnimframe" };
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_31 = {19, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_30};
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_32 = {4, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_4};
static const struct {
  NI cap; NIM_CHAR data[25+1];
} TM__9cXbbi8LuWedlpH77PUxfew_33 = { 25 | NIM_STRLIT_FLAG, "nimparsebiggestfloatmagic" };
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_34 = {25, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_33};
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_35 = {4, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_4};
static const struct {
  NI cap; NIM_CHAR data[8+1];
} TM__9cXbbi8LuWedlpH77PUxfew_36 = { 8 | NIM_STRLIT_FLAG, "nimalias" };
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_37 = {8, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_36};
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_38 = {4, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_4};
static const struct {
  NI cap; NIM_CHAR data[8+1];
} TM__9cXbbi8LuWedlpH77PUxfew_39 = { 8 | NIM_STRLIT_FLAG, "nimlocks" };
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_40 = {8, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_39};
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_41 = {4, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_4};
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__9cXbbi8LuWedlpH77PUxfew_42 = { 7 | NIM_STRLIT_FLAG, "nimnode" };
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_43 = {7, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_42};
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_44 = {4, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_4};
static const struct {
  NI cap; NIM_CHAR data[15+1];
} TM__9cXbbi8LuWedlpH77PUxfew_45 = { 15 | NIM_STRLIT_FLAG, "nimvarargstyped" };
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_46 = {15, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_45};
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_47 = {4, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_4};
static const struct {
  NI cap; NIM_CHAR data[16+1];
} TM__9cXbbi8LuWedlpH77PUxfew_48 = { 16 | NIM_STRLIT_FLAG, "nimtypedescfixed" };
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_49 = {16, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_48};
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_50 = {4, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_4};
static const struct {
  NI cap; NIM_CHAR data[13+1];
} TM__9cXbbi8LuWedlpH77PUxfew_51 = { 13 | NIM_STRLIT_FLAG, "nimKnowsNimvm" };
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_52 = {13, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_51};
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_53 = {4, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_4};
static const struct {
  NI cap; NIM_CHAR data[9+1];
} TM__9cXbbi8LuWedlpH77PUxfew_54 = { 9 | NIM_STRLIT_FLAG, "nimArrIdx" };
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_55 = {9, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_54};
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_56 = {4, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_4};
static const struct {
  NI cap; NIM_CHAR data[13+1];
} TM__9cXbbi8LuWedlpH77PUxfew_57 = { 13 | NIM_STRLIT_FLAG, "nimHasalignOf" };
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_58 = {13, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_57};
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_59 = {4, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_4};
static const struct {
  NI cap; NIM_CHAR data[10+1];
} TM__9cXbbi8LuWedlpH77PUxfew_60 = { 10 | NIM_STRLIT_FLAG, "nimDistros" };
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_61 = {10, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_60};
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_62 = {4, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_4};
static const struct {
  NI cap; NIM_CHAR data[15+1];
} TM__9cXbbi8LuWedlpH77PUxfew_63 = { 15 | NIM_STRLIT_FLAG, "nimHasCppDefine" };
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_64 = {15, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_63};
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_65 = {4, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_4};
static const struct {
  NI cap; NIM_CHAR data[20+1];
} TM__9cXbbi8LuWedlpH77PUxfew_66 = { 20 | NIM_STRLIT_FLAG, "nimGenericInOutFlags" };
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_67 = {20, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_66};
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_68 = {4, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_4};
static const struct {
  NI cap; NIM_CHAR data[29+1];
} TM__9cXbbi8LuWedlpH77PUxfew_69 = { 29 | NIM_STRLIT_FLAG, "nimNoArrayToCstringConversion" };
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_70 = {29, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_69};
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_71 = {4, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_4};
static const struct {
  NI cap; NIM_CHAR data[22+1];
} TM__9cXbbi8LuWedlpH77PUxfew_72 = { 22 | NIM_STRLIT_FLAG, "nimHasRunnableExamples" };
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_73 = {22, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_72};
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_74 = {4, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_4};
static const struct {
  NI cap; NIM_CHAR data[9+1];
} TM__9cXbbi8LuWedlpH77PUxfew_75 = { 9 | NIM_STRLIT_FLAG, "nimNewDot" };
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_76 = {9, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_75};
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_77 = {4, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_4};
static const struct {
  NI cap; NIM_CHAR data[15+1];
} TM__9cXbbi8LuWedlpH77PUxfew_78 = { 15 | NIM_STRLIT_FLAG, "nimHasNilChecks" };
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_79 = {15, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_78};
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_80 = {4, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_4};
static const struct {
  NI cap; NIM_CHAR data[10+1];
} TM__9cXbbi8LuWedlpH77PUxfew_81 = { 10 | NIM_STRLIT_FLAG, "nimSymKind" };
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_82 = {10, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_81};
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_83 = {4, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_4};
static const struct {
  NI cap; NIM_CHAR data[12+1];
} TM__9cXbbi8LuWedlpH77PUxfew_84 = { 12 | NIM_STRLIT_FLAG, "nimVmEqIdent" };
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_85 = {12, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_84};
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_86 = {4, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_4};
static const struct {
  NI cap; NIM_CHAR data[8+1];
} TM__9cXbbi8LuWedlpH77PUxfew_87 = { 8 | NIM_STRLIT_FLAG, "nimNoNil" };
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_88 = {8, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_87};
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_89 = {4, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_4};
static const struct {
  NI cap; NIM_CHAR data[19+1];
} TM__9cXbbi8LuWedlpH77PUxfew_90 = { 19 | NIM_STRLIT_FLAG, "nimNoZeroTerminator" };
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_91 = {19, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_90};
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_92 = {4, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_4};
static const struct {
  NI cap; NIM_CHAR data[9+1];
} TM__9cXbbi8LuWedlpH77PUxfew_93 = { 9 | NIM_STRLIT_FLAG, "nimNotNil" };
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_94 = {9, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_93};
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_95 = {4, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_4};
static const struct {
  NI cap; NIM_CHAR data[16+1];
} TM__9cXbbi8LuWedlpH77PUxfew_96 = { 16 | NIM_STRLIT_FLAG, "nimVmExportFixed" };
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_97 = {16, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_96};
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_98 = {4, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_4};
static const struct {
  NI cap; NIM_CHAR data[21+1];
} TM__9cXbbi8LuWedlpH77PUxfew_99 = { 21 | NIM_STRLIT_FLAG, "nimHasSymOwnerInMacro" };
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_100 = {21, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_99};
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_101 = {4, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_4};
static const struct {
  NI cap; NIM_CHAR data[13+1];
} TM__9cXbbi8LuWedlpH77PUxfew_102 = { 13 | NIM_STRLIT_FLAG, "nimNewRuntime" };
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_103 = {13, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_102};
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_104 = {4, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_4};
static const struct {
  NI cap; NIM_CHAR data[12+1];
} TM__9cXbbi8LuWedlpH77PUxfew_105 = { 12 | NIM_STRLIT_FLAG, "nimIncrSeqV3" };
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_106 = {12, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_105};
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_107 = {4, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_4};
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__9cXbbi8LuWedlpH77PUxfew_108 = { 7 | NIM_STRLIT_FLAG, "nimAshr" };
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_109 = {7, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_108};
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_110 = {4, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_4};
static const struct {
  NI cap; NIM_CHAR data[12+1];
} TM__9cXbbi8LuWedlpH77PUxfew_111 = { 12 | NIM_STRLIT_FLAG, "nimNoNilSeqs" };
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_112 = {12, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_111};
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_113 = {4, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_4};
static const struct {
  NI cap; NIM_CHAR data[13+1];
} TM__9cXbbi8LuWedlpH77PUxfew_114 = { 13 | NIM_STRLIT_FLAG, "nimNoNilSeqs2" };
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_115 = {13, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_114};
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_116 = {4, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_4};
static const struct {
  NI cap; NIM_CHAR data[16+1];
} TM__9cXbbi8LuWedlpH77PUxfew_117 = { 16 | NIM_STRLIT_FLAG, "nimHasUserErrors" };
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_118 = {16, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_117};
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_119 = {4, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_4};
static const struct {
  NI cap; NIM_CHAR data[20+1];
} TM__9cXbbi8LuWedlpH77PUxfew_120 = { 20 | NIM_STRLIT_FLAG, "nimUncheckedArrayTyp" };
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_121 = {20, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_120};
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_122 = {4, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_4};
static const struct {
  NI cap; NIM_CHAR data[12+1];
} TM__9cXbbi8LuWedlpH77PUxfew_123 = { 12 | NIM_STRLIT_FLAG, "nimHasTypeof" };
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_124 = {12, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_123};
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_125 = {4, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_4};
static const struct {
  NI cap; NIM_CHAR data[23+1];
} TM__9cXbbi8LuWedlpH77PUxfew_126 = { 23 | NIM_STRLIT_FLAG, "nimErrorProcCanHaveBody" };
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_127 = {23, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_126};
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_128 = {4, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_4};
static const struct {
  NI cap; NIM_CHAR data[28+1];
} TM__9cXbbi8LuWedlpH77PUxfew_129 = { 28 | NIM_STRLIT_FLAG, "nimHasInstantiationOfInMacro" };
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_130 = {28, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_129};
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_131 = {4, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_4};
static const struct {
  NI cap; NIM_CHAR data[22+1];
} TM__9cXbbi8LuWedlpH77PUxfew_132 = { 22 | NIM_STRLIT_FLAG, "nimHasHotCodeReloading" };
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_133 = {22, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_132};
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_134 = {4, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_4};
static const struct {
  NI cap; NIM_CHAR data[13+1];
} TM__9cXbbi8LuWedlpH77PUxfew_135 = { 13 | NIM_STRLIT_FLAG, "nimHasNilSeqs" };
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_136 = {13, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_135};
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_137 = {4, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_4};
static const struct {
  NI cap; NIM_CHAR data[26+1];
} TM__9cXbbi8LuWedlpH77PUxfew_138 = { 26 | NIM_STRLIT_FLAG, "nimHasSignatureHashInMacro" };
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_139 = {26, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_138};
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_140 = {4, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_4};
static const struct {
  NI cap; NIM_CHAR data[13+1];
} TM__9cXbbi8LuWedlpH77PUxfew_141 = { 13 | NIM_STRLIT_FLAG, "nimHasDefault" };
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_142 = {13, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_141};
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_143 = {4, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_4};
static const struct {
  NI cap; NIM_CHAR data[20+1];
} TM__9cXbbi8LuWedlpH77PUxfew_144 = { 20 | NIM_STRLIT_FLAG, "nimMacrosSizealignof" };
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_145 = {20, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_144};
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_146 = {4, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_4};
static const struct {
  NI cap; NIM_CHAR data[20+1];
} TM__9cXbbi8LuWedlpH77PUxfew_147 = { 20 | NIM_STRLIT_FLAG, "nimNoZeroExtendMagic" };
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_148 = {20, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_147};
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_149 = {4, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_4};
static const struct {
  NI cap; NIM_CHAR data[18+1];
} TM__9cXbbi8LuWedlpH77PUxfew_150 = { 18 | NIM_STRLIT_FLAG, "nimMacrosGetNodeId" };
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_151 = {18, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_150};
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_152 = {4, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_4};
static const struct {
  NI cap; NIM_CHAR data[22+1];
} TM__9cXbbi8LuWedlpH77PUxfew_153 = { 22 | NIM_STRLIT_FLAG, "nimFixedForwardGeneric" };
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_154 = {22, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_153};
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_155 = {4, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_4};
static const struct {
  NI cap; NIM_CHAR data[21+1];
} TM__9cXbbi8LuWedlpH77PUxfew_156 = { 21 | NIM_STRLIT_FLAG, "nimToOpenArrayCString" };
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_157 = {21, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_156};
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_158 = {4, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_4};
static const struct {
  NI cap; NIM_CHAR data[10+1];
} TM__9cXbbi8LuWedlpH77PUxfew_159 = { 10 | NIM_STRLIT_FLAG, "nimHasUsed" };
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_160 = {10, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_159};
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_161 = {4, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_4};
static const struct {
  NI cap; NIM_CHAR data[12+1];
} TM__9cXbbi8LuWedlpH77PUxfew_162 = { 12 | NIM_STRLIT_FLAG, "nimnomagic64" };
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_163 = {12, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_162};
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_164 = {4, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_4};
static const struct {
  NI cap; NIM_CHAR data[14+1];
} TM__9cXbbi8LuWedlpH77PUxfew_165 = { 14 | NIM_STRLIT_FLAG, "nimNewShiftOps" };
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_166 = {14, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_165};
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_167 = {4, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_4};
static const struct {
  NI cap; NIM_CHAR data[12+1];
} TM__9cXbbi8LuWedlpH77PUxfew_168 = { 12 | NIM_STRLIT_FLAG, "nimHasCursor" };
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_169 = {12, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_168};
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_170 = {4, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_4};
static const struct {
  NI cap; NIM_CHAR data[14+1];
} TM__9cXbbi8LuWedlpH77PUxfew_171 = { 14 | NIM_STRLIT_FLAG, "nimAlignPragma" };
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_172 = {14, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_171};
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_173 = {4, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_4};
static const struct {
  NI cap; NIM_CHAR data[21+1];
} TM__9cXbbi8LuWedlpH77PUxfew_174 = { 21 | NIM_STRLIT_FLAG, "nimHasExceptionsQuery" };
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_175 = {21, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_174};
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_176 = {4, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_4};
static const struct {
  NI cap; NIM_CHAR data[18+1];
} TM__9cXbbi8LuWedlpH77PUxfew_177 = { 18 | NIM_STRLIT_FLAG, "nimHasIsNamedTuple" };
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_178 = {18, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_177};
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_179 = {4, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_4};
static const struct {
  NI cap; NIM_CHAR data[19+1];
} TM__9cXbbi8LuWedlpH77PUxfew_180 = { 19 | NIM_STRLIT_FLAG, "nimHashOrdinalFixed" };
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_181 = {19, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_180};
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_182 = {4, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_4};
static const struct {
  NI cap; NIM_CHAR data[19+1];
} TM__9cXbbi8LuWedlpH77PUxfew_183 = { 19 | NIM_STRLIT_FLAG, "nimHasSinkInference" };
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_184 = {19, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_183};
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_185 = {4, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_4};
static const struct {
  NI cap; NIM_CHAR data[16+1];
} TM__9cXbbi8LuWedlpH77PUxfew_186 = { 16 | NIM_STRLIT_FLAG, "nimNewIntegerOps" };
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_187 = {16, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_186};
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_188 = {4, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_4};
static const struct {
  NI cap; NIM_CHAR data[15+1];
} TM__9cXbbi8LuWedlpH77PUxfew_189 = { 15 | NIM_STRLIT_FLAG, "nimHasInvariant" };
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_190 = {15, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_189};
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_191 = {4, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_4};
static const struct {
  NI cap; NIM_CHAR data[6+1];
} TM__9cXbbi8LuWedlpH77PUxfew_192 = { 6 | NIM_STRLIT_FLAG, "nimHas" };
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_193 = {6, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_192};
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_196 = {4, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_4};
static const struct {
  NI cap; NIM_CHAR data[13+1];
} TM__9cXbbi8LuWedlpH77PUxfew_198 = { 13 | NIM_STRLIT_FLAG, "nimHasWarning" };
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_199 = {13, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_198};
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_200 = {4, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_4};
static const struct {
  NI cap; NIM_CHAR data[10+1];
} TM__9cXbbi8LuWedlpH77PUxfew_202 = { 10 | NIM_STRLIT_FLAG, "nimHasHint" };
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_203 = {10, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_202};
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_204 = {4, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_4};
static const struct {
  NI cap; NIM_CHAR data[13+1];
} TM__9cXbbi8LuWedlpH77PUxfew_206 = { 13 | NIM_STRLIT_FLAG, "nimFixedOwned" };
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_207 = {13, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_206};
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_208 = {4, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_4};
static const struct {
  NI cap; NIM_CHAR data[17+1];
} TM__9cXbbi8LuWedlpH77PUxfew_209 = { 17 | NIM_STRLIT_FLAG, "nimHasStyleChecks" };
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_210 = {17, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_209};
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_211 = {4, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_4};
static const struct {
  NI cap; NIM_CHAR data[20+1];
} TM__9cXbbi8LuWedlpH77PUxfew_212 = { 20 | NIM_STRLIT_FLAG, "nimHasStacktraceMsgs" };
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_213 = {20, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_212};
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_214 = {4, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_4};
static const struct {
  NI cap; NIM_CHAR data[21+1];
} TM__9cXbbi8LuWedlpH77PUxfew_215 = { 21 | NIM_STRLIT_FLAG, "nimDoesntTrackDefects" };
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_216 = {21, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_215};
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_217 = {4, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_4};
static const struct {
  NI cap; NIM_CHAR data[19+1];
} TM__9cXbbi8LuWedlpH77PUxfew_218 = { 19 | NIM_STRLIT_FLAG, "nimHasLentIterators" };
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_219 = {19, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_218};
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_220 = {4, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_4};
static const struct {
  NI cap; NIM_CHAR data[19+1];
} TM__9cXbbi8LuWedlpH77PUxfew_221 = { 19 | NIM_STRLIT_FLAG, "nimHasDeclaredMagic" };
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_222 = {19, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_221};
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_223 = {4, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_4};
static const struct {
  NI cap; NIM_CHAR data[23+1];
} TM__9cXbbi8LuWedlpH77PUxfew_224 = { 23 | NIM_STRLIT_FLAG, "nimHasStacktracesModule" };
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_225 = {23, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_224};
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_226 = {4, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_4};
static const struct {
  NI cap; NIM_CHAR data[24+1];
} TM__9cXbbi8LuWedlpH77PUxfew_227 = { 24 | NIM_STRLIT_FLAG, "nimHasEffectTraitsModule" };
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_228 = {24, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_227};
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_229 = {4, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_4};
static const struct {
  NI cap; NIM_CHAR data[22+1];
} TM__9cXbbi8LuWedlpH77PUxfew_230 = { 22 | NIM_STRLIT_FLAG, "nimHasCastPragmaBlocks" };
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_231 = {22, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_230};
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_232 = {4, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_4};
static const struct {
  NI cap; NIM_CHAR data[18+1];
} TM__9cXbbi8LuWedlpH77PUxfew_233 = { 18 | NIM_STRLIT_FLAG, "nimHasDeclaredLocs" };
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_234 = {18, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_233};
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_235 = {4, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_4};
static const struct {
  NI cap; NIM_CHAR data[21+1];
} TM__9cXbbi8LuWedlpH77PUxfew_236 = { 21 | NIM_STRLIT_FLAG, "nimHasJsBigIntBackend" };
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_237 = {21, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_236};
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_238 = {4, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_4};
static const struct {
  NI cap; NIM_CHAR data[20+1];
} TM__9cXbbi8LuWedlpH77PUxfew_239 = { 20 | NIM_STRLIT_FLAG, "nimHasWarningAsError" };
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_240 = {20, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_239};
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_241 = {4, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_4};
static const struct {
  NI cap; NIM_CHAR data[17+1];
} TM__9cXbbi8LuWedlpH77PUxfew_242 = { 17 | NIM_STRLIT_FLAG, "nimHasHintAsError" };
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_243 = {17, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_242};
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_244 = {4, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_4};
static const struct {
  NI cap; NIM_CHAR data[18+1];
} TM__9cXbbi8LuWedlpH77PUxfew_245 = { 18 | NIM_STRLIT_FLAG, "nimHasSpellSuggest" };
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_246 = {18, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_245};
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_247 = {4, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_4};
static const struct {
  NI cap; NIM_CHAR data[20+1];
} TM__9cXbbi8LuWedlpH77PUxfew_248 = { 20 | NIM_STRLIT_FLAG, "nimHasCustomLiterals" };
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_249 = {20, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_248};
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_250 = {4, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_4};
static const struct {
  NI cap; NIM_CHAR data[18+1];
} TM__9cXbbi8LuWedlpH77PUxfew_251 = { 18 | NIM_STRLIT_FLAG, "nimHasUnifiedTuple" };
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_252 = {18, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_251};
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_253 = {4, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_4};
static const struct {
  NI cap; NIM_CHAR data[14+1];
} TM__9cXbbi8LuWedlpH77PUxfew_254 = { 14 | NIM_STRLIT_FLAG, "nimHasIterable" };
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_255 = {14, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_254};
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_256 = {4, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_4};
static const struct {
  NI cap; NIM_CHAR data[16+1];
} TM__9cXbbi8LuWedlpH77PUxfew_257 = { 16 | NIM_STRLIT_FLAG, "nimHasTypeofVoid" };
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_258 = {16, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_257};
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_259 = {4, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_4};
static const struct {
  NI cap; NIM_CHAR data[15+1];
} TM__9cXbbi8LuWedlpH77PUxfew_260 = { 15 | NIM_STRLIT_FLAG, "nimHasDragonBox" };
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_261 = {15, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_260};
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_262 = {4, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_4};
static const struct {
  NI cap; NIM_CHAR data[13+1];
} TM__9cXbbi8LuWedlpH77PUxfew_263 = { 13 | NIM_STRLIT_FLAG, "nimHasHintAll" };
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_264 = {13, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_263};
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_265 = {4, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_4};
static const struct {
  NI cap; NIM_CHAR data[11+1];
} TM__9cXbbi8LuWedlpH77PUxfew_266 = { 11 | NIM_STRLIT_FLAG, "nimHasTrace" };
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_267 = {11, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_266};
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_268 = {4, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_4};
static const struct {
  NI cap; NIM_CHAR data[15+1];
} TM__9cXbbi8LuWedlpH77PUxfew_269 = { 15 | NIM_STRLIT_FLAG, "nimHasEffectsOf" };
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_270 = {15, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_269};
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_271 = {4, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_4};
static const struct {
  NI cap; NIM_CHAR data[21+1];
} TM__9cXbbi8LuWedlpH77PUxfew_272 = { 21 | NIM_STRLIT_FLAG, "nimHasEnforceNoRaises" };
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_273 = {21, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_272};
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_274 = {4, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_4};
static const struct {
  NI cap; NIM_CHAR data[22+1];
} TM__9cXbbi8LuWedlpH77PUxfew_275 = { 22 | NIM_STRLIT_FLAG, "nimHasTopDownInference" };
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_276 = {22, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_275};
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_277 = {4, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_4};
static const struct {
  NI cap; NIM_CHAR data[32+1];
} TM__9cXbbi8LuWedlpH77PUxfew_278 = { 32 | NIM_STRLIT_FLAG, "nimHasTemplateRedefinitionPragma" };
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_279 = {32, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_278};
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_280 = {4, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_4};
static const struct {
  NI cap; NIM_CHAR data[17+1];
} TM__9cXbbi8LuWedlpH77PUxfew_281 = { 17 | NIM_STRLIT_FLAG, "nimHasCstringCase" };
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_282 = {17, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_281};
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_283 = {4, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_4};
static const struct {
  NI cap; NIM_CHAR data[20+1];
} TM__9cXbbi8LuWedlpH77PUxfew_284 = { 20 | NIM_STRLIT_FLAG, "nimHasCallsitePragma" };
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_285 = {20, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_284};
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_286 = {4, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_4};
static const struct {
  NI cap; NIM_CHAR data[23+1];
} TM__9cXbbi8LuWedlpH77PUxfew_287 = { 23 | NIM_STRLIT_FLAG, "nimHasAmbiguousEnumHint" };
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_288 = {23, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_287};
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_289 = {4, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_4};
static const struct {
  NI cap; NIM_CHAR data[19+1];
} TM__9cXbbi8LuWedlpH77PUxfew_290 = { 19 | NIM_STRLIT_FLAG, "nimHasWarnCastSizes" };
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_291 = {19, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_290};
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_292 = {4, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_4};
static const struct {
  NI cap; NIM_CHAR data[15+1];
} TM__9cXbbi8LuWedlpH77PUxfew_293 = { 15 | NIM_STRLIT_FLAG, "nimHasOutParams" };
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_294 = {15, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_293};
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_295 = {4, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_4};
static const struct {
  NI cap; NIM_CHAR data[24+1];
} TM__9cXbbi8LuWedlpH77PUxfew_296 = { 24 | NIM_STRLIT_FLAG, "nimHasSystemRaisesDefect" };
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_297 = {24, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_296};
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_298 = {4, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_4};
static const struct {
  NI cap; NIM_CHAR data[22+1];
} TM__9cXbbi8LuWedlpH77PUxfew_299 = { 22 | NIM_STRLIT_FLAG, "nimHasWarnUnnamedBreak" };
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_300 = {22, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_299};
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_301 = {4, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_4};
static const struct {
  NI cap; NIM_CHAR data[19+1];
} TM__9cXbbi8LuWedlpH77PUxfew_302 = { 19 | NIM_STRLIT_FLAG, "nimHasGenericDefine" };
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_303 = {19, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_302};
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_304 = {4, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_4};
static const struct {
  NI cap; NIM_CHAR data[19+1];
} TM__9cXbbi8LuWedlpH77PUxfew_305 = { 19 | NIM_STRLIT_FLAG, "nimHasDefineAliases" };
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_306 = {19, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_305};
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_307 = {4, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_4};
static const struct {
  NI cap; NIM_CHAR data[20+1];
} TM__9cXbbi8LuWedlpH77PUxfew_308 = { 20 | NIM_STRLIT_FLAG, "nimHasWarnBareExcept" };
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_309 = {20, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_308};
static const NimStringV2 TM__9cXbbi8LuWedlpH77PUxfew_310 = {4, (NimStrPayload*)&TM__9cXbbi8LuWedlpH77PUxfew_4};
extern NIM_BOOL nimInErrorMode__system_u4097;
extern TFrame* framePtr__system_u3743;
extern TFrame* framePtr__system_u3743;
extern TFrame* framePtr__system_u3743;
extern TFrame* framePtr__system_u3743;
extern TFrame* framePtr__system_u3743;
extern TFrame* framePtr__system_u3743;
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (NIM_BOOL*)0;
	result = (&nimInErrorMode__system_u4097);
	return result;
}
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u3743 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u3743).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u3743;
	framePtr__system_u3743 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4294();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u3743 = (*framePtr__system_u3743).prev;
}
N_LIB_PRIVATE N_NIMCALL(void, defineSymbol__condsyms_u4)(tyObject_StringTableObj__eQlzBfCID7uSzbD7mP9cuYw* symbols_p0, NimStringV2 symbol_p1, NimStringV2 value_p2) {
NIM_BOOL* nimErr_;
	nimfr_("defineSymbol", "D:\\nim\\compiler\\condsyms.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(19, "D:\\nim\\compiler\\condsyms.nim");
	nstPut(symbols_p0, symbol_p1, value_p2);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, undefSymbol__condsyms_u8)(tyObject_StringTableObj__eQlzBfCID7uSzbD7mP9cuYw* symbols_p0, NimStringV2 symbol_p1) {
NIM_BOOL* nimErr_;
	nimfr_("undefSymbol", "D:\\nim\\compiler\\condsyms.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(22, "D:\\nim\\compiler\\condsyms.nim");
	del__pureZstrtabs_u591(symbols_p0, symbol_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
BeforeRet_: ;
	popFrame();
}
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__system_u1720)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1) {
{	{
		NI TM__9cXbbi8LuWedlpH77PUxfew_194;
		NI TM__9cXbbi8LuWedlpH77PUxfew_195;
		if (!(((NI)0) < src_p1.len)) goto LA3_;
		if (nimAddInt(src_p1.len, ((NI)1), &TM__9cXbbi8LuWedlpH77PUxfew_194)) { raiseOverflow(); goto BeforeRet_;
		};
		if (((NI)(TM__9cXbbi8LuWedlpH77PUxfew_194)) < ((NI)0) || ((NI)(TM__9cXbbi8LuWedlpH77PUxfew_194)) > ((NI)2147483647)){ raiseRangeErrorI((NI)(TM__9cXbbi8LuWedlpH77PUxfew_194), ((NI)0), ((NI)2147483647)); goto BeforeRet_;
		}
		copyMem__system_u1720(((void*) ((&(*(*dest_p0).p).data[(*dest_p0).len]))), ((void*) ((&(*src_p1.p).data[((NI)0)]))), ((NI) ((NI)(TM__9cXbbi8LuWedlpH77PUxfew_194))));
		if (nimAddInt((*dest_p0).len, src_p1.len, &TM__9cXbbi8LuWedlpH77PUxfew_195)) { raiseOverflow(); goto BeforeRet_;
		};
		(*dest_p0).len = (NI)(TM__9cXbbi8LuWedlpH77PUxfew_195);
	}
LA3_: ;
	}
BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, initDefines__condsyms_u17)(tyObject_StringTableObj__eQlzBfCID7uSzbD7mP9cuYw* symbols_p0) {
NIM_BOOL* nimErr_;
	nimfr_("initDefines", "D:\\nim\\compiler\\condsyms.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(37, "D:\\nim\\compiler\\condsyms.nim");
	defineSymbol__condsyms_u4(symbols_p0, TM__9cXbbi8LuWedlpH77PUxfew_3, TM__9cXbbi8LuWedlpH77PUxfew_5);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(38);
	defineSymbol__condsyms_u4(symbols_p0, TM__9cXbbi8LuWedlpH77PUxfew_7, TM__9cXbbi8LuWedlpH77PUxfew_8);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(39);
	defineSymbol__condsyms_u4(symbols_p0, TM__9cXbbi8LuWedlpH77PUxfew_10, TM__9cXbbi8LuWedlpH77PUxfew_11);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(40);
	defineSymbol__condsyms_u4(symbols_p0, TM__9cXbbi8LuWedlpH77PUxfew_13, TM__9cXbbi8LuWedlpH77PUxfew_14);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(41);
	defineSymbol__condsyms_u4(symbols_p0, TM__9cXbbi8LuWedlpH77PUxfew_16, TM__9cXbbi8LuWedlpH77PUxfew_17);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(42);
	defineSymbol__condsyms_u4(symbols_p0, TM__9cXbbi8LuWedlpH77PUxfew_19, TM__9cXbbi8LuWedlpH77PUxfew_20);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(43);
	defineSymbol__condsyms_u4(symbols_p0, TM__9cXbbi8LuWedlpH77PUxfew_22, TM__9cXbbi8LuWedlpH77PUxfew_23);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(44);
	defineSymbol__condsyms_u4(symbols_p0, TM__9cXbbi8LuWedlpH77PUxfew_25, TM__9cXbbi8LuWedlpH77PUxfew_26);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(45);
	defineSymbol__condsyms_u4(symbols_p0, TM__9cXbbi8LuWedlpH77PUxfew_28, TM__9cXbbi8LuWedlpH77PUxfew_29);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(46);
	defineSymbol__condsyms_u4(symbols_p0, TM__9cXbbi8LuWedlpH77PUxfew_31, TM__9cXbbi8LuWedlpH77PUxfew_32);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(47);
	defineSymbol__condsyms_u4(symbols_p0, TM__9cXbbi8LuWedlpH77PUxfew_34, TM__9cXbbi8LuWedlpH77PUxfew_35);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(48);
	defineSymbol__condsyms_u4(symbols_p0, TM__9cXbbi8LuWedlpH77PUxfew_37, TM__9cXbbi8LuWedlpH77PUxfew_38);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(49);
	defineSymbol__condsyms_u4(symbols_p0, TM__9cXbbi8LuWedlpH77PUxfew_40, TM__9cXbbi8LuWedlpH77PUxfew_41);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(50);
	defineSymbol__condsyms_u4(symbols_p0, TM__9cXbbi8LuWedlpH77PUxfew_43, TM__9cXbbi8LuWedlpH77PUxfew_44);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(52);
	defineSymbol__condsyms_u4(symbols_p0, TM__9cXbbi8LuWedlpH77PUxfew_46, TM__9cXbbi8LuWedlpH77PUxfew_47);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(53);
	defineSymbol__condsyms_u4(symbols_p0, TM__9cXbbi8LuWedlpH77PUxfew_49, TM__9cXbbi8LuWedlpH77PUxfew_50);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(54);
	defineSymbol__condsyms_u4(symbols_p0, TM__9cXbbi8LuWedlpH77PUxfew_52, TM__9cXbbi8LuWedlpH77PUxfew_53);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(55);
	defineSymbol__condsyms_u4(symbols_p0, TM__9cXbbi8LuWedlpH77PUxfew_55, TM__9cXbbi8LuWedlpH77PUxfew_56);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(56);
	defineSymbol__condsyms_u4(symbols_p0, TM__9cXbbi8LuWedlpH77PUxfew_58, TM__9cXbbi8LuWedlpH77PUxfew_59);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(57);
	defineSymbol__condsyms_u4(symbols_p0, TM__9cXbbi8LuWedlpH77PUxfew_61, TM__9cXbbi8LuWedlpH77PUxfew_62);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(58);
	defineSymbol__condsyms_u4(symbols_p0, TM__9cXbbi8LuWedlpH77PUxfew_64, TM__9cXbbi8LuWedlpH77PUxfew_65);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(59);
	defineSymbol__condsyms_u4(symbols_p0, TM__9cXbbi8LuWedlpH77PUxfew_67, TM__9cXbbi8LuWedlpH77PUxfew_68);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(61);
	defineSymbol__condsyms_u4(symbols_p0, TM__9cXbbi8LuWedlpH77PUxfew_70, TM__9cXbbi8LuWedlpH77PUxfew_71);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(62);
	defineSymbol__condsyms_u4(symbols_p0, TM__9cXbbi8LuWedlpH77PUxfew_73, TM__9cXbbi8LuWedlpH77PUxfew_74);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(63);
	defineSymbol__condsyms_u4(symbols_p0, TM__9cXbbi8LuWedlpH77PUxfew_76, TM__9cXbbi8LuWedlpH77PUxfew_77);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(64);
	defineSymbol__condsyms_u4(symbols_p0, TM__9cXbbi8LuWedlpH77PUxfew_79, TM__9cXbbi8LuWedlpH77PUxfew_80);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(65);
	defineSymbol__condsyms_u4(symbols_p0, TM__9cXbbi8LuWedlpH77PUxfew_82, TM__9cXbbi8LuWedlpH77PUxfew_83);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(66);
	defineSymbol__condsyms_u4(symbols_p0, TM__9cXbbi8LuWedlpH77PUxfew_85, TM__9cXbbi8LuWedlpH77PUxfew_86);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(67);
	defineSymbol__condsyms_u4(symbols_p0, TM__9cXbbi8LuWedlpH77PUxfew_88, TM__9cXbbi8LuWedlpH77PUxfew_89);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(68);
	defineSymbol__condsyms_u4(symbols_p0, TM__9cXbbi8LuWedlpH77PUxfew_91, TM__9cXbbi8LuWedlpH77PUxfew_92);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(69);
	defineSymbol__condsyms_u4(symbols_p0, TM__9cXbbi8LuWedlpH77PUxfew_94, TM__9cXbbi8LuWedlpH77PUxfew_95);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(70);
	defineSymbol__condsyms_u4(symbols_p0, TM__9cXbbi8LuWedlpH77PUxfew_97, TM__9cXbbi8LuWedlpH77PUxfew_98);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(71);
	defineSymbol__condsyms_u4(symbols_p0, TM__9cXbbi8LuWedlpH77PUxfew_100, TM__9cXbbi8LuWedlpH77PUxfew_101);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(72);
	defineSymbol__condsyms_u4(symbols_p0, TM__9cXbbi8LuWedlpH77PUxfew_103, TM__9cXbbi8LuWedlpH77PUxfew_104);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(73);
	defineSymbol__condsyms_u4(symbols_p0, TM__9cXbbi8LuWedlpH77PUxfew_106, TM__9cXbbi8LuWedlpH77PUxfew_107);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(74);
	defineSymbol__condsyms_u4(symbols_p0, TM__9cXbbi8LuWedlpH77PUxfew_109, TM__9cXbbi8LuWedlpH77PUxfew_110);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(75);
	defineSymbol__condsyms_u4(symbols_p0, TM__9cXbbi8LuWedlpH77PUxfew_112, TM__9cXbbi8LuWedlpH77PUxfew_113);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(76);
	defineSymbol__condsyms_u4(symbols_p0, TM__9cXbbi8LuWedlpH77PUxfew_115, TM__9cXbbi8LuWedlpH77PUxfew_116);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(77);
	defineSymbol__condsyms_u4(symbols_p0, TM__9cXbbi8LuWedlpH77PUxfew_118, TM__9cXbbi8LuWedlpH77PUxfew_119);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(78);
	defineSymbol__condsyms_u4(symbols_p0, TM__9cXbbi8LuWedlpH77PUxfew_121, TM__9cXbbi8LuWedlpH77PUxfew_122);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(79);
	defineSymbol__condsyms_u4(symbols_p0, TM__9cXbbi8LuWedlpH77PUxfew_124, TM__9cXbbi8LuWedlpH77PUxfew_125);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(80);
	defineSymbol__condsyms_u4(symbols_p0, TM__9cXbbi8LuWedlpH77PUxfew_127, TM__9cXbbi8LuWedlpH77PUxfew_128);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(81);
	defineSymbol__condsyms_u4(symbols_p0, TM__9cXbbi8LuWedlpH77PUxfew_130, TM__9cXbbi8LuWedlpH77PUxfew_131);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(82);
	defineSymbol__condsyms_u4(symbols_p0, TM__9cXbbi8LuWedlpH77PUxfew_133, TM__9cXbbi8LuWedlpH77PUxfew_134);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(83);
	defineSymbol__condsyms_u4(symbols_p0, TM__9cXbbi8LuWedlpH77PUxfew_136, TM__9cXbbi8LuWedlpH77PUxfew_137);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(84);
	defineSymbol__condsyms_u4(symbols_p0, TM__9cXbbi8LuWedlpH77PUxfew_139, TM__9cXbbi8LuWedlpH77PUxfew_140);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(85);
	defineSymbol__condsyms_u4(symbols_p0, TM__9cXbbi8LuWedlpH77PUxfew_142, TM__9cXbbi8LuWedlpH77PUxfew_143);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(86);
	defineSymbol__condsyms_u4(symbols_p0, TM__9cXbbi8LuWedlpH77PUxfew_145, TM__9cXbbi8LuWedlpH77PUxfew_146);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(87);
	defineSymbol__condsyms_u4(symbols_p0, TM__9cXbbi8LuWedlpH77PUxfew_148, TM__9cXbbi8LuWedlpH77PUxfew_149);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(88);
	defineSymbol__condsyms_u4(symbols_p0, TM__9cXbbi8LuWedlpH77PUxfew_151, TM__9cXbbi8LuWedlpH77PUxfew_152);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(89);
	defineSymbol__condsyms_u4(symbols_p0, TM__9cXbbi8LuWedlpH77PUxfew_154, TM__9cXbbi8LuWedlpH77PUxfew_155);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(90);
	defineSymbol__condsyms_u4(symbols_p0, TM__9cXbbi8LuWedlpH77PUxfew_157, TM__9cXbbi8LuWedlpH77PUxfew_158);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(91);
	defineSymbol__condsyms_u4(symbols_p0, TM__9cXbbi8LuWedlpH77PUxfew_160, TM__9cXbbi8LuWedlpH77PUxfew_161);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(92);
	defineSymbol__condsyms_u4(symbols_p0, TM__9cXbbi8LuWedlpH77PUxfew_163, TM__9cXbbi8LuWedlpH77PUxfew_164);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(93);
	defineSymbol__condsyms_u4(symbols_p0, TM__9cXbbi8LuWedlpH77PUxfew_166, TM__9cXbbi8LuWedlpH77PUxfew_167);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(94);
	defineSymbol__condsyms_u4(symbols_p0, TM__9cXbbi8LuWedlpH77PUxfew_169, TM__9cXbbi8LuWedlpH77PUxfew_170);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(95);
	defineSymbol__condsyms_u4(symbols_p0, TM__9cXbbi8LuWedlpH77PUxfew_172, TM__9cXbbi8LuWedlpH77PUxfew_173);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(96);
	defineSymbol__condsyms_u4(symbols_p0, TM__9cXbbi8LuWedlpH77PUxfew_175, TM__9cXbbi8LuWedlpH77PUxfew_176);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(97);
	defineSymbol__condsyms_u4(symbols_p0, TM__9cXbbi8LuWedlpH77PUxfew_178, TM__9cXbbi8LuWedlpH77PUxfew_179);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(98);
	defineSymbol__condsyms_u4(symbols_p0, TM__9cXbbi8LuWedlpH77PUxfew_181, TM__9cXbbi8LuWedlpH77PUxfew_182);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(99);
	defineSymbol__condsyms_u4(symbols_p0, TM__9cXbbi8LuWedlpH77PUxfew_184, TM__9cXbbi8LuWedlpH77PUxfew_185);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(100);
	defineSymbol__condsyms_u4(symbols_p0, TM__9cXbbi8LuWedlpH77PUxfew_187, TM__9cXbbi8LuWedlpH77PUxfew_188);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(101);
	defineSymbol__condsyms_u4(symbols_p0, TM__9cXbbi8LuWedlpH77PUxfew_190, TM__9cXbbi8LuWedlpH77PUxfew_191);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		tyEnum_Feature__M3s7Uywm9c5BlzNIKwZFu3g f;
		f = (tyEnum_Feature__M3s7Uywm9c5BlzNIKwZFu3g)0;
		{
			tyEnum_Feature__M3s7Uywm9c5BlzNIKwZFu3g v;
			NI res;
			v = (tyEnum_Feature__M3s7Uywm9c5BlzNIKwZFu3g)0;
			nimlf_(90, "D:\\nim\\lib\\system\\iterators_1.nim");
			res = ((NI)0);
			{
				nimln_(91);
				while (1) {
					NimStringV2 colontmpD_;
					NimStringV2 colontmpD__2;
					NimStringV2 T5_;
					NI TM__9cXbbi8LuWedlpH77PUxfew_197;
					if (!(res <= ((NI)19))) goto LA4;
					colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
					colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
					nimlf_(129, "D:\\nim\\lib\\system\\iterators.nim");
					if ((res) < ((tyEnum_Feature__M3s7Uywm9c5BlzNIKwZFu3g)0) || (res) > ((tyEnum_Feature__M3s7Uywm9c5BlzNIKwZFu3g)19)){ raiseRangeErrorI(res, ((tyEnum_Feature__M3s7Uywm9c5BlzNIKwZFu3g)0), ((tyEnum_Feature__M3s7Uywm9c5BlzNIKwZFu3g)19)); goto BeforeRet_;
					}
					v = ((tyEnum_Feature__M3s7Uywm9c5BlzNIKwZFu3g) (res));
					nimlf_(105, "D:\\nim\\compiler\\condsyms.nim");
					f = v;
					T5_.len = 0; T5_.p = NIM_NIL;
					nimln_(106);
					colontmpD_ = dollar___options_u255(f);
					T5_ = rawNewString(colontmpD_.len + 6);
appendString((&T5_), TM__9cXbbi8LuWedlpH77PUxfew_193);
appendString((&T5_), colontmpD_);
					colontmpD__2 = T5_;
					nimln_(105);
					defineSymbol__condsyms_u4(symbols_p0, colontmpD__2, TM__9cXbbi8LuWedlpH77PUxfew_196);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					nimlf_(93, "D:\\nim\\lib\\system\\iterators_1.nim");
					if (nimAddInt(res, ((NI)1), &TM__9cXbbi8LuWedlpH77PUxfew_197)) { raiseOverflow(); goto BeforeRet_;
					};
					res = (NI)(TM__9cXbbi8LuWedlpH77PUxfew_197);
					nimlf_(25, "D:\\nim\\lib\\std\\assertions.nim");
					eqdestroy___stdZassertions_u16((&colontmpD__2));
					eqdestroy___stdZassertions_u16((&colontmpD_));
				} LA4: ;
			}
		}
	}
	{
		tyEnum_TMsgKind__aghsq7zHWm205GRPJE9a2yw s;
		NI res_2;
		s = (tyEnum_TMsgKind__aghsq7zHWm205GRPJE9a2yw)0;
		nimlf_(90, "D:\\nim\\lib\\system\\iterators_1.nim");
		res_2 = ((NI)19);
		{
			nimln_(91);
			while (1) {
				NimStringV2 colontmpD__3;
				NimStringV2 colontmpD__4;
				NimStringV2 T9_;
				NI TM__9cXbbi8LuWedlpH77PUxfew_201;
				if (!(res_2 <= ((NI)80))) goto LA8;
				colontmpD__3.len = 0; colontmpD__3.p = NIM_NIL;
				colontmpD__4.len = 0; colontmpD__4.p = NIM_NIL;
				nimlf_(108, "D:\\nim\\compiler\\condsyms.nim");
				if ((res_2) < ((tyEnum_TMsgKind__aghsq7zHWm205GRPJE9a2yw)0) || (res_2) > ((tyEnum_TMsgKind__aghsq7zHWm205GRPJE9a2yw)116)){ raiseRangeErrorI(res_2, ((tyEnum_TMsgKind__aghsq7zHWm205GRPJE9a2yw)0), ((tyEnum_TMsgKind__aghsq7zHWm205GRPJE9a2yw)116)); goto BeforeRet_;
				}
				s = ((tyEnum_TMsgKind__aghsq7zHWm205GRPJE9a2yw) (res_2));
				T9_.len = 0; T9_.p = NIM_NIL;
				nimln_(109);
				colontmpD__3 = dollar___lineinfos_u127(s);
				T9_ = rawNewString(colontmpD__3.len + 13);
appendString((&T9_), TM__9cXbbi8LuWedlpH77PUxfew_199);
appendString((&T9_), colontmpD__3);
				colontmpD__4 = T9_;
				nimln_(108);
				defineSymbol__condsyms_u4(symbols_p0, colontmpD__4, TM__9cXbbi8LuWedlpH77PUxfew_200);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				nimlf_(93, "D:\\nim\\lib\\system\\iterators_1.nim");
				if (nimAddInt(res_2, ((NI)1), &TM__9cXbbi8LuWedlpH77PUxfew_201)) { raiseOverflow(); goto BeforeRet_;
				};
				res_2 = (NI)(TM__9cXbbi8LuWedlpH77PUxfew_201);
				nimlf_(25, "D:\\nim\\lib\\std\\assertions.nim");
				eqdestroy___stdZassertions_u16((&colontmpD__4));
				eqdestroy___stdZassertions_u16((&colontmpD__3));
			} LA8: ;
		}
	}
	{
		tyEnum_TMsgKind__aghsq7zHWm205GRPJE9a2yw s_2;
		NI res_3;
		s_2 = (tyEnum_TMsgKind__aghsq7zHWm205GRPJE9a2yw)0;
		nimlf_(90, "D:\\nim\\lib\\system\\iterators_1.nim");
		res_3 = ((NI)81);
		{
			nimln_(91);
			while (1) {
				NimStringV2 colontmpD__5;
				NimStringV2 colontmpD__6;
				NimStringV2 T13_;
				NI TM__9cXbbi8LuWedlpH77PUxfew_205;
				if (!(res_3 <= ((NI)116))) goto LA12;
				colontmpD__5.len = 0; colontmpD__5.p = NIM_NIL;
				colontmpD__6.len = 0; colontmpD__6.p = NIM_NIL;
				nimlf_(110, "D:\\nim\\compiler\\condsyms.nim");
				if ((res_3) < ((tyEnum_TMsgKind__aghsq7zHWm205GRPJE9a2yw)0) || (res_3) > ((tyEnum_TMsgKind__aghsq7zHWm205GRPJE9a2yw)116)){ raiseRangeErrorI(res_3, ((tyEnum_TMsgKind__aghsq7zHWm205GRPJE9a2yw)0), ((tyEnum_TMsgKind__aghsq7zHWm205GRPJE9a2yw)116)); goto BeforeRet_;
				}
				s_2 = ((tyEnum_TMsgKind__aghsq7zHWm205GRPJE9a2yw) (res_3));
				T13_.len = 0; T13_.p = NIM_NIL;
				nimln_(111);
				colontmpD__5 = dollar___lineinfos_u127(s_2);
				T13_ = rawNewString(colontmpD__5.len + 10);
appendString((&T13_), TM__9cXbbi8LuWedlpH77PUxfew_203);
appendString((&T13_), colontmpD__5);
				colontmpD__6 = T13_;
				nimln_(110);
				defineSymbol__condsyms_u4(symbols_p0, colontmpD__6, TM__9cXbbi8LuWedlpH77PUxfew_204);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				nimlf_(93, "D:\\nim\\lib\\system\\iterators_1.nim");
				if (nimAddInt(res_3, ((NI)1), &TM__9cXbbi8LuWedlpH77PUxfew_205)) { raiseOverflow(); goto BeforeRet_;
				};
				res_3 = (NI)(TM__9cXbbi8LuWedlpH77PUxfew_205);
				nimlf_(25, "D:\\nim\\lib\\std\\assertions.nim");
				eqdestroy___stdZassertions_u16((&colontmpD__6));
				eqdestroy___stdZassertions_u16((&colontmpD__5));
			} LA12: ;
		}
	}
	nimlf_(113, "D:\\nim\\compiler\\condsyms.nim");
	defineSymbol__condsyms_u4(symbols_p0, TM__9cXbbi8LuWedlpH77PUxfew_207, TM__9cXbbi8LuWedlpH77PUxfew_208);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(114);
	defineSymbol__condsyms_u4(symbols_p0, TM__9cXbbi8LuWedlpH77PUxfew_210, TM__9cXbbi8LuWedlpH77PUxfew_211);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(122);
	defineSymbol__condsyms_u4(symbols_p0, TM__9cXbbi8LuWedlpH77PUxfew_213, TM__9cXbbi8LuWedlpH77PUxfew_214);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(123);
	defineSymbol__condsyms_u4(symbols_p0, TM__9cXbbi8LuWedlpH77PUxfew_216, TM__9cXbbi8LuWedlpH77PUxfew_217);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(124);
	defineSymbol__condsyms_u4(symbols_p0, TM__9cXbbi8LuWedlpH77PUxfew_219, TM__9cXbbi8LuWedlpH77PUxfew_220);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(125);
	defineSymbol__condsyms_u4(symbols_p0, TM__9cXbbi8LuWedlpH77PUxfew_222, TM__9cXbbi8LuWedlpH77PUxfew_223);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(126);
	defineSymbol__condsyms_u4(symbols_p0, TM__9cXbbi8LuWedlpH77PUxfew_225, TM__9cXbbi8LuWedlpH77PUxfew_226);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(127);
	defineSymbol__condsyms_u4(symbols_p0, TM__9cXbbi8LuWedlpH77PUxfew_228, TM__9cXbbi8LuWedlpH77PUxfew_229);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(128);
	defineSymbol__condsyms_u4(symbols_p0, TM__9cXbbi8LuWedlpH77PUxfew_231, TM__9cXbbi8LuWedlpH77PUxfew_232);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(129);
	defineSymbol__condsyms_u4(symbols_p0, TM__9cXbbi8LuWedlpH77PUxfew_234, TM__9cXbbi8LuWedlpH77PUxfew_235);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(130);
	defineSymbol__condsyms_u4(symbols_p0, TM__9cXbbi8LuWedlpH77PUxfew_237, TM__9cXbbi8LuWedlpH77PUxfew_238);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(131);
	defineSymbol__condsyms_u4(symbols_p0, TM__9cXbbi8LuWedlpH77PUxfew_240, TM__9cXbbi8LuWedlpH77PUxfew_241);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(132);
	defineSymbol__condsyms_u4(symbols_p0, TM__9cXbbi8LuWedlpH77PUxfew_243, TM__9cXbbi8LuWedlpH77PUxfew_244);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(133);
	defineSymbol__condsyms_u4(symbols_p0, TM__9cXbbi8LuWedlpH77PUxfew_246, TM__9cXbbi8LuWedlpH77PUxfew_247);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(134);
	defineSymbol__condsyms_u4(symbols_p0, TM__9cXbbi8LuWedlpH77PUxfew_249, TM__9cXbbi8LuWedlpH77PUxfew_250);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(135);
	defineSymbol__condsyms_u4(symbols_p0, TM__9cXbbi8LuWedlpH77PUxfew_252, TM__9cXbbi8LuWedlpH77PUxfew_253);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(136);
	defineSymbol__condsyms_u4(symbols_p0, TM__9cXbbi8LuWedlpH77PUxfew_255, TM__9cXbbi8LuWedlpH77PUxfew_256);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(137);
	defineSymbol__condsyms_u4(symbols_p0, TM__9cXbbi8LuWedlpH77PUxfew_258, TM__9cXbbi8LuWedlpH77PUxfew_259);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(138);
	defineSymbol__condsyms_u4(symbols_p0, TM__9cXbbi8LuWedlpH77PUxfew_261, TM__9cXbbi8LuWedlpH77PUxfew_262);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(139);
	defineSymbol__condsyms_u4(symbols_p0, TM__9cXbbi8LuWedlpH77PUxfew_264, TM__9cXbbi8LuWedlpH77PUxfew_265);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(140);
	defineSymbol__condsyms_u4(symbols_p0, TM__9cXbbi8LuWedlpH77PUxfew_267, TM__9cXbbi8LuWedlpH77PUxfew_268);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(141);
	defineSymbol__condsyms_u4(symbols_p0, TM__9cXbbi8LuWedlpH77PUxfew_270, TM__9cXbbi8LuWedlpH77PUxfew_271);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(143);
	defineSymbol__condsyms_u4(symbols_p0, TM__9cXbbi8LuWedlpH77PUxfew_273, TM__9cXbbi8LuWedlpH77PUxfew_274);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(144);
	defineSymbol__condsyms_u4(symbols_p0, TM__9cXbbi8LuWedlpH77PUxfew_276, TM__9cXbbi8LuWedlpH77PUxfew_277);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(145);
	defineSymbol__condsyms_u4(symbols_p0, TM__9cXbbi8LuWedlpH77PUxfew_279, TM__9cXbbi8LuWedlpH77PUxfew_280);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(146);
	defineSymbol__condsyms_u4(symbols_p0, TM__9cXbbi8LuWedlpH77PUxfew_282, TM__9cXbbi8LuWedlpH77PUxfew_283);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(147);
	defineSymbol__condsyms_u4(symbols_p0, TM__9cXbbi8LuWedlpH77PUxfew_285, TM__9cXbbi8LuWedlpH77PUxfew_286);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(148);
	defineSymbol__condsyms_u4(symbols_p0, TM__9cXbbi8LuWedlpH77PUxfew_288, TM__9cXbbi8LuWedlpH77PUxfew_289);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(150);
	defineSymbol__condsyms_u4(symbols_p0, TM__9cXbbi8LuWedlpH77PUxfew_291, TM__9cXbbi8LuWedlpH77PUxfew_292);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(151);
	defineSymbol__condsyms_u4(symbols_p0, TM__9cXbbi8LuWedlpH77PUxfew_294, TM__9cXbbi8LuWedlpH77PUxfew_295);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(152);
	defineSymbol__condsyms_u4(symbols_p0, TM__9cXbbi8LuWedlpH77PUxfew_297, TM__9cXbbi8LuWedlpH77PUxfew_298);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(153);
	defineSymbol__condsyms_u4(symbols_p0, TM__9cXbbi8LuWedlpH77PUxfew_300, TM__9cXbbi8LuWedlpH77PUxfew_301);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(154);
	defineSymbol__condsyms_u4(symbols_p0, TM__9cXbbi8LuWedlpH77PUxfew_303, TM__9cXbbi8LuWedlpH77PUxfew_304);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(155);
	defineSymbol__condsyms_u4(symbols_p0, TM__9cXbbi8LuWedlpH77PUxfew_306, TM__9cXbbi8LuWedlpH77PUxfew_307);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(156);
	defineSymbol__condsyms_u4(symbols_p0, TM__9cXbbi8LuWedlpH77PUxfew_309, TM__9cXbbi8LuWedlpH77PUxfew_310);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
BeforeRet_: ;
	popFrame();
}
