/* Generated by Nim Compiler v1.9.3 */
#define NIM_INTBITS 32

#include "nimbase.h"
#include <stdio.h>
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #define nimfrs_(proc, file, slots, length) \
    struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename;NI len;VarSlot s[slots];} FR_; \
    FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #define nimln_(n) \
    FR_.line = n;

  #define nimlf_(n, file) \
    FR_.line = n; FR_.filename = file;

typedef struct tyObject_StreamObj__YejCBqGiUpphaYVvxhpLOQ tyObject_StreamObj__YejCBqGiUpphaYVvxhpLOQ;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct RootObj RootObj;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tyObject_HSlice__Ft7fsi5uCTryLqJGssT0Jw tyObject_HSlice__Ft7fsi5uCTryLqJGssT0Jw;
typedef struct tyObject_RefHeader__b9cZ5ThQEAqSv7VLAQu0wEw tyObject_RefHeader__b9cZ5ThQEAqSv7VLAQu0wEw;
typedef struct tyObject_FileStreamObj__3EaLUqxHvhPMY9a0V1oV9aPQ tyObject_FileStreamObj__3EaLUqxHvhPMY9a0V1oV9aPQ;
typedef struct tyObject_IOError__Vy6h1gTZNMhIMVGxEYGYlg tyObject_IOError__Vy6h1gTZNMhIMVGxEYGYlg;
typedef struct tyObject_CatchableError__gR37KDrjbfwtwdSWyHspqA tyObject_CatchableError__gR37KDrjbfwtwdSWyHspqA;
typedef struct Exception Exception;
typedef struct tySequence__OC4OxQhfzCBuUQxMi5llBQ tySequence__OC4OxQhfzCBuUQxMi5llBQ;
typedef struct tySequence__OC4OxQhfzCBuUQxMi5llBQ_Content tySequence__OC4OxQhfzCBuUQxMi5llBQ_Content;
typedef struct tyObject_StringStreamObj__Varqg7Zqtz8r284IHsIK5A tyObject_StringStreamObj__Varqg7Zqtz8r284IHsIK5A;
typedef struct tyObject_StackTraceEntry__cwz3X1atIa8ET8VanDA2pw tyObject_StackTraceEntry__cwz3X1atIa8ET8VanDA2pw;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
};
struct RootObj {
TNimTypeV2* m_type;
};
typedef N_NIMCALL_PTR(void, tyProc__KtdQJPZ5vkTySfa0kiietg) (tyObject_StreamObj__YejCBqGiUpphaYVvxhpLOQ* s_p0);
typedef N_NIMCALL_PTR(NIM_BOOL, tyProc__wLy7X6AzUmW632phG1ImIg) (tyObject_StreamObj__YejCBqGiUpphaYVvxhpLOQ* s_p0);
typedef N_NIMCALL_PTR(void, tyProc__HK8chayPRiFbuhu4sRRv7g) (tyObject_StreamObj__YejCBqGiUpphaYVvxhpLOQ* s_p0, NI pos_p1);
typedef N_NIMCALL_PTR(NI, tyProc__QQHc9aYLDyAfqF9b6t1H27WA) (tyObject_StreamObj__YejCBqGiUpphaYVvxhpLOQ* s_p0);
typedef N_NIMCALL_PTR(NI, tyProc__XiQAchrYy3u7KhulcHbmLg) (tyObject_StreamObj__YejCBqGiUpphaYVvxhpLOQ* s_p0, NimStringV2* buffer_p1, tyObject_HSlice__Ft7fsi5uCTryLqJGssT0Jw slice_p2);
typedef N_NIMCALL_PTR(NIM_BOOL, tyProc__DP17vAZ3FcEvbk4geIuBwA) (tyObject_StreamObj__YejCBqGiUpphaYVvxhpLOQ* s_p0, NimStringV2* line_p1);
typedef N_NIMCALL_PTR(NI, tyProc__Ityxqkz9bQW9c2D0d9bhFb5wA) (tyObject_StreamObj__YejCBqGiUpphaYVvxhpLOQ* s_p0, void* buffer_p1, NI bufLen_p2);
typedef N_NIMCALL_PTR(void, tyProc__3RcaB8PpiiAQU8HYkI7ZcA) (tyObject_StreamObj__YejCBqGiUpphaYVvxhpLOQ* s_p0, void* buffer_p1, NI bufLen_p2);
struct tyObject_StreamObj__YejCBqGiUpphaYVvxhpLOQ {
  RootObj Sup;
	tyProc__KtdQJPZ5vkTySfa0kiietg closeImpl;
	tyProc__wLy7X6AzUmW632phG1ImIg atEndImpl;
	tyProc__HK8chayPRiFbuhu4sRRv7g setPositionImpl;
	tyProc__QQHc9aYLDyAfqF9b6t1H27WA getPositionImpl;
	tyProc__XiQAchrYy3u7KhulcHbmLg readDataStrImpl;
	tyProc__DP17vAZ3FcEvbk4geIuBwA readLineImpl;
	tyProc__Ityxqkz9bQW9c2D0d9bhFb5wA readDataImpl;
	tyProc__Ityxqkz9bQW9c2D0d9bhFb5wA peekDataImpl;
	tyProc__3RcaB8PpiiAQU8HYkI7ZcA writeDataImpl;
	tyProc__KtdQJPZ5vkTySfa0kiietg flushImpl;
};
struct tyObject_RefHeader__b9cZ5ThQEAqSv7VLAQu0wEw {
	NI rc;
	NI rootIdx;
};
struct tyObject_FileStreamObj__3EaLUqxHvhPMY9a0V1oV9aPQ {
  tyObject_StreamObj__YejCBqGiUpphaYVvxhpLOQ Sup;
	FILE* f;
};
typedef NU8 tyEnum_FileSeekPos__64uV49bBMhJtiSJHjCdTuzg;
struct tyObject_HSlice__Ft7fsi5uCTryLqJGssT0Jw {
	NI a;
	NI b;
};
struct tySequence__OC4OxQhfzCBuUQxMi5llBQ {
  NI len; tySequence__OC4OxQhfzCBuUQxMi5llBQ_Content* p;
};
struct Exception {
  RootObj Sup;
	Exception* parent;
	NCSTRING name;
	NimStringV2 message;
	tySequence__OC4OxQhfzCBuUQxMi5llBQ trace;
	Exception* up;
};
struct tyObject_CatchableError__gR37KDrjbfwtwdSWyHspqA {
  Exception Sup;
};
struct tyObject_IOError__Vy6h1gTZNMhIMVGxEYGYlg {
  tyObject_CatchableError__gR37KDrjbfwtwdSWyHspqA Sup;
};
struct tyObject_StringStreamObj__Varqg7Zqtz8r284IHsIK5A {
  tyObject_StreamObj__YejCBqGiUpphaYVvxhpLOQ Sup;
	NimStringV2 data;
	NI pos;
};
typedef NU8 tyEnum_FileMode__9atfYUlw9bQtL4ixYGhUZZfQ;
struct tyObject_StackTraceEntry__cwz3X1atIa8ET8VanDA2pw {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};


#ifndef tySequence__OC4OxQhfzCBuUQxMi5llBQ_Content_PP
#define tySequence__OC4OxQhfzCBuUQxMi5llBQ_Content_PP
struct tySequence__OC4OxQhfzCBuUQxMi5llBQ_Content { NI cap; tyObject_StackTraceEntry__cwz3X1atIa8ET8VanDA2pw data[SEQ_DECL_SIZE];};
#endif

      N_LIB_PRIVATE N_NIMCALL(void, writeData__pureZstreams_u175)(tyObject_StreamObj__YejCBqGiUpphaYVvxhpLOQ* s_p0, void* buffer_p1, NI bufLen_p2);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4312)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0);
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void* p_p0);
static N_INLINE(NI, minuspercent___system_u790)(NI x_p0, NI y_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NOINLINE(void, rememberCycle__system_u3269)(NIM_BOOL isDestroyAction_p0, tyObject_RefHeader__b9cZ5ThQEAqSv7VLAQu0wEw* s_p1, TNimTypeV2* desc_p2);
N_LIB_PRIVATE N_NIMCALL(void, nimDestroyAndDispose)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZstreams_u915)(tyObject_FileStreamObj__3EaLUqxHvhPMY9a0V1oV9aPQ** dest_p0);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size_p0, NI alignment_p1);
N_LIB_PRIVATE N_NIMCALL(void, fsClose__pureZstreams_u906)(tyObject_StreamObj__YejCBqGiUpphaYVvxhpLOQ* s_p0);
static N_INLINE(NIM_BOOL, isObjDisplayCheck)(TNimTypeV2* source_p0, NI16 targetDepth_p1, NU32 token_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseObjectConversionError)(void);
N_LIB_PRIVATE N_NIMCALL(void, close__stdZsyncio_u250)(FILE* f_p0);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, fsAtEnd__pureZstreams_u963)(tyObject_StreamObj__YejCBqGiUpphaYVvxhpLOQ* s_p0);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, endOfFile__stdZsyncio_u356)(FILE* f_p0);
N_LIB_PRIVATE N_NIMCALL(void, fsSetPosition__pureZstreams_u966)(tyObject_StreamObj__YejCBqGiUpphaYVvxhpLOQ* s_p0, NI pos_p1);
N_LIB_PRIVATE N_NIMCALL(void, setFilePos__stdZsyncio_u469)(FILE* f_p0, NI64 pos_p1, tyEnum_FileSeekPos__64uV49bBMhJtiSJHjCdTuzg relativeTo_p2);
N_LIB_PRIVATE N_NIMCALL(NI, fsGetPosition__pureZstreams_u969)(tyObject_StreamObj__YejCBqGiUpphaYVvxhpLOQ* s_p0);
N_LIB_PRIVATE N_NIMCALL(NI64, getFilePos__stdZsyncio_u489)(FILE* f_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
N_LIB_PRIVATE N_NIMCALL(NI, fsReadDataStr__pureZstreams_u977)(tyObject_StreamObj__YejCBqGiUpphaYVvxhpLOQ* s_p0, NimStringV2* buffer_p1, tyObject_HSlice__Ft7fsi5uCTryLqJGssT0Jw slice_p2);
N_LIB_PRIVATE N_NIMCALL(NI, readBuffer__stdZsyncio_u155)(FILE* f_p0, void* buffer_p1, NI len_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
N_LIB_PRIVATE N_NIMCALL(NI, fsReadData__pureZstreams_u972)(tyObject_StreamObj__YejCBqGiUpphaYVvxhpLOQ* s_p0, void* buffer_p1, NI bufLen_p2);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, fsReadLine__pureZstreams_u993)(tyObject_StreamObj__YejCBqGiUpphaYVvxhpLOQ* s_p0, NimStringV2* line_p1);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, readLine__stdZsyncio_u271)(FILE* f_p0, NimStringV2* line_p1);
N_LIB_PRIVATE N_NIMCALL(NI, fsPeekData__pureZstreams_u983)(tyObject_StreamObj__YejCBqGiUpphaYVvxhpLOQ* s_p0, void* buffer_p1, NI bufLen_p2);
N_LIB_PRIVATE N_NIMCALL(void, fsWriteData__pureZstreams_u989)(tyObject_StreamObj__YejCBqGiUpphaYVvxhpLOQ* s_p0, void* buffer_p1, NI bufLen_p2);
N_LIB_PRIVATE N_NIMCALL(NI, writeBuffer__stdZsyncio_u186)(FILE* f_p0, void* buffer_p1, NI len_p2);
N_LIB_PRIVATE N_NIMCALL(tyObject_IOError__Vy6h1gTZNMhIMVGxEYGYlg*, newEIO__pureZstreams_u3)(NimStringV2 msg_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u7990)(tyObject_IOError__Vy6h1gTZNMhIMVGxEYGYlg** dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___stdZassertions_u22)(NimStringV2* dest_p0, NimStringV2 src_p1);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e_p0, NCSTRING ename_p1, NCSTRING procname_p2, NCSTRING filename_p3, NI line_p4);
N_LIB_PRIVATE N_NIMCALL(void, fsFlush__pureZstreams_u961)(tyObject_StreamObj__YejCBqGiUpphaYVvxhpLOQ* s_p0);
N_LIB_PRIVATE N_NIMCALL(void, flushFile__stdZsyncio_u259)(FILE* f_p0);
static N_INLINE(void, nimIncRefCyclic)(void* p_p0, NIM_BOOL cyclic_p1);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, atEnd__pureZstreams_u67)(tyObject_StreamObj__YejCBqGiUpphaYVvxhpLOQ* s_p0);
N_LIB_PRIVATE N_NIMCALL(NIM_CHAR, readChar__pureZstreams_u209)(tyObject_StreamObj__YejCBqGiUpphaYVvxhpLOQ* s_p0);
N_LIB_PRIVATE N_NIMCALL(NI, readData__pureZstreams_u79)(tyObject_StreamObj__YejCBqGiUpphaYVvxhpLOQ* s_p0, void* buffer_p1, NI bufLen_p2);
static N_INLINE(void, nimAddCharV1)(NimStringV2* s_p0, NIM_CHAR c_p1);
N_LIB_PRIVATE N_NIMCALL(void, prepareAdd)(NimStringV2* s_p0, NI addlen_p1);
N_LIB_PRIVATE N_NIMCALL(void, setLengthStrV2)(NimStringV2* s_p0, NI newLen_p1);
static N_INLINE(void, prepareMutation__system_u2340)(NimStringV2* s_p0);
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimPrepareStrMutationImpl__system_u2328)(NimStringV2* s_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZstreams_u588)(tyObject_StringStreamObj__Varqg7Zqtz8r284IHsIK5A** dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZstreams_u604)(tyObject_StringStreamObj__Varqg7Zqtz8r284IHsIK5A* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___stdZassertions_u16)(NimStringV2* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, ssClose__pureZstreams_u782)(tyObject_StreamObj__YejCBqGiUpphaYVvxhpLOQ* s_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___pureZstreams_u636)(tyObject_StreamObj__YejCBqGiUpphaYVvxhpLOQ** dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___pureZstreams_u642)(tyObject_StreamObj__YejCBqGiUpphaYVvxhpLOQ** dest_p0, tyObject_StreamObj__YejCBqGiUpphaYVvxhpLOQ* src_p1, NIM_BOOL cyclic_p2);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, ssAtEnd__pureZstreams_u581)(tyObject_StreamObj__YejCBqGiUpphaYVvxhpLOQ* s_p0);
N_LIB_PRIVATE N_NIMCALL(void, ssSetPosition__pureZstreams_u684)(tyObject_StreamObj__YejCBqGiUpphaYVvxhpLOQ* s_p0, NI pos_p1);
N_LIB_PRIVATE N_NIMCALL(NI, clamp__pureZstreams_u688)(NI x_p0, NI a_p1, NI b_p2);
N_LIB_PRIVATE N_NIMCALL(NI, ssGetPosition__pureZstreams_u694)(tyObject_StreamObj__YejCBqGiUpphaYVvxhpLOQ* s_p0);
N_LIB_PRIVATE N_NIMCALL(NI, ssReadDataStr__pureZstreams_u698)(tyObject_StreamObj__YejCBqGiUpphaYVvxhpLOQ* s_p0, NimStringV2* buffer_p1, tyObject_HSlice__Ft7fsi5uCTryLqJGssT0Jw slice_p2);
static N_INLINE(void, copyMem__system_u1720)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(NI, ssReadData__pureZstreams_u755)(tyObject_StreamObj__YejCBqGiUpphaYVvxhpLOQ* s_p0, void* buffer_p1, NI bufLen_p2);
N_LIB_PRIVATE N_NIMCALL(NI, ssPeekData__pureZstreams_u766)(tyObject_StreamObj__YejCBqGiUpphaYVvxhpLOQ* s_p0, void* buffer_p1, NI bufLen_p2);
N_LIB_PRIVATE N_NIMCALL(void, ssWriteData__pureZstreams_u772)(tyObject_StreamObj__YejCBqGiUpphaYVvxhpLOQ* s_p0, void* buffer_p1, NI bufLen_p2);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, open__stdZsyncio_u399)(FILE** f_p0, NimStringV2 filename_p1, tyEnum_FileMode__9atfYUlw9bQtL4ixYGhUZZfQ mode_p2, NI bufSize_p3);
N_LIB_PRIVATE N_NIMCALL(tyObject_FileStreamObj__3EaLUqxHvhPMY9a0V1oV9aPQ*, newFileStream__pureZstreams_u997)(FILE* f_p0);
N_LIB_PRIVATE TNimTypeV2 NTIv2__3EaLUqxHvhPMY9a0V1oV9aPQ_;
extern TNimTypeV2 NTIv2__Vy6h1gTZNMhIMVGxEYGYlg_;
static const struct {
  NI cap; NIM_CHAR data[22+1];
} TM__Ue7tnBcsL67VCiRfvt8q0A_6 = { 22 | NIM_STRLIT_FLAG, "cannot write to stream" };
static const NimStringV2 TM__Ue7tnBcsL67VCiRfvt8q0A_7 = {22, (NimStrPayload*)&TM__Ue7tnBcsL67VCiRfvt8q0A_6};
static const struct {
  NI cap; NIM_CHAR data[0+1];
} TM__Ue7tnBcsL67VCiRfvt8q0A_9 = { 0 | NIM_STRLIT_FLAG, "" };
static const NimStringV2 TM__Ue7tnBcsL67VCiRfvt8q0A_10 = {0, (NimStrPayload*)&TM__Ue7tnBcsL67VCiRfvt8q0A_9};
static const struct {
  NI cap; NIM_CHAR data[23+1];
} TM__Ue7tnBcsL67VCiRfvt8q0A_11 = { 23 | NIM_STRLIT_FLAG, "cannot read from stream" };
static const NimStringV2 TM__Ue7tnBcsL67VCiRfvt8q0A_12 = {23, (NimStrPayload*)&TM__Ue7tnBcsL67VCiRfvt8q0A_11};
N_LIB_PRIVATE TNimTypeV2 NTIv2__Varqg7Zqtz8r284IHsIK5A_;
static const NimStringV2 TM__Ue7tnBcsL67VCiRfvt8q0A_18 = {0, (NimStrPayload*)&TM__Ue7tnBcsL67VCiRfvt8q0A_9};
extern NIM_BOOL nimInErrorMode__system_u4115;
extern TFrame* framePtr__system_u3761;
extern TFrame* framePtr__system_u3761;
extern TFrame* framePtr__system_u3761;
extern TFrame* framePtr__system_u3761;
extern TFrame* framePtr__system_u3761;
extern TFrame* framePtr__system_u3761;
static NIM_CONST NU32 TM__Ue7tnBcsL67VCiRfvt8q0A_3[3] = {3701606400, 3905029632, 1183535616};
N_LIB_PRIVATE TNimTypeV2 NTIv2__3EaLUqxHvhPMY9a0V1oV9aPQ_ = {.destructor = (void*)NIM_NIL, .size = sizeof(tyObject_FileStreamObj__3EaLUqxHvhPMY9a0V1oV9aPQ), .align = (NI16) NIM_ALIGNOF(tyObject_FileStreamObj__3EaLUqxHvhPMY9a0V1oV9aPQ), .depth = 2, .display = TM__Ue7tnBcsL67VCiRfvt8q0A_3, .traceImpl = (void*)NIM_NIL, .flags = 0};
static NIM_CONST NU32 TM__Ue7tnBcsL67VCiRfvt8q0A_17[3] = {3701606400, 3905029632, 2867495680};
N_LIB_PRIVATE TNimTypeV2 NTIv2__Varqg7Zqtz8r284IHsIK5A_ = {.destructor = (void*)eqdestroy___pureZstreams_u604, .size = sizeof(tyObject_StringStreamObj__Varqg7Zqtz8r284IHsIK5A), .align = (NI16) NIM_ALIGNOF(tyObject_StringStreamObj__Varqg7Zqtz8r284IHsIK5A), .depth = 2, .display = TM__Ue7tnBcsL67VCiRfvt8q0A_17, .traceImpl = (void*)NIM_NIL, .flags = 0};
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (NIM_BOOL*)0;
	result = (&nimInErrorMode__system_u4115);
	return result;
}
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u3761 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u3761).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u3761;
	framePtr__system_u3761 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4312();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u3761 = (*framePtr__system_u3761).prev;
}
N_LIB_PRIVATE N_NIMCALL(void, writeData__pureZstreams_u175)(tyObject_StreamObj__YejCBqGiUpphaYVvxhpLOQ* s_p0, void* buffer_p1, NI bufLen_p2) {
NIM_BOOL* nimErr_;
	nimfr_("writeData", "D:\\nim\\lib\\pure\\streams.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(343, "D:\\nim\\lib\\pure\\streams.nim");
	(*s_p0).writeDataImpl(s_p0, buffer_p1, bufLen_p2);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
BeforeRet_: ;
	popFrame();
}
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0) {
	NCSTRING result;
	result = (NCSTRING)0;
	{
		if (!(s_p0.len == ((NI)0))) goto LA3_;
		result = "";
	}
	goto LA1_;
LA3_: ;
	{
		result = ((NCSTRING) ((*s_p0.p).data));
	}
LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, write__pureZstreams_u184)(tyObject_StreamObj__YejCBqGiUpphaYVvxhpLOQ* s_p0, NimStringV2 x_p1) {
NIM_BOOL* nimErr_;
	nimfr_("write", "D:\\nim\\lib\\pure\\streams.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(376, "D:\\nim\\lib\\pure\\streams.nim");
	{
		if (!(((NI)0) < x_p1.len)) goto LA3_;
		nimln_(381);
		writeData__pureZstreams_u175(s_p0, ((void*) (nimToCStringConv(x_p1))), x_p1.len);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA3_: ;
	}
BeforeRet_: ;
	popFrame();
}
static N_INLINE(NI, minuspercent___system_u790)(NI x_p0, NI y_p1) {
	NI result;
	nimfr_("-%", "D:\\nim\\lib\\system\\arithmetics.nim");
	result = (NI)0;
	nimlf_(363, "D:\\nim\\lib\\system\\arithmetics.nim");
	nimln_(364);
	nimln_(368);
	result = ((NI) ((NU)((NU32)(((NU) (x_p0))) - (NU32)(((NU) (y_p1))))));
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void* p_p0) {
	NIM_BOOL result;
NIM_BOOL* nimErr_;
	nimfr_("nimDecRefIsLastCyclicDyn", "D:\\nim\\lib\\system\\orc.nim");
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	nimlf_(478, "D:\\nim\\lib\\system\\orc.nim");
	{
		tyObject_RefHeader__b9cZ5ThQEAqSv7VLAQu0wEw* cell;
		NI T5_;
		if (!!((p_p0 == NIM_NIL))) goto LA3_;
		nimln_(479);
		nimlf_(43, "D:\\nim\\lib\\system\\arc.nim");
		T5_ = (NI)0;
		T5_ = minuspercent___system_u790(((NI) (ptrdiff_t) (p_p0)), ((NI)8));
		cell = ((tyObject_RefHeader__b9cZ5ThQEAqSv7VLAQu0wEw*) (T5_));
		nimlf_(480, "D:\\nim\\lib\\system\\orc.nim");
		{
			if (!((NI)((*cell).rc & ((NI)-16)) == ((NI)0))) goto LA8_;
			nimln_(481);
			result = NIM_TRUE;
		}
		goto LA6_;
LA8_: ;
		{
			NI TM__Ue7tnBcsL67VCiRfvt8q0A_2;
			nimln_(484);
			if (nimSubInt((*cell).rc, ((NI)16), &TM__Ue7tnBcsL67VCiRfvt8q0A_2)) { raiseOverflow(); goto BeforeRet_;
			};
			(*cell).rc = (NI)(TM__Ue7tnBcsL67VCiRfvt8q0A_2);
		}
LA6_: ;
		nimln_(486);
		rememberCycle__system_u3269(result, cell, (*((TNimTypeV2**) (p_p0))));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA3_: ;
	}
BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqsink___pureZstreams_u646)(tyObject_StreamObj__YejCBqGiUpphaYVvxhpLOQ** dest_p0, tyObject_StreamObj__YejCBqGiUpphaYVvxhpLOQ* src_p1) {
	tyObject_StreamObj__YejCBqGiUpphaYVvxhpLOQ* colontmp_;
	colontmp_ = (*dest_p0);
	(*dest_p0) = src_p1;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn(colontmp_);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose(colontmp_);
	}
LA4_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZstreams_u915)(tyObject_FileStreamObj__3EaLUqxHvhPMY9a0V1oV9aPQ** dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0));
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0));
	}
LA4_: ;
}
static N_INLINE(NIM_BOOL, isObjDisplayCheck)(TNimTypeV2* source_p0, NI16 targetDepth_p1, NU32 token_p2) {
	NIM_BOOL result;
	NIM_BOOL T1_;
	nimfr_("isObjDisplayCheck", "D:\\nim\\lib\\system\\arc.nim");
	result = (NIM_BOOL)0;
	nimlf_(211, "D:\\nim\\lib\\system\\arc.nim");
	T1_ = (NIM_BOOL)0;
	T1_ = (targetDepth_p1 <= (*source_p0).depth);
	if (!(T1_)) goto LA2_;
	T1_ = ((*source_p0).display[targetDepth_p1] == token_p2);
LA2_: ;
	result = T1_;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, fsClose__pureZstreams_u906)(tyObject_StreamObj__YejCBqGiUpphaYVvxhpLOQ* s_p0) {
NIM_BOOL* nimErr_;
	nimfr_("fsClose", "D:\\nim\\lib\\pure\\streams.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(1326, "D:\\nim\\lib\\pure\\streams.nim");
	{
		if (s_p0 && !isObjDisplayCheck((*s_p0).Sup.m_type, 2, 1183535616)){ raiseObjectConversionError(); goto BeforeRet_;
		}
		if (!!(((*((tyObject_FileStreamObj__3EaLUqxHvhPMY9a0V1oV9aPQ*) (s_p0))).f == ((FILE*) NIM_NIL)))) goto LA3_;
		nimln_(1327);
		if (s_p0 && !isObjDisplayCheck((*s_p0).Sup.m_type, 2, 1183535616)){ raiseObjectConversionError(); goto BeforeRet_;
		}
		close__stdZsyncio_u250((*((tyObject_FileStreamObj__3EaLUqxHvhPMY9a0V1oV9aPQ*) (s_p0))).f);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimln_(1328);
		if (s_p0 && !isObjDisplayCheck((*s_p0).Sup.m_type, 2, 1183535616)){ raiseObjectConversionError(); goto BeforeRet_;
		}
		(*((tyObject_FileStreamObj__3EaLUqxHvhPMY9a0V1oV9aPQ*) (s_p0))).f = ((FILE*) NIM_NIL);
	}
LA3_: ;
	}
BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, fsAtEnd__pureZstreams_u963)(tyObject_StreamObj__YejCBqGiUpphaYVvxhpLOQ* s_p0) {
	NIM_BOOL result;
NIM_BOOL* nimErr_;
	nimfr_("fsAtEnd", "D:\\nim\\lib\\pure\\streams.nim");
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	nimlf_(1330, "D:\\nim\\lib\\pure\\streams.nim");
	if (s_p0 && !isObjDisplayCheck((*s_p0).Sup.m_type, 2, 1183535616)){ raiseObjectConversionError(); goto BeforeRet_;
	}
	result = endOfFile__stdZsyncio_u356((*((tyObject_FileStreamObj__3EaLUqxHvhPMY9a0V1oV9aPQ*) (s_p0))).f);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	goto BeforeRet_;
	}
BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, fsSetPosition__pureZstreams_u966)(tyObject_StreamObj__YejCBqGiUpphaYVvxhpLOQ* s_p0, NI pos_p1) {
NIM_BOOL* nimErr_;
	nimfr_("fsSetPosition", "D:\\nim\\lib\\pure\\streams.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(1331, "D:\\nim\\lib\\pure\\streams.nim");
	if (s_p0 && !isObjDisplayCheck((*s_p0).Sup.m_type, 2, 1183535616)){ raiseObjectConversionError(); goto BeforeRet_;
	}
	setFilePos__stdZsyncio_u469((*((tyObject_FileStreamObj__3EaLUqxHvhPMY9a0V1oV9aPQ*) (s_p0))).f, ((NI64) (pos_p1)), ((tyEnum_FileSeekPos__64uV49bBMhJtiSJHjCdTuzg)0));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(NI, fsGetPosition__pureZstreams_u969)(tyObject_StreamObj__YejCBqGiUpphaYVvxhpLOQ* s_p0) {
	NI result;
	NI64 T1_;
NIM_BOOL* nimErr_;
	nimfr_("fsGetPosition", "D:\\nim\\lib\\pure\\streams.nim");
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	nimlf_(1332, "D:\\nim\\lib\\pure\\streams.nim");
	if (s_p0 && !isObjDisplayCheck((*s_p0).Sup.m_type, 2, 1183535616)){ raiseObjectConversionError(); goto BeforeRet_;
	}
	T1_ = (NI64)0;
	T1_ = getFilePos__stdZsyncio_u489((*((tyObject_FileStreamObj__3EaLUqxHvhPMY9a0V1oV9aPQ*) (s_p0))).f);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	if ((T1_) < ((NI)(-2147483647 -1)) || (T1_) > ((NI)2147483647)){ raiseRangeErrorI(T1_, ((NI)(-2147483647 -1)), ((NI)2147483647)); goto BeforeRet_;
	}
	result = ((NI) (T1_));
	goto BeforeRet_;
	}
BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, fsReadDataStr__pureZstreams_u977)(tyObject_StreamObj__YejCBqGiUpphaYVvxhpLOQ* s_p0, NimStringV2* buffer_p1, tyObject_HSlice__Ft7fsi5uCTryLqJGssT0Jw slice_p2) {
	NI result;
	NI TM__Ue7tnBcsL67VCiRfvt8q0A_4;
	NI TM__Ue7tnBcsL67VCiRfvt8q0A_5;
NIM_BOOL* nimErr_;
	nimfr_("fsReadDataStr", "D:\\nim\\lib\\pure\\streams.nim");
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	nimlf_(1338, "D:\\nim\\lib\\pure\\streams.nim");
	if (s_p0 && !isObjDisplayCheck((*s_p0).Sup.m_type, 2, 1183535616)){ raiseObjectConversionError(); goto BeforeRet_;
	}
	if (slice_p2.a < 0 || slice_p2.a >= (*buffer_p1).len){ raiseIndexError2(slice_p2.a,(*buffer_p1).len-1); goto BeforeRet_;
	}
	if (nimAddInt(slice_p2.b, ((NI)1), &TM__Ue7tnBcsL67VCiRfvt8q0A_4)) { raiseOverflow(); goto BeforeRet_;
	};
	if (nimSubInt((NI)(TM__Ue7tnBcsL67VCiRfvt8q0A_4), slice_p2.a, &TM__Ue7tnBcsL67VCiRfvt8q0A_5)) { raiseOverflow(); goto BeforeRet_;
	};
	if (((NI)(TM__Ue7tnBcsL67VCiRfvt8q0A_5)) < ((NI)0) || ((NI)(TM__Ue7tnBcsL67VCiRfvt8q0A_5)) > ((NI)2147483647)){ raiseRangeErrorI((NI)(TM__Ue7tnBcsL67VCiRfvt8q0A_5), ((NI)0), ((NI)2147483647)); goto BeforeRet_;
	}
	result = readBuffer__stdZsyncio_u155((*((tyObject_FileStreamObj__3EaLUqxHvhPMY9a0V1oV9aPQ*) (s_p0))).f, ((void*) ((&(*buffer_p1).p->data[slice_p2.a]))), ((NI) ((NI)(TM__Ue7tnBcsL67VCiRfvt8q0A_5))));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, fsReadData__pureZstreams_u972)(tyObject_StreamObj__YejCBqGiUpphaYVvxhpLOQ* s_p0, void* buffer_p1, NI bufLen_p2) {
	NI result;
NIM_BOOL* nimErr_;
	nimfr_("fsReadData", "D:\\nim\\lib\\pure\\streams.nim");
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	nimlf_(1335, "D:\\nim\\lib\\pure\\streams.nim");
	if (s_p0 && !isObjDisplayCheck((*s_p0).Sup.m_type, 2, 1183535616)){ raiseObjectConversionError(); goto BeforeRet_;
	}
	if ((bufLen_p2) < ((NI)0) || (bufLen_p2) > ((NI)2147483647)){ raiseRangeErrorI(bufLen_p2, ((NI)0), ((NI)2147483647)); goto BeforeRet_;
	}
	result = readBuffer__stdZsyncio_u155((*((tyObject_FileStreamObj__3EaLUqxHvhPMY9a0V1oV9aPQ*) (s_p0))).f, buffer_p1, ((NI) (bufLen_p2)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, fsReadLine__pureZstreams_u993)(tyObject_StreamObj__YejCBqGiUpphaYVvxhpLOQ* s_p0, NimStringV2* line_p1) {
	NIM_BOOL result;
NIM_BOOL* nimErr_;
	nimfr_("fsReadLine", "D:\\nim\\lib\\pure\\streams.nim");
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	nimlf_(1350, "D:\\nim\\lib\\pure\\streams.nim");
	if (s_p0 && !isObjDisplayCheck((*s_p0).Sup.m_type, 2, 1183535616)){ raiseObjectConversionError(); goto BeforeRet_;
	}
	result = readLine__stdZsyncio_u271((*((tyObject_FileStreamObj__3EaLUqxHvhPMY9a0V1oV9aPQ*) (s_p0))).f, line_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, fsPeekData__pureZstreams_u983)(tyObject_StreamObj__YejCBqGiUpphaYVvxhpLOQ* s_p0, void* buffer_p1, NI bufLen_p2) {
	NI result;
	NI pos;
NIM_BOOL oldNimErrFin1_;
NIM_BOOL* nimErr_;
	nimfr_("fsPeekData", "D:\\nim\\lib\\pure\\streams.nim");
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	nimlf_(1341, "D:\\nim\\lib\\pure\\streams.nim");
	pos = fsGetPosition__pureZstreams_u969(s_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(1343);
	if (s_p0 && !isObjDisplayCheck((*s_p0).Sup.m_type, 2, 1183535616)){ raiseObjectConversionError(); goto LA1_;
	}
	if ((bufLen_p2) < ((NI)0) || (bufLen_p2) > ((NI)2147483647)){ raiseRangeErrorI(bufLen_p2, ((NI)0), ((NI)2147483647)); goto LA1_;
	}
	result = readBuffer__stdZsyncio_u155((*((tyObject_FileStreamObj__3EaLUqxHvhPMY9a0V1oV9aPQ*) (s_p0))).f, buffer_p1, ((NI) (bufLen_p2)));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		LA1_:;
	}
	{
		oldNimErrFin1_ = *nimErr_; *nimErr_ = NIM_FALSE;
		nimln_(1342);
		fsSetPosition__pureZstreams_u966(s_p0, pos);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		*nimErr_ = oldNimErrFin1_;
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_IOError__Vy6h1gTZNMhIMVGxEYGYlg*, newEIO__pureZstreams_u3)(NimStringV2 msg_p0) {
	tyObject_IOError__Vy6h1gTZNMhIMVGxEYGYlg* result;
	nimfr_("newEIO", "D:\\nim\\lib\\pure\\streams.nim");
	result = NIM_NIL;
	nimlf_(53, "D:\\nim\\lib\\system\\fatal.nim");
	eqdestroy___system_u7990(&result);
	nimlf_(104, "D:\\nim\\lib\\pure\\streams.nim");
	result = (tyObject_IOError__Vy6h1gTZNMhIMVGxEYGYlg*) nimNewObj(sizeof(tyObject_IOError__Vy6h1gTZNMhIMVGxEYGYlg), NIM_ALIGNOF(tyObject_IOError__Vy6h1gTZNMhIMVGxEYGYlg));
	(*result).Sup.Sup.Sup.m_type = (&NTIv2__Vy6h1gTZNMhIMVGxEYGYlg_);
	(*result).Sup.Sup.name = "IOError";
	nimlf_(25, "D:\\nim\\lib\\std\\assertions.nim");
	eqsink___stdZassertions_u22((&(*result).Sup.Sup.message), msg_p0);
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, fsWriteData__pureZstreams_u989)(tyObject_StreamObj__YejCBqGiUpphaYVvxhpLOQ* s_p0, void* buffer_p1, NI bufLen_p2) {
NIM_BOOL* nimErr_;
	nimfr_("fsWriteData", "D:\\nim\\lib\\pure\\streams.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(1346, "D:\\nim\\lib\\pure\\streams.nim");
	{
		NI T3_;
		tyObject_IOError__Vy6h1gTZNMhIMVGxEYGYlg* T6_;
		if (s_p0 && !isObjDisplayCheck((*s_p0).Sup.m_type, 2, 1183535616)){ raiseObjectConversionError(); goto BeforeRet_;
		}
		if ((bufLen_p2) < ((NI)0) || (bufLen_p2) > ((NI)2147483647)){ raiseRangeErrorI(bufLen_p2, ((NI)0), ((NI)2147483647)); goto BeforeRet_;
		}
		T3_ = (NI)0;
		T3_ = writeBuffer__stdZsyncio_u186((*((tyObject_FileStreamObj__3EaLUqxHvhPMY9a0V1oV9aPQ*) (s_p0))).f, buffer_p1, ((NI) (bufLen_p2)));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!!((T3_ == bufLen_p2))) goto LA4_;
		nimln_(1347);
		T6_ = NIM_NIL;
		T6_ = newEIO__pureZstreams_u3(TM__Ue7tnBcsL67VCiRfvt8q0A_7);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		raiseExceptionEx((Exception*)T6_, "IOError", "fsWriteData", "D:\\nim\\lib\\pure\\streams.nim", 1347);
goto BeforeRet_;
	}
LA4_: ;
	}
BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, fsFlush__pureZstreams_u961)(tyObject_StreamObj__YejCBqGiUpphaYVvxhpLOQ* s_p0) {
NIM_BOOL* nimErr_;
	nimfr_("fsFlush", "D:\\nim\\lib\\pure\\streams.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(1329, "D:\\nim\\lib\\pure\\streams.nim");
	if (s_p0 && !isObjDisplayCheck((*s_p0).Sup.m_type, 2, 1183535616)){ raiseObjectConversionError(); goto BeforeRet_;
	}
	flushFile__stdZsyncio_u259((*((tyObject_FileStreamObj__3EaLUqxHvhPMY9a0V1oV9aPQ*) (s_p0))).f);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(tyObject_FileStreamObj__3EaLUqxHvhPMY9a0V1oV9aPQ*, newFileStream__pureZstreams_u997)(FILE* f_p0) {
	tyObject_FileStreamObj__3EaLUqxHvhPMY9a0V1oV9aPQ* result;
	nimfr_("newFileStream", "D:\\nim\\lib\\pure\\streams.nim");
	result = NIM_NIL;
	nimlf_(1326, "D:\\nim\\lib\\pure\\streams.nim");
	eqdestroy___pureZstreams_u915(&result);
	nimln_(1382);
	result = (tyObject_FileStreamObj__3EaLUqxHvhPMY9a0V1oV9aPQ*) nimNewObj(sizeof(tyObject_FileStreamObj__3EaLUqxHvhPMY9a0V1oV9aPQ), NIM_ALIGNOF(tyObject_FileStreamObj__3EaLUqxHvhPMY9a0V1oV9aPQ));
	(*result).Sup.Sup.m_type = (&NTIv2__3EaLUqxHvhPMY9a0V1oV9aPQ_);
	nimln_(1383);
	(*result).f = f_p0;
	nimln_(1384);
	(*result).Sup.closeImpl = fsClose__pureZstreams_u906;
	nimln_(1385);
	(*result).Sup.atEndImpl = fsAtEnd__pureZstreams_u963;
	nimln_(1386);
	(*result).Sup.setPositionImpl = fsSetPosition__pureZstreams_u966;
	nimln_(1387);
	(*result).Sup.getPositionImpl = fsGetPosition__pureZstreams_u969;
	nimln_(1388);
	(*result).Sup.readDataStrImpl = fsReadDataStr__pureZstreams_u977;
	nimln_(1389);
	(*result).Sup.readDataImpl = fsReadData__pureZstreams_u972;
	nimln_(1390);
	(*result).Sup.readLineImpl = fsReadLine__pureZstreams_u993;
	nimln_(1391);
	(*result).Sup.peekDataImpl = fsPeekData__pureZstreams_u983;
	nimln_(1392);
	(*result).Sup.writeDataImpl = fsWriteData__pureZstreams_u989;
	nimln_(1393);
	(*result).Sup.flushImpl = fsFlush__pureZstreams_u961;
	popFrame();
	return result;
}
static N_INLINE(void, nimIncRefCyclic)(void* p_p0, NIM_BOOL cyclic_p1) {
	tyObject_RefHeader__b9cZ5ThQEAqSv7VLAQu0wEw* h;
	NI T1_;
	NI TM__Ue7tnBcsL67VCiRfvt8q0A_8;
	nimfr_("nimIncRefCyclic", "D:\\nim\\lib\\system\\orc.nim");
{	nimlf_(45, "D:\\nim\\lib\\system\\orc.nim");
	nimlf_(43, "D:\\nim\\lib\\system\\arc.nim");
	T1_ = (NI)0;
	T1_ = minuspercent___system_u790(((NI) (ptrdiff_t) (p_p0)), ((NI)8));
	h = ((tyObject_RefHeader__b9cZ5ThQEAqSv7VLAQu0wEw*) (T1_));
	nimlf_(46, "D:\\nim\\lib\\system\\orc.nim");
	if (nimAddInt((*h).rc, ((NI)16), &TM__Ue7tnBcsL67VCiRfvt8q0A_8)) { raiseOverflow(); goto BeforeRet_;
	};
	(*h).rc = (NI)(TM__Ue7tnBcsL67VCiRfvt8q0A_8);
	}
BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___pureZstreams_u642)(tyObject_StreamObj__YejCBqGiUpphaYVvxhpLOQ** dest_p0, tyObject_StreamObj__YejCBqGiUpphaYVvxhpLOQ* src_p1, NIM_BOOL cyclic_p2) {
	tyObject_StreamObj__YejCBqGiUpphaYVvxhpLOQ* colontmp_;
	colontmp_ = (*dest_p0);
	{
		if (!src_p1) goto LA3_;
		nimIncRefCyclic(src_p1, cyclic_p2);
	}
LA3_: ;
	(*dest_p0) = src_p1;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = nimDecRefIsLastCyclicDyn(colontmp_);
		if (!T7_) goto LA8_;
		nimDestroyAndDispose(colontmp_);
	}
LA8_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, close__pureZstreams_u58)(tyObject_StreamObj__YejCBqGiUpphaYVvxhpLOQ* s_p0) {
NIM_BOOL* nimErr_;
	nimfr_("close", "D:\\nim\\lib\\pure\\streams.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(189, "D:\\nim\\lib\\pure\\streams.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = !((s_p0 == 0));
		if (!(T3_)) goto LA4_;
		T3_ = !(((*s_p0).closeImpl == 0));
LA4_: ;
		if (!T3_) goto LA5_;
		nimln_(190);
		(*s_p0).closeImpl(s_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA5_: ;
	}
BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZstreams_u639)(tyObject_StreamObj__YejCBqGiUpphaYVvxhpLOQ** dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0));
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0));
	}
LA4_: ;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, atEnd__pureZstreams_u67)(tyObject_StreamObj__YejCBqGiUpphaYVvxhpLOQ* s_p0) {
	NIM_BOOL result;
NIM_BOOL* nimErr_;
	nimfr_("atEnd", "D:\\nim\\lib\\pure\\streams.nim");
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	nimlf_(204, "D:\\nim\\lib\\pure\\streams.nim");
	result = (*s_p0).atEndImpl(s_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, readData__pureZstreams_u79)(tyObject_StreamObj__YejCBqGiUpphaYVvxhpLOQ* s_p0, void* buffer_p1, NI bufLen_p2) {
	NI result;
NIM_BOOL* nimErr_;
	nimfr_("readData", "D:\\nim\\lib\\pure\\streams.nim");
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	nimlf_(242, "D:\\nim\\lib\\pure\\streams.nim");
	result = (*s_p0).readDataImpl(s_p0, buffer_p1, bufLen_p2);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_CHAR, readChar__pureZstreams_u209)(tyObject_StreamObj__YejCBqGiUpphaYVvxhpLOQ* s_p0) {
	NIM_CHAR result;
NIM_BOOL* nimErr_;
	nimfr_("readChar", "D:\\nim\\lib\\pure\\streams.nim");
{nimErr_ = nimErrorFlag();
	result = (NIM_CHAR)0;
	{
		nimlf_(466, "D:\\nim\\lib\\pure\\streams.nim");
		{
			NI T4_;
			T4_ = (NI)0;
			T4_ = readData__pureZstreams_u79(s_p0, ((void*) ((&result))), ((NI)1));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!!((T4_ == ((NI)1)))) goto LA5_;
			result = 0;
		}
LA5_: ;
	}
	}
BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(void, nimAddCharV1)(NimStringV2* s_p0, NIM_CHAR c_p1) {
	NI TM__Ue7tnBcsL67VCiRfvt8q0A_13;
	NI TM__Ue7tnBcsL67VCiRfvt8q0A_14;
{	prepareAdd(s_p0, ((NI)1));
	(*(*s_p0).p).data[(*s_p0).len] = c_p1;
	if (nimAddInt((*s_p0).len, ((NI)1), &TM__Ue7tnBcsL67VCiRfvt8q0A_13)) { raiseOverflow(); goto BeforeRet_;
	};
	(*(*s_p0).p).data[(NI)(TM__Ue7tnBcsL67VCiRfvt8q0A_13)] = 0;
	if (nimAddInt((*s_p0).len, ((NI)1), &TM__Ue7tnBcsL67VCiRfvt8q0A_14)) { raiseOverflow(); goto BeforeRet_;
	};
	(*s_p0).len = (NI)(TM__Ue7tnBcsL67VCiRfvt8q0A_14);
	}
BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, readLine__pureZstreams_u562)(tyObject_StreamObj__YejCBqGiUpphaYVvxhpLOQ* s_p0) {
	NimStringV2 result;
NIM_BOOL* nimErr_;
	nimfr_("readLine", "D:\\nim\\lib\\pure\\streams.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimlf_(1083, "D:\\nim\\lib\\pure\\streams.nim");
	result = TM__Ue7tnBcsL67VCiRfvt8q0A_10;
	nimln_(1084);
	{
		NIM_BOOL T3_;
		tyObject_IOError__Vy6h1gTZNMhIMVGxEYGYlg* T6_;
		T3_ = (NIM_BOOL)0;
		T3_ = atEnd__pureZstreams_u67(s_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!T3_) goto LA4_;
		nimln_(1085);
		T6_ = NIM_NIL;
		T6_ = newEIO__pureZstreams_u3(TM__Ue7tnBcsL67VCiRfvt8q0A_12);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		raiseExceptionEx((Exception*)T6_, "IOError", "readLine", "D:\\nim\\lib\\pure\\streams.nim", 1085);
goto BeforeRet_;
	}
LA4_: ;
	{
		nimln_(1086);
		while (1) {
			NIM_CHAR c;
			nimln_(1087);
			c = readChar__pureZstreams_u209(s_p0);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			nimln_(1088);
			{
				if (!((NU8)(c) == (NU8)(13))) goto LA11_;
				nimln_(1089);
				c = readChar__pureZstreams_u209(s_p0);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				nimln_(1090);
				goto LA7;
			}
LA11_: ;
			nimln_(1091);
			{
				NIM_BOOL T15_;
				T15_ = (NIM_BOOL)0;
				T15_ = ((NU8)(c) == (NU8)(10));
				if (T15_) goto LA16_;
				T15_ = ((NU8)(c) == (NU8)(0));
LA16_: ;
				if (!T15_) goto LA17_;
				nimln_(1092);
				goto LA7;
			}
			goto LA13_;
LA17_: ;
			{
				nimln_(1094);
				nimAddCharV1((&result), c);
			}
LA13_: ;
		}
	} LA7: ;
	}
BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, readLine__pureZstreams_u547)(tyObject_StreamObj__YejCBqGiUpphaYVvxhpLOQ* s_p0, NimStringV2* line_p1) {
	NIM_BOOL result;
NIM_BOOL* nimErr_;
	nimfr_("readLine", "D:\\nim\\lib\\pure\\streams.nim");
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	nimlf_(1018, "D:\\nim\\lib\\pure\\streams.nim");
	{
		if (!!(((*s_p0).readLineImpl == NIM_NIL))) goto LA3_;
		nimln_(1019);
		result = (*s_p0).readLineImpl(s_p0, line_p1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	goto LA1_;
LA3_: ;
	{
		nimln_(1022);
		setLengthStrV2((&(*line_p1)), ((NI)0));
		{
			nimln_(1023);
			while (1) {
				NIM_CHAR c;
				nimln_(1024);
				c = readChar__pureZstreams_u209(s_p0);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				nimln_(1025);
				{
					if (!((NU8)(c) == (NU8)(13))) goto LA10_;
					nimln_(1026);
					c = readChar__pureZstreams_u209(s_p0);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					nimln_(1027);
					goto LA6;
				}
				goto LA8_;
LA10_: ;
				{
					nimln_(1028);
					if (!((NU8)(c) == (NU8)(10))) goto LA13_;
					goto LA6;
				}
				goto LA8_;
LA13_: ;
				{
					nimln_(1029);
					if (!((NU8)(c) == (NU8)(0))) goto LA16_;
					nimln_(1030);
					{
						if (!(((NI)0) < (*line_p1).len)) goto LA20_;
						goto LA6;
					}
					goto LA18_;
LA20_: ;
					{
						nimln_(1031);
						nimln_(992);
						nimln_(1031);
						result = NIM_FALSE;
						goto BeforeRet_;
					}
LA18_: ;
				}
				goto LA8_;
LA16_: ;
LA8_: ;
				nimln_(1032);
				nimAddCharV1((&(*line_p1)), c);
			}
		} LA6: ;
		nimln_(1033);
		result = NIM_TRUE;
	}
LA1_: ;
	}
BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = !(((*s_p0).p == ((NimStrPayload*) NIM_NIL)));
		if (!(T3_)) goto LA4_;
		T3_ = ((NI)((*(*s_p0).p).cap & ((NI)1073741824)) == ((NI)1073741824));
LA4_: ;
		if (!T3_) goto LA5_;
		nimPrepareStrMutationImpl__system_u2328(s_p0);
	}
LA5_: ;
}
static N_INLINE(void, prepareMutation__system_u2340)(NimStringV2* s_p0) {
	NimStringV2* s_2;
	s_2 = s_p0;
	nimPrepareStrMutationV2(((NimStringV2*) (s_2)));
}
N_LIB_PRIVATE N_NIMCALL(NI, readDataStr__pureZstreams_u85)(tyObject_StreamObj__YejCBqGiUpphaYVvxhpLOQ* s_p0, NimStringV2* buffer_p1, tyObject_HSlice__Ft7fsi5uCTryLqJGssT0Jw slice_p2) {
	NI result;
NIM_BOOL* nimErr_;
	nimfr_("readDataStr", "D:\\nim\\lib\\pure\\streams.nim");
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	nimlf_(253, "D:\\nim\\lib\\pure\\streams.nim");
	{
		if (!!(((*s_p0).readDataStrImpl == NIM_NIL))) goto LA3_;
		nimln_(254);
		result = (*s_p0).readDataStrImpl(s_p0, buffer_p1, slice_p2);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	goto LA1_;
LA3_: ;
	{
		NI TM__Ue7tnBcsL67VCiRfvt8q0A_15;
		NI TM__Ue7tnBcsL67VCiRfvt8q0A_16;
		nimln_(259);
		prepareMutation__system_u2340(buffer_p1);
		nimln_(260);
		if (slice_p2.a < 0 || slice_p2.a >= (*buffer_p1).len){ raiseIndexError2(slice_p2.a,(*buffer_p1).len-1); goto BeforeRet_;
		}
		if (nimAddInt(slice_p2.b, ((NI)1), &TM__Ue7tnBcsL67VCiRfvt8q0A_15)) { raiseOverflow(); goto BeforeRet_;
		};
		if (nimSubInt((NI)(TM__Ue7tnBcsL67VCiRfvt8q0A_15), slice_p2.a, &TM__Ue7tnBcsL67VCiRfvt8q0A_16)) { raiseOverflow(); goto BeforeRet_;
		};
		result = readData__pureZstreams_u79(s_p0, ((void*) ((&(*buffer_p1).p->data[slice_p2.a]))), (NI)(TM__Ue7tnBcsL67VCiRfvt8q0A_16));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA1_: ;
	}
BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZstreams_u588)(tyObject_StringStreamObj__Varqg7Zqtz8r284IHsIK5A** dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0));
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0));
	}
LA4_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZstreams_u604)(tyObject_StringStreamObj__Varqg7Zqtz8r284IHsIK5A* dest_p0) {
	eqdestroy___stdZassertions_u16((&(*dest_p0).data));
}
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___pureZstreams_u636)(tyObject_StreamObj__YejCBqGiUpphaYVvxhpLOQ** dest_p0) {
	(*dest_p0) = 0;
}
N_LIB_PRIVATE N_NIMCALL(void, ssClose__pureZstreams_u782)(tyObject_StreamObj__YejCBqGiUpphaYVvxhpLOQ* s_p0) {
	tyObject_StringStreamObj__Varqg7Zqtz8r284IHsIK5A* s_2;
	tyObject_StreamObj__YejCBqGiUpphaYVvxhpLOQ* colontmpD_;
	nimfr_("ssClose", "D:\\nim\\lib\\pure\\streams.nim");
{	s_2 = NIM_NIL;
	colontmpD_ = NIM_NIL;
	nimlf_(1274, "D:\\nim\\lib\\pure\\streams.nim");
	nimln_(1198);
	eqwasMoved___pureZstreams_u636(&colontmpD_);
	eqcopy___pureZstreams_u642(&colontmpD_, s_p0, NIM_TRUE);
	if (colontmpD_ && !isObjDisplayCheck((*colontmpD_).Sup.m_type, 2, 2867495680)){ raiseObjectConversionError(); goto BeforeRet_;
	}
	s_2 = (*((tyObject_StringStreamObj__Varqg7Zqtz8r284IHsIK5A**) (&(colontmpD_))));
	nimlf_(25, "D:\\nim\\lib\\std\\assertions.nim");
	eqsink___stdZassertions_u22((&(*s_2).data), TM__Ue7tnBcsL67VCiRfvt8q0A_18);
	nimlf_(1198, "D:\\nim\\lib\\pure\\streams.nim");
	eqdestroy___pureZstreams_u588(&s_2);
	}
BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, ssAtEnd__pureZstreams_u581)(tyObject_StreamObj__YejCBqGiUpphaYVvxhpLOQ* s_p0) {
	NIM_BOOL result;
	tyObject_StringStreamObj__Varqg7Zqtz8r284IHsIK5A* s_2;
	nimfr_("ssAtEnd", "D:\\nim\\lib\\pure\\streams.nim");
{	result = (NIM_BOOL)0;
	s_2 = NIM_NIL;
	nimlf_(1198, "D:\\nim\\lib\\pure\\streams.nim");
	if (s_p0 && !isObjDisplayCheck((*s_p0).Sup.m_type, 2, 2867495680)){ raiseObjectConversionError(); goto BeforeRet_;
	}
	s_2 = ((tyObject_StringStreamObj__Varqg7Zqtz8r284IHsIK5A*) (s_p0));
	nimln_(1199);
	nimln_(1197);
	nimln_(1199);
	result = ((*s_2).data.len <= (*s_2).pos);
	goto BeforeRet_;
	}
BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, ssSetPosition__pureZstreams_u684)(tyObject_StreamObj__YejCBqGiUpphaYVvxhpLOQ* s_p0, NI pos_p1) {
	tyObject_StringStreamObj__Varqg7Zqtz8r284IHsIK5A* s_2;
	tyObject_StreamObj__YejCBqGiUpphaYVvxhpLOQ* colontmpD_;
	nimfr_("ssSetPosition", "D:\\nim\\lib\\pure\\streams.nim");
{	s_2 = NIM_NIL;
	colontmpD_ = NIM_NIL;
	nimlf_(1202, "D:\\nim\\lib\\pure\\streams.nim");
	nimln_(1198);
	eqwasMoved___pureZstreams_u636(&colontmpD_);
	eqcopy___pureZstreams_u642(&colontmpD_, s_p0, NIM_TRUE);
	if (colontmpD_ && !isObjDisplayCheck((*colontmpD_).Sup.m_type, 2, 2867495680)){ raiseObjectConversionError(); goto BeforeRet_;
	}
	s_2 = (*((tyObject_StringStreamObj__Varqg7Zqtz8r284IHsIK5A**) (&(colontmpD_))));
	nimln_(1203);
	(*s_2).pos = clamp__pureZstreams_u688(pos_p1, ((NI)0), (*s_2).data.len);
	nimln_(1198);
	eqdestroy___pureZstreams_u588(&s_2);
	}
BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(NI, ssGetPosition__pureZstreams_u694)(tyObject_StreamObj__YejCBqGiUpphaYVvxhpLOQ* s_p0) {
	NI result;
	tyObject_StringStreamObj__Varqg7Zqtz8r284IHsIK5A* s_2;
	nimfr_("ssGetPosition", "D:\\nim\\lib\\pure\\streams.nim");
{	result = (NI)0;
	s_2 = NIM_NIL;
	nimlf_(1206, "D:\\nim\\lib\\pure\\streams.nim");
	if (s_p0 && !isObjDisplayCheck((*s_p0).Sup.m_type, 2, 2867495680)){ raiseObjectConversionError(); goto BeforeRet_;
	}
	s_2 = ((tyObject_StringStreamObj__Varqg7Zqtz8r284IHsIK5A*) (s_p0));
	nimln_(1207);
	nimln_(1205);
	nimln_(1207);
	result = (*s_2).pos;
	goto BeforeRet_;
	}
BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__system_u1720)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
N_LIB_PRIVATE N_NIMCALL(NI, ssReadDataStr__pureZstreams_u698)(tyObject_StreamObj__YejCBqGiUpphaYVvxhpLOQ* s_p0, NimStringV2* buffer_p1, tyObject_HSlice__Ft7fsi5uCTryLqJGssT0Jw slice_p2) {
	NI result;
	tyObject_StringStreamObj__Varqg7Zqtz8r284IHsIK5A* s_2;
	tyObject_StreamObj__YejCBqGiUpphaYVvxhpLOQ* colontmpD_;
	NI TM__Ue7tnBcsL67VCiRfvt8q0A_19;
	NI TM__Ue7tnBcsL67VCiRfvt8q0A_20;
	NI TM__Ue7tnBcsL67VCiRfvt8q0A_21;
	nimfr_("ssReadDataStr", "D:\\nim\\lib\\pure\\streams.nim");
{	result = (NI)0;
	s_2 = NIM_NIL;
	colontmpD_ = NIM_NIL;
	nimlf_(1210, "D:\\nim\\lib\\pure\\streams.nim");
	nimln_(1198);
	eqwasMoved___pureZstreams_u636(&colontmpD_);
	eqcopy___pureZstreams_u642(&colontmpD_, s_p0, NIM_TRUE);
	if (colontmpD_ && !isObjDisplayCheck((*colontmpD_).Sup.m_type, 2, 2867495680)){ raiseObjectConversionError(); goto BeforeRet_;
	}
	s_2 = (*((tyObject_StringStreamObj__Varqg7Zqtz8r284IHsIK5A**) (&(colontmpD_))));
	nimln_(1215);
	prepareMutation__system_u2340(buffer_p1);
	nimln_(1216);
	if (nimAddInt(slice_p2.b, ((NI)1), &TM__Ue7tnBcsL67VCiRfvt8q0A_19)) { raiseOverflow(); goto BeforeRet_;
	};
	if (nimSubInt((NI)(TM__Ue7tnBcsL67VCiRfvt8q0A_19), slice_p2.a, &TM__Ue7tnBcsL67VCiRfvt8q0A_20)) { raiseOverflow(); goto BeforeRet_;
	};
	if (nimSubInt((*s_2).data.len, (*s_2).pos, &TM__Ue7tnBcsL67VCiRfvt8q0A_21)) { raiseOverflow(); goto BeforeRet_;
	};
	result = (((NI)(TM__Ue7tnBcsL67VCiRfvt8q0A_20) <= (NI)(TM__Ue7tnBcsL67VCiRfvt8q0A_21)) ? (NI)(TM__Ue7tnBcsL67VCiRfvt8q0A_20) : (NI)(TM__Ue7tnBcsL67VCiRfvt8q0A_21));
	nimln_(1217);
	{
		NI TM__Ue7tnBcsL67VCiRfvt8q0A_22;
		if (!(((NI)0) < result)) goto LA3_;
		{
			nimln_(1221);
			if (slice_p2.a < 0 || slice_p2.a >= (*buffer_p1).len){ raiseIndexError2(slice_p2.a,(*buffer_p1).len-1); goto BeforeRet_;
			}
			if ((*s_2).pos < 0 || (*s_2).pos >= (*s_2).data.len){ raiseIndexError2((*s_2).pos,(*s_2).data.len-1); goto BeforeRet_;
			}
			if ((result) < ((NI)0) || (result) > ((NI)2147483647)){ raiseRangeErrorI(result, ((NI)0), ((NI)2147483647)); goto BeforeRet_;
			}
			copyMem__system_u1720(((void*) ((&(*buffer_p1).p->data[slice_p2.a]))), ((void*) ((&(*s_2).data.p->data[(*s_2).pos]))), ((NI) (result)));
		}
		nimln_(1222);
		if (nimAddInt((*s_2).pos, result, &TM__Ue7tnBcsL67VCiRfvt8q0A_22)) { raiseOverflow(); goto BeforeRet_;
		};
		(*s_2).pos = (NI)(TM__Ue7tnBcsL67VCiRfvt8q0A_22);
	}
	goto LA1_;
LA3_: ;
	{
		nimln_(1224);
		result = ((NI)0);
	}
LA1_: ;
	nimln_(1198);
	eqdestroy___pureZstreams_u588(&s_2);
	}
BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, ssReadData__pureZstreams_u755)(tyObject_StreamObj__YejCBqGiUpphaYVvxhpLOQ* s_p0, void* buffer_p1, NI bufLen_p2) {
	NI result;
	tyObject_StringStreamObj__Varqg7Zqtz8r284IHsIK5A* s_2;
	tyObject_StreamObj__YejCBqGiUpphaYVvxhpLOQ* colontmpD_;
	NI TM__Ue7tnBcsL67VCiRfvt8q0A_23;
	nimfr_("ssReadData", "D:\\nim\\lib\\pure\\streams.nim");
{	result = (NI)0;
	s_2 = NIM_NIL;
	colontmpD_ = NIM_NIL;
	nimlf_(1227, "D:\\nim\\lib\\pure\\streams.nim");
	nimln_(1198);
	eqwasMoved___pureZstreams_u636(&colontmpD_);
	eqcopy___pureZstreams_u642(&colontmpD_, s_p0, NIM_TRUE);
	if (colontmpD_ && !isObjDisplayCheck((*colontmpD_).Sup.m_type, 2, 2867495680)){ raiseObjectConversionError(); goto BeforeRet_;
	}
	s_2 = (*((tyObject_StringStreamObj__Varqg7Zqtz8r284IHsIK5A**) (&(colontmpD_))));
	nimln_(1228);
	if (nimSubInt((*s_2).data.len, (*s_2).pos, &TM__Ue7tnBcsL67VCiRfvt8q0A_23)) { raiseOverflow(); goto BeforeRet_;
	};
	result = ((bufLen_p2 <= (NI)(TM__Ue7tnBcsL67VCiRfvt8q0A_23)) ? bufLen_p2 : (NI)(TM__Ue7tnBcsL67VCiRfvt8q0A_23));
	nimln_(1229);
	{
		NI TM__Ue7tnBcsL67VCiRfvt8q0A_24;
		if (!(((NI)0) < result)) goto LA3_;
		nimln_(1237);
		if ((*s_2).pos < 0 || (*s_2).pos >= (*s_2).data.len){ raiseIndexError2((*s_2).pos,(*s_2).data.len-1); goto BeforeRet_;
		}
		if ((result) < ((NI)0) || (result) > ((NI)2147483647)){ raiseRangeErrorI(result, ((NI)0), ((NI)2147483647)); goto BeforeRet_;
		}
		copyMem__system_u1720(buffer_p1, ((void*) ((&(*s_2).data.p->data[(*s_2).pos]))), ((NI) (result)));
		nimln_(1238);
		if (nimAddInt((*s_2).pos, result, &TM__Ue7tnBcsL67VCiRfvt8q0A_24)) { raiseOverflow(); goto BeforeRet_;
		};
		(*s_2).pos = (NI)(TM__Ue7tnBcsL67VCiRfvt8q0A_24);
	}
	goto LA1_;
LA3_: ;
	{
		nimln_(1240);
		result = ((NI)0);
	}
LA1_: ;
	nimln_(1198);
	eqdestroy___pureZstreams_u588(&s_2);
	}
BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, ssPeekData__pureZstreams_u766)(tyObject_StreamObj__YejCBqGiUpphaYVvxhpLOQ* s_p0, void* buffer_p1, NI bufLen_p2) {
	NI result;
	tyObject_StringStreamObj__Varqg7Zqtz8r284IHsIK5A* s_2;
	NI TM__Ue7tnBcsL67VCiRfvt8q0A_25;
	nimfr_("ssPeekData", "D:\\nim\\lib\\pure\\streams.nim");
{	result = (NI)0;
	s_2 = NIM_NIL;
	nimlf_(1243, "D:\\nim\\lib\\pure\\streams.nim");
	if (s_p0 && !isObjDisplayCheck((*s_p0).Sup.m_type, 2, 2867495680)){ raiseObjectConversionError(); goto BeforeRet_;
	}
	s_2 = ((tyObject_StringStreamObj__Varqg7Zqtz8r284IHsIK5A*) (s_p0));
	nimln_(1244);
	if (nimSubInt((*s_2).data.len, (*s_2).pos, &TM__Ue7tnBcsL67VCiRfvt8q0A_25)) { raiseOverflow(); goto BeforeRet_;
	};
	result = ((bufLen_p2 <= (NI)(TM__Ue7tnBcsL67VCiRfvt8q0A_25)) ? bufLen_p2 : (NI)(TM__Ue7tnBcsL67VCiRfvt8q0A_25));
	nimln_(1245);
	{
		if (!(((NI)0) < result)) goto LA3_;
		nimln_(1253);
		if ((*s_2).pos < 0 || (*s_2).pos >= (*s_2).data.len){ raiseIndexError2((*s_2).pos,(*s_2).data.len-1); goto BeforeRet_;
		}
		if ((result) < ((NI)0) || (result) > ((NI)2147483647)){ raiseRangeErrorI(result, ((NI)0), ((NI)2147483647)); goto BeforeRet_;
		}
		copyMem__system_u1720(buffer_p1, ((void*) ((&(*s_2).data.p->data[(*s_2).pos]))), ((NI) (result)));
	}
	goto LA1_;
LA3_: ;
	{
		nimln_(1255);
		result = ((NI)0);
	}
LA1_: ;
	}
BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, ssWriteData__pureZstreams_u772)(tyObject_StreamObj__YejCBqGiUpphaYVvxhpLOQ* s_p0, void* buffer_p1, NI bufLen_p2) {
	tyObject_StringStreamObj__Varqg7Zqtz8r284IHsIK5A* s_2;
	tyObject_StreamObj__YejCBqGiUpphaYVvxhpLOQ* colontmpD_;
	NI TM__Ue7tnBcsL67VCiRfvt8q0A_28;
NIM_BOOL* nimErr_;
	nimfr_("ssWriteData", "D:\\nim\\lib\\pure\\streams.nim");
{nimErr_ = nimErrorFlag();
	s_2 = NIM_NIL;
	colontmpD_ = NIM_NIL;
	nimlf_(1258, "D:\\nim\\lib\\pure\\streams.nim");
	nimln_(1198);
	eqwasMoved___pureZstreams_u636(&colontmpD_);
	eqcopy___pureZstreams_u642(&colontmpD_, s_p0, NIM_TRUE);
	if (colontmpD_ && !isObjDisplayCheck((*colontmpD_).Sup.m_type, 2, 2867495680)){ raiseObjectConversionError(); goto LA1_;
	}
	s_2 = (*((tyObject_StringStreamObj__Varqg7Zqtz8r284IHsIK5A**) (&(colontmpD_))));
	nimln_(1259);
	{
		if (!(bufLen_p2 <= ((NI)0))) goto LA4_;
		nimln_(1260);
		nimln_(1198);
		eqdestroy___pureZstreams_u588(&s_2);
		goto BeforeRet_;
	}
LA4_: ;
	nimln_(1261);
	{
		NI TM__Ue7tnBcsL67VCiRfvt8q0A_26;
		NI TM__Ue7tnBcsL67VCiRfvt8q0A_27;
		if (nimAddInt((*s_2).pos, bufLen_p2, &TM__Ue7tnBcsL67VCiRfvt8q0A_26)) { raiseOverflow(); goto LA1_;
		};
		if (!((*s_2).data.len < (NI)(TM__Ue7tnBcsL67VCiRfvt8q0A_26))) goto LA8_;
		nimln_(1262);
		if (nimAddInt((*s_2).pos, bufLen_p2, &TM__Ue7tnBcsL67VCiRfvt8q0A_27)) { raiseOverflow(); goto LA1_;
		};
		if (((NI)(TM__Ue7tnBcsL67VCiRfvt8q0A_27)) < ((NI)0) || ((NI)(TM__Ue7tnBcsL67VCiRfvt8q0A_27)) > ((NI)2147483647)){ raiseRangeErrorI((NI)(TM__Ue7tnBcsL67VCiRfvt8q0A_27), ((NI)0), ((NI)2147483647)); goto LA1_;
		}
		setLengthStrV2((&(*s_2).data), ((NI) ((NI)(TM__Ue7tnBcsL67VCiRfvt8q0A_27))));
	}
LA8_: ;
	nimln_(1270);
	if ((*s_2).pos < 0 || (*s_2).pos >= (*s_2).data.len){ raiseIndexError2((*s_2).pos,(*s_2).data.len-1); goto LA1_;
	}
	if ((bufLen_p2) < ((NI)0) || (bufLen_p2) > ((NI)2147483647)){ raiseRangeErrorI(bufLen_p2, ((NI)0), ((NI)2147483647)); goto LA1_;
	}
	copyMem__system_u1720(((void*) ((&(*s_2).data.p->data[(*s_2).pos]))), buffer_p1, ((NI) (bufLen_p2)));
	nimln_(1271);
	if (nimAddInt((*s_2).pos, bufLen_p2, &TM__Ue7tnBcsL67VCiRfvt8q0A_28)) { raiseOverflow(); goto LA1_;
	};
	(*s_2).pos = (NI)(TM__Ue7tnBcsL67VCiRfvt8q0A_28);
	{
		LA1_:;
	}
	{
		nimln_(1198);
		eqdestroy___pureZstreams_u588(&s_2);
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(tyObject_StringStreamObj__Varqg7Zqtz8r284IHsIK5A*, newStringStream__pureZstreams_u785)(NimStringV2 s_p0) {
	tyObject_StringStreamObj__Varqg7Zqtz8r284IHsIK5A* result;
	nimfr_("newStringStream", "D:\\nim\\lib\\pure\\streams.nim");
	result = NIM_NIL;
	nimlf_(1198, "D:\\nim\\lib\\pure\\streams.nim");
	eqdestroy___pureZstreams_u588(&result);
	nimln_(1294);
	result = (tyObject_StringStreamObj__Varqg7Zqtz8r284IHsIK5A*) nimNewObj(sizeof(tyObject_StringStreamObj__Varqg7Zqtz8r284IHsIK5A), NIM_ALIGNOF(tyObject_StringStreamObj__Varqg7Zqtz8r284IHsIK5A));
	(*result).Sup.Sup.m_type = (&NTIv2__Varqg7Zqtz8r284IHsIK5A_);
	nimlf_(25, "D:\\nim\\lib\\std\\assertions.nim");
	eqsink___stdZassertions_u22((&(*result).data), s_p0);
	nimlf_(1300, "D:\\nim\\lib\\pure\\streams.nim");
	prepareMutation__system_u2340((&(*result).data));
	nimln_(1301);
	(*result).pos = ((NI)0);
	nimln_(1302);
	(*result).Sup.closeImpl = ssClose__pureZstreams_u782;
	nimln_(1303);
	(*result).Sup.atEndImpl = ssAtEnd__pureZstreams_u581;
	nimln_(1304);
	(*result).Sup.setPositionImpl = ssSetPosition__pureZstreams_u684;
	nimln_(1305);
	(*result).Sup.getPositionImpl = ssGetPosition__pureZstreams_u694;
	nimln_(1306);
	(*result).Sup.readDataStrImpl = ssReadDataStr__pureZstreams_u698;
	nimln_(1310);
	(*result).Sup.readDataImpl = ssReadData__pureZstreams_u755;
	nimln_(1311);
	(*result).Sup.peekDataImpl = ssPeekData__pureZstreams_u766;
	nimln_(1312);
	(*result).Sup.writeDataImpl = ssWriteData__pureZstreams_u772;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_FileStreamObj__3EaLUqxHvhPMY9a0V1oV9aPQ*, newFileStream__pureZstreams_u1019)(NimStringV2 filename_p0, tyEnum_FileMode__9atfYUlw9bQtL4ixYGhUZZfQ mode_p1, NI bufSize_p2) {
	tyObject_FileStreamObj__3EaLUqxHvhPMY9a0V1oV9aPQ* result;
	FILE* f;
NIM_BOOL* nimErr_;
	nimfr_("newFileStream", "D:\\nim\\lib\\pure\\streams.nim");
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	f = (FILE*)0;
	nimlf_(1431, "D:\\nim\\lib\\pure\\streams.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = open__stdZsyncio_u399(&f, filename_p0, mode_p1, bufSize_p2);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!T3_) goto LA4_;
		result = newFileStream__pureZstreams_u997(f);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA4_: ;
	}
BeforeRet_: ;
	popFrame();
	return result;
}
